### ISSUE TITLE
orange paper links are unavailable

### ISSUE THREAD

**Issue by JeffreyBPetersen** [ethersphere/swarm#1]
Hopefully they're still around somewhere.

**Comment by JeffreyBPetersen** [comment]
Thank you!

That just leaves the "smash" paper missing (unless it was rolled into the first one).

**Comment by sesam** [comment]
Oh, I got a paper on smash right beside where I found the first one: swarm-gateways.net/bzz:/swarm/ethersphere/orange-papers/2/smash.pdf

The pdf links on https://github.com/ethersphere/swarm are somewhat simlar, but non-working, while the two working and one linked but marked as yet-to-be-published was found here: http://swarm-gateways.net/bzz:/swarm/#the-thsph-orange-paper-series  so setting a webpage update tracker/software agent to watch that page may be worthwhile :)

**Comment by zelig** [comment]
thanks, you know the swarm toy network is flaky plus we are testing and fixing...
