### ISSUE TITLE
`swarm up` doesn't work with large files

### ISSUE THREAD

**Issue by nonsense** [ethersphere/swarm#1000]
Swarm version: 0.3.5 stable

I am not able to consistently upload 1.2GB .. 1.5GB files to local node with `swarm up` and chunk store of 10^7. Sometimes the upload takes 4min and is successful, sometimes it takes 15min and I have to kill the process. There might be a deadlock or a race condition in the pyramid chunker or in the storage layer.

We need a reliable benchmark on how long this is supposed to take and also add automated tests for 1GB, 2GB, 4GB and larger files.

cc @zelig @janos @adamschmideg

**Comment by nonsense** [comment]
Additionally the `bytes read` and `bytes written` from/on disk reported by the process are an order to magnitude bigger than the store size.

3 `swarm up` calls resulting in 3.5GB store size, result in 37GB written by the process, and 30GB read by the process.

**Comment by zelig** [comment]
might be worth trying with new filehasher ftw @nolash
