### ISSUE TITLE
tags - backend for upload progress bars

### ISSUE THREAD

**Issue by zelig** [ethersphere/swarm#1019]
tentative implementation - 

 - https://github.com/ethersphere/go-ethereum/blob/644ffab9986bd68151fc50721eb900c169d8258e/swarm/syncer/tags.go
- https://github.com/ethersphere/go-ethereum/blob/644ffab9986bd68151fc50721eb900c169d8258e/swarm/syncer/tags_test.go

backend for https://github.com/ethersphere/go-ethereum/issues/988

takes over #459, #460, mentioned in #179

todo:
- [x] go through all method comments
- [x] prefix state names with `State` i.e. `StateSplit` instead of just `SPLIT`

**Comment by acud** [comment]
kind of done i'd say
