### ISSUE TITLE
Node running in docker doesn't expose http api port

### ISSUE THREAD

**Issue by petyaracz** [ethersphere/swarm#1021]
#### System information

Version: 0.3.7-unstable
Go Version: go1.10.3
OS: darwin

#### Expected behaviour

Swarm node pulled and run in docker exposes http api port for up/downloads & browser access.

#### Actual behaviour

For e.g. localhost:8501;

`Fatal: Upload failed: Post http://localhost:8501/bzz:/: EOF` for `swarm up` / `ERR_EMPTY_RESPONSE` at http://localhost:8501

#### Steps to reproduce the behaviour

```
docker pull ethdevops/swarm:latest

docker run -p 8501:8500/tcp -e PASSWORD=napernyo -t ethdevops/swarm:latest --  --httpaddr=0.0.0.0 --debug --verbosity 4

open http://localhost:8501
```

**Comment by nonsense** [comment]
This is not a bug, but how the image is supposed to work.

We send the following params to the `swarm` binary, everything else can be defined by the user:

```
exec /swarm --bzzaccount=$BZZACCOUNT --password /password --datadir $DATADIR $@ 2>&1
```

The HTTP interface port is one of these and users are free to assign a different port or not expose it. Therefore we cannot statically EXPOSE it in Docker.

Feel free to re-open if you think I am wrong.

**Comment by nonsense** [comment]
@petyaracz your command is wrong, it should be:

```
docker run -p 8501:8500/tcp -e PASSWORD=napernyo -t ethdevops/swarm:latest --httpaddr=0.0.0.0 --debug --verbosity 4
```

What I meant above is that we don't `EXPOSE 8500` in Docker by default, so you must do `-p 8500:8500` which you already are.

I see that we have the wrong commands in the documentation, will fix them now.

**Comment by petyaracz** [comment]
that's what this was. thanks. id-ing it was harder because with the typo everything worked fine except this. you are right about the ports of course.

**Comment by nonsense** [comment]
This command used to be correct before, but we modified the docker image, and forgot to update docs.
