### ISSUE TITLE
BootNodes entry in config file not working as documented

### ISSUE THREAD

**Issue by adamschmideg** [ethersphere/swarm#1023]
(Upstream original: https://github.com/ethereum/go-ethereum/issues/18004)

https://swarm-guide.readthedocs.io/en/latest/configuration.html claims that parameter BootNodes is supported in config file.

If setting that, I get the following err message on starting swarm:

Fatal: unable to configure swarm: config.toml, line 21: field 'BootNodes' is not defined in api.Config, check github.com/ethereum/go-ethereum/swarm/api/config.go for available fields
The mentioned file (which unfortunately can't be copy'n pasted into a browser address bar) https://github.com/ethereum/go-ethereum/blob/master/swarm/api/config.go does indeed not mention a BootNode parameter.

Using swarm 0.3.6-unstable

**Comment by acud** [comment]
so what's the resolution of this? (i) remove the parameter from the documentation? (ii) add support through the config file?

**Comment by nolash** [comment]
Obsoleted by https://github.com/ethersphere/go-ethereum/issues/1143
