### ISSUE TITLE
Baseline benchmark of upload and download success rate

### ISSUE THREAD

**Issue by adamschmideg** [ethersphere/swarm#1033]
The idea here is to run continuously the `swarm-smoke` tests towards a given environment (https://swarm-gateways.net/ or a given deployment on Kubernetes), and also pushing the `success` or `failure` measurements to InfluxDB/Grafana.

So we need:
1. Cronjobs to run as part of a deployment of Swarm (https://github.com/ethereum/swarm-cluster/pull/90), for example:
- 100kb content (every 10min)?
- 1000kb content (every 1 hour)?
- 10000kb content (every 2-3 hours)?

2. Modify `swarm-smoke` to push `success/failure` measurements to InfluxDB, as well as times that it took to upload and time that it took for the test to finish. https://github.com/ethereum/go-ethereum/pull/18189

3. We should probably modify `swarm-smoke` to not always download concurrently from all nodes a given content upload, but to randomly pick a node and download only from it. Otherwise we are going to have a lot of the content cached on individual nodes, which might hide issues with retrieve requests.

**Comment by nonsense** [comment]
1. Cronjob is ready. https://github.com/ethersphere/helm-charts/pull/13

2. We are in the process of adding configurations and flags to the smoke tests. https://github.com/ethersphere/go-ethereum/pull/1041

**Comment by nonsense** [comment]
What's left to do for this ticket is https://github.com/ethereum/swarm-cluster/issues/103 and then we can close it.

**Comment by adamschmideg** [comment]
Done
