### ISSUE TITLE
refactor AddNode* methods in swarm/network/simulation

### ISSUE THREAD

**Issue by acud** [ethersphere/swarm#1059]
as discussed in https://github.com/ethersphere/go-ethereum/pull/1057, our methods of adding nodes into a simulation are spaghetti and have to be cleaned up and refactored, with the appropriate functionalities moved to `p2p/simulations` package

**Comment by frncmx** [comment]
The original idea was to move `node.go` from `swarm/network/simulation` to `p2p/simulations`.   The methods in `node.go` currently belong to `type Simulation`, those methods would belong to `type Network` after the refactor. However, `Network` has too many methods already and we would double their count (see picture). That we don't want.

As I noticed, most of the methods in `node.go` and `connect.go` are not in use. I considered those as dead code and tried to remove in #1076. However the removal was voted down, as we consider the methods as part of a test helper library.

Another idea from @justelad  was to simplify the interface to something like:
```
Connect(ids []enode.ID,  topology Topology)
AddNodes(count int, topology Topology, opts ...AddNodeOption)
```
But we agreed with @zelig; we don't want to spend that effort on this right now.

![image](https://user-images.githubusercontent.com/1735667/51024738-a20de300-158a-11e9-9d70-75718346f50e.png)
