### ISSUE TITLE
Refactor `kademlia.EachBin`

### ISSUE THREAD

**Issue by holisticode** [ethersphere/swarm#1071]
The `kademlia.EachBin` function is utterly complex and very difficult to reason about, and lacking documentation to understand it.

It is currently exclusively used to evaluate which bins the streamer syncing protocol needs to subscribe to for *pull syncing*.

It should be refactored and documented

**Comment by holisticode** [comment]
The PR addressing this is https://github.com/ethereum/go-ethereum/pull/18355

**Comment by zelig** [comment]
merged as https://github.com/ethereum/go-ethereum/pull/18355
