### ISSUE TITLE
Upload speed for different file sizes

### ISSUE THREAD

**Issue by adamschmideg** [ethersphere/swarm#1091]
We have a Grafana dashboard where we can see the upload time to the 1st node we are connected to.

Create CRON jobs on our Kubernetes cluster which runs uploads, basically feeding the dashboard.

Decide: Are we satisfied with the current upload time?

root issue: #1035

**Comment by frncmx** [comment]
@nonsense Do we have anything similar already?

We are talking here about a [Kubernetes CronJob Controller](https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/#creating-a-cron-job), aren't we? Where should the `cronjob.yml` live?

Regarding the file generation and uploads: I guess we need a Docker image containing the swarm CLI and `head` or `dd`. So the job should just start a script (binary?) which generates some files and uploads to Swarm with the CLI.

Where should the script live? I think it would be easy to write it in Bash, but not to test it. But it's test code anyway and hopefully not something complex. So, Python or Go or just remain with Bash and let go of automated testing?

- How many files do we want to upload?
- How big those files should be?
- Do we want to upload in parallel? If yes, what level?

**Comment by frncmx** [comment]
Note: #1033 can be used as example

**Comment by nonsense** [comment]
@frncmx yes, we have something similar.

Currently two cronjobs live at https://github.com/ethersphere/release-staging

We use `swarm-smoke` to generate the random file and upload it.

I'd rather we write code in Go, rather in Bash - it is easier to test and make sure that it works and compiles.

**Comment by holisticode** [comment]
Closed by:

* https://github.com/ethereum/go-ethereum/pull/18442
* https://github.com/ethersphere/grafana-dashboards/pull/1
* https://github.com/ethersphere/release-staging/pull/4
