### ISSUE TITLE
Download speed for different file sizes

### ISSUE THREAD

**Issue by adamschmideg** [ethersphere/swarm#1092]
We have a Grafana dashboard where we can see the download time to the 1st node we are connected to.

Create CRON jobs on our Kubernetes cluster which runs downloads, basically feeding the dashboard.

Decide: Are we satisfied with the current download time?

**Comment by frncmx** [comment]
Questions asked in [upload speed](https://github.com/ethersphere/go-ethereum/issues/1091#issuecomment-453050608) apply here, too. I think.
