### ISSUE TITLE
Node connects to all others when maxpeers is unlimited

### ISSUE THREAD

**Issue by frncmx** [ethersphere/swarm#1094]
Example:
Node count: 200
Maxpeers set to: 2000
=> You are connected to all nodes. NOK

Expected: not radically different than what you need for healthy connectivity

Regression? We did not use to connect to all the nodes.

Idea: limit number of nodes/bin

The idea to limit the number of connections had been rejected in the past. https://github.com/ethersphere/go-ethereum/pull/406
Also see this document on pruning: https://github.com/ethersphere/go-ethereum/wiki/Pruning,-planning-20180419
the hive bootstrap algorithm should take care of outgoing connections prioritising depth over breadth (of PO bins in the kademlia) thereby protecting rows from being overpopulated. 
However, random peer dialing in the p2p package goes against this.

Restrictive maxpeers setting will prevent nodes from connecting and therefore may have unhealthy kademlia or even remain disjoint from their real neighbourhood which is critical for routing. 
high maxpeers value on the other hand leads to full connectivity

We want to configure the `p2p` package to not connect to any random nodes, and handle connections to new peers from the Swarm Kademlia implementation and `SuggestPeer` functionality.

**Comment by frncmx** [comment]
@zelig clarifies the card

**Comment by nonsense** [comment]
This is currently expected behaviour of the `p2p` package and the `dialstate` runner. Once we have a Swarm bootnode, we can try to disable these, and take over node discovery and connections on Swarm side, rather than have the `dialstate` runner fill our peer slots.

**Comment by zelig** [comment]
will fix after https://github.com/ethersphere/go-ethereum/issues/1111
