### ISSUE TITLE
Create test to validate the distribution of chunks among nodes

### ISSUE THREAD

**Issue by frncmx** [ethersphere/swarm#1095]
Background: There is/was a bug where all chunks got sync to all nodes.

Depends on https://github.com/ethersphere/go-ethereum/issues/1071 

This test would bring  up a cluster of N nodes and would start filling up storage with equal size files f_0, ..., f_i. After that when uploading f_i+j, retrieval of f_j is attempted. 
Report i+j, in which `j` is the aggregate network size, such that f_j is not available. 

`(i+j)*filesize*(MinProxBinSize+1) ~ node_count * storage_capacity`

**Comment by acud** [comment]
further explaination by @nonsense:

> we have to do some kind of sliding window upload and report when older uploads are not available
we should specify “older” as a parameter - it is not clear what capacity the network has so to say
i have tried this manually multiple times but we have to automate it
i would go as far and say that we should not only attempt f_j on step f_i+j, but all f_0 to f_i+j-1
that would put them all in the caches or respective nodes though
