### ISSUE TITLE
Expose node information to allow us building proper tooling to visualize our network.

### ISSUE THREAD

**Issue by skylenet** [ethersphere/swarm#1099]
Create an admin API that exposes the following information about individual swarm nodes:
- [x] peers 
- [x] known nodes
- [x] chunk IDs that are in the local datastore

The API could be in JSON RPC or HTTP.

This would bring up the possibility to create tooling that could iterate over all our nodes (in private deployments) and gather this information. Something similar has been already mention in the roundtable, .e.g "chunk explorer".

**Comment by holisticode** [comment]
https://github.com/ethersphere/go-ethereum/issues/159
https://github.com/ethersphere/go-ethereum/issues/158

Also note that "chunk IDs that are in the local datastore" has security implications and should be something optional. 

The "chunk explorer" task aims indeed at the same goals.

**Comment by holisticode** [comment]
@nonsense my understanding is that you could be tracking who is storing what. What do you think @nagydani, is that something we need to consider?

**Comment by nonsense** [comment]
@holisticode it is my node, so I am free to do whatever I want with it. People who care about privacy should be uploading/syncing encrypted content. Even if we don't implement this, it is trivial to run an iterator on LevelDB and print out all chunks, and therefore review all non-encrypted chunks, so we have to assume that users would do/have already done that.

**Comment by holisticode** [comment]
@nonsense Yes but also from outside like with an API - "What chunks do you have?"

**Comment by nonsense** [comment]
@holisticode yeah, we discussed that this will be an `admin` endpoint or something like that - one that you should not expose unless you know what you are doing. `geth` already has such APIs.

**Comment by janos** [comment]
@justelad Yes, iterating is needed in every request to get all chunks. But iteration should not be on all indexes (for both current or new localstore). We only need to iterate over retrieval index. Also, iteration is not locking the database. Every iterator is taking a snapshot on which it iterates, allowing other operations to commit changes to the log. I have measured that it takes around 0.7s to iterate over 1.000.000 keys on my laptop with pretty good ssd. This is an expensive operation, with 100% cpu utilization.

But I doubt that we would need to provide all chunk keys in one response. Paging is a must for this lists. Having a response with a few million items, even if they are just 32 bytes long, is not efficient for both server and client.

**Comment by nonsense** [comment]
@skylenet for peers, we already have `admin.peers`. We could do something like:

```
# 1. enable apis for a given deployment
    extraFlags:
      - --ws
      - --wsorigins=localhost
      - --wsapi=admin,debug,pss

# 2. port forward to websocket interface on a given node
kubectl port-forward -n tony pods/swarm-private-40 8546:8546

# 3. get peers and extract only enodes
echo '{"jsonrpc":"2.0","method":"admin_peers","id":1}' | websocat ws://localhost:8546 --origin localhost | jq ".[]" | tail -n+3 | jq ".[] | .enode"
```

We could get the node id with
```
echo '{"jsonrpc":"2.0","method":"admin_nodeInfo","id":1}' | websocat ws://localhost:8546 --origin localhost | jq ".[]" | tail -n+3 | jq ".id"
```

This should be mostly enough to construct a network snapshot, once we query all nodes from a given deployment. cc @gluk256

**Comment by holisticode** [comment]
After conversation on standup 29/01/2019, the decision has been taken to actually implement a `HasChunk` method which can be called via API. 

A complete `listChunks` method will be implemented only on `GlobalStore`

**Comment by holisticode** [comment]
Closed by https://github.com/ethereum/go-ethereum/pull/18972

Two possible solutions for `known nodes`:
  * `admin.peers`
  * `GetPeerSubscriptions`

**Comment by nonsense** [comment]
`admin.peers` shows actual peers, not all `known nodes`.
`known nodes` are collected as part of the `hive` protocol. As soon as we have a use-case for them, we should expose them as well in a more structured format (currently they are visible only in the `bzz.hive` string).
