### ISSUE TITLE
Create a swarm bootnode

### ISSUE THREAD

**Issue by nonsense** [ethersphere/swarm#1111]
At the moment both `p2p` package and Swarm `hive` protocol handle node discovery and connections to peers, which is problematic for a number of reasons.

We want to configure the `p2p` package to not connect to any random nodes, and handle connections to new peers from the Swarm Kademlia implementation and `SuggestPeer` functionality.

For this purpose we need to create a Swarm bootnode, which runs the `hive` protocol, so that Swarm Kademlia implementation can take of new connections to nodes.

At the moment the `bootnode` cmd does not run `hive`, so if we turn off `random` peer dialling in the `p2p` package, we end up with 0 peers in all Swarm nodes. However if random peer dialing is on we end up with full connectivity https://github.com/ethersphere/go-ethereum/issues/1094

**Comment by skylenet** [comment]
Prod bootnode setup: https://github.com/ethereum/swarm-cluster/pull/121
