### ISSUE TITLE
reduce the number of errors in http access

### ISSUE THREAD

**Issue by cobordism** [ethersphere/swarm#112]
- [ ] the GET request /favicon.ico should return our favicon bzz:/22481deec05d53e909e4f3933842686113927c67ab2a22c8ad5614e4e3dc505c/favicon.ico
- [ ] the GET request for robots.txt should return a valid robots.txt 
- [ ] the default behaviour of *any* manifest should be to redirect to the entry for '/' and what was previously called the --defaultpath should be the entry at '/' 
- [ ]  the GET request for just '/' (as opposed to bzz:/ etc.) should return a HTTP 200 and some minimal status info, not an error about an invalid protocol https://github.com/ethereum/go-ethereum/blob/master/swarm/api/http/server.go#L555
- [ ] manifests without a default path should default to the behaviour that `?list=true` induces. (Or at least it should be possible to enable this behaviour on the local node)
- [ ]  the GET request to /status should output a status page showing sync status, connected peers, disk usage etc. etc. ... possibly leading in future to a configuration assistant?
- [ ]  The configuration file should be populated with default values or should be edited manually.. currently empty entries in the config file are overwritten by any command line arguments. This leads to funky config files if the first time you run swarm you get an argument wrong.  For example if I change httpaddr to '' in my config and then run swarm with  `--httpaddr doofus`, then I'll have doofus stuck in my config until I change it manually.

**Comment by zelig** [comment]
@homotopycolimit great stuff, are you gonna tackle the fixes?

**Comment by gbalint** [comment]
>The configuration file should be populated with default values or should be edited manually.. currently empty entries in the config file are overwritten by any command line arguments. This leads to funky config files if the first time you run swarm you get an argument wrong. For example if I change httpaddr to '' in my config and then run swarm with --httpaddr doofus, then I'll have doofus stuck in my config until I change it manually.

This should be solved by https://github.com/ethereum/go-ethereum/pull/15548
The other points are covered by these issues:
https://github.com/ethersphere/go-ethereum/issues/153
https://github.com/ethersphere/go-ethereum/issues/154
https://github.com/ethersphere/go-ethereum/issues/155
https://github.com/ethersphere/go-ethereum/issues/156
https://github.com/ethersphere/go-ethereum/issues/158
https://github.com/ethersphere/go-ethereum/issues/162
