### ISSUE TITLE
Kubernetes: Add grafana dashboards to visualise disk usage

### ISSUE THREAD

**Issue by skylenet** [ethersphere/swarm#1126]
Moved from issue: ethereum/swarm-cluster#77

@nonsense wrote:

>We need to add disk i/o utilisation graphs to both persistent volumes and local vm disks, so that we track disk i/o usage on Swarm.

>We are having a lot of issues with it, with Swarm using 100% of available IOPS on current setup. It would be difficult to improve this and add benchmarking tests unless we can monitor it on K8s.

**Comment by nonsense** [comment]
@skylenet This is one of the last resources that I can't really visualise in Swarm, and can't say if it is a bottleneck (it probably is, based on experience).

staging, and my namespaces are not CPU bound or Memory bound, but still some actions are slow. We should see how to add metrics for disk usage within Swarm (localstore) and within Kubernetes for the data volumes.
