### ISSUE TITLE
InfluxDB metrics: Allow lookups via `kademlia base address` and `node address`

### ISSUE THREAD

**Issue by skylenet** [ethersphere/swarm#1134]
Currently we're tagging our metrics only by providing a hostname via a flag `--metrics.influxdb.host.tag` 

It would be nice if our metrics could be tagged with the following keys to make it easier to search metrics by:

- kademlia base address
- node address

Also update our [existing grafana dashboard](https://github.com/ethersphere/grafana-dashboards) to include these new tags.

fyi @nonsense @justelad

**Comment by nonsense** [comment]
Solved here: https://github.com/ethersphere/swarm-docker/pull/4

I am not sure this is what you had in mind, but this would probably help for now.

**Comment by nonsense** [comment]
@skylenet multiple tags PR is merged.

We also have a tool to extract the queen address - `swarm print-keys` - `bzzkey`.

We have to see how to update the docker image so that we run swarm with a `bzzkey` influx tag, or some other solution.

**Comment by skylenet** [comment]
Thanks @nonsense. I'll pick it up from here and will add those tags to our swarm helm charts.

I'm also updating the grafana dashboards to be able to filter by those.

**Comment by skylenet** [comment]
Forwarding the tags to influxdb: https://github.com/ethersphere/helm-charts/pull/52

**Comment by skylenet** [comment]
Grafana dashboard update: https://github.com/ethersphere/grafana-dashboards/pull/3

**Comment by skylenet** [comment]
All changes have been merged and applied to our staging env.
