### ISSUE TITLE
proper error handling in pss sendMsg

### ISSUE THREAD

**Issue by zelig** [ethersphere/swarm#1140]
AFAICT `sendMsg` in pss
https://github.com/ethereum/go-ethereum/blob/master/swarm/pss/pss.go#L899

is incorrect.

- I think the function should return an error and be logged in the forward function
- pss caps check is not needed if
  - fwdPool only contains the peer if it has pss enabled AND
  - pp is checked for nil

**Comment by nolash** [comment]
seems stale
