### ISSUE TITLE
Local cache for uploads

### ISSUE THREAD

**Issue by holisticode** [ethersphere/swarm#1144]
From the swarm channel:

> and another: when you upload something to swarm and it disappears / isn't downloadable.. how do you troubleshoot?
> ie it's not available 5 mins, 5 hours or a day after uploading
> (with the local node running, all the time)

This is actually pretty bad for user perception.

Maybe we should be doing something IPFS like - that every node had an additional cache where it saves stuff uploaded to itself.
Because the moment we chunk up files, the local node does not have the file anymore, and we need a well working network right away
Maybe as a crook until we have version 1.0...

Only the local node would be accessing that cache (FIFO)

^ this comes up many times ^

Seems to be some "implicit" assumption by many users...
Although, of course, this assumption could be biased, maybe due to the use of IPFS or other systems.

In any case it would help to improve user perception, for sure.

**Comment by cobordism** [comment]
Related: https://hackmd.io/t-OQFK3mTsGfrpLCqDrdlw#A-separate-local-cache

**Comment by holisticode** [comment]
Related: https://gist.github.com/nagydani/8b8efc82da5fd8fe84f64ccda9ac0d38

**Comment by acud** [comment]
related to/duplicate of https://github.com/ethersphere/go-ethereum/issues/1274
