### ISSUE TITLE
swarm/network: Complete healthy parameters

### ISSUE THREAD

**Issue by nolash** [ethersphere/swarm#1145]
Currently a node can be healthy by having neighbours only. 

AFAIK, the current idea of healthiness is:

* you know of and are connected to all neighbors
* if depth value is greater than 0, you should know of and be connected to at least one peer in each bin shallower than depth.

Previously we had a method `full` which I _believe_ was part of making sure of this. It can be found eg. in 362e2ba792927282c41acda05cb1a7cd34e1c790

For the abandoned work on the kademlia cleanup I introduced a notion "potent" which was supposed to be this exact check. It also has unit tests. The branch in question is here: https://github.com/ethersphere/go-ethereum/pull/1108

Hopefully the task is not much more than superimposing this work on top of the current head, and making sure that the simulation tests have the right expectations.

**Comment by holisticode** [comment]
After a call with @zelig it became clear that the work for this ticket is not correctly described.

According to @zelig we need to refactor the notion of `Saturated` such that the `PeerPot` is passed the *ideal* version of the kademlia, and then compare with the *real* one - that will determine saturation.

The rows below the `depth` there is a *choice* of multiple peers to fill the bins, so we compare connections with `MinBinSize`; the nearest neighbours will need exact match

**Comment by holisticode** [comment]
Closed by https://github.com/ethereum/go-ethereum/pull/19071
