### ISSUE TITLE
network: clean shutdown for Fetcher is impossible

### ISSUE THREAD

**Issue by frncmx** [ethersphere/swarm#1148]
**Problem**

`FetcherFactory.New()` starts a goroutine (`go fetcher.run()`) without providing a way to wait for that goroutine to finish on shutdown. Basically, `Fetcher.run()` crashes randomly on every shutdown. What kind of problem that can cause? 

**Solution**

`FetcherFactory.New()` must return quit channel. When context is cancelled to initiate the shutdown, that channel must be closed eventually.

Then the wait for that shutdown signal must be implemented at every place where `New()` is called. Including `TestFetcherFactory`.

**Comment by nolash** [comment]
Pending https://github.com/ethersphere/go-ethereum/issues/1181 after which it will hopefully become clearer whether "crashing" the `Fetcher` subthreads is a problem or not.
