### ISSUE TITLE
Monitoring production swarm-bootnodes

### ISSUE THREAD

**Issue by skylenet** [ethersphere/swarm#1191]
Currently there is no monitoring setup for the prod bootnodes that we have.

It would be nice to get alerts when:

- VM is not responsive
- Bootnode process is not responsive

**Comment by nonsense** [comment]
One way we could address this is to make sure that swarm bootnodes emit the number of peers they have, forward to influx/datadog and have an alert if data stops flowing in.

**Comment by skylenet** [comment]
PR in here: https://github.com/ethereum/swarm-cluster/pull/138

**Comment by skylenet** [comment]
The alert definitions can be found in here: https://github.com/ethereum/swarm-cluster/pull/139
