### ISSUE TITLE
Re-enable long-running integration tests

### ISSUE THREAD

**Issue by adamschmideg** [ethersphere/swarm#1192]
We have a `longrunning` flag, which separates test with short and long run time. Currently these tests do not run as part of the CI. Tests not run regularly might become broken.

- [ ] Try to run `-longrunning` tests locally. Do they pass? If not, create issues to fix them.
- [ ] If tests are consistently passing, try to run them on Travis in a separate `matrix.include` entry. Do they pass? Do we hit any limit, e.g., memory? If there is a problem, how do we deal with it? => New issue + Discussions.
- [ ] If all the above are done, make sure running these tests becomes the part of the normal CI flow. How long do they take? Daily CRON or every integration?

This issue is prerequisite of #1175

**Comment by holisticode** [comment]
Closed by https://github.com/ethereum/go-ethereum/pull/19208
