### ISSUE TITLE
Trigger debug functionality after smoke tests (upload_and_sync) timeouts

### ISSUE THREAD

**Issue by nonsense** [ethersphere/swarm#1196]
Having built a few debug tools, such as:
- get all references from content
- `hasChunks` RPC
- extract network topology

It'd be nice to use them when smoke tests (`upload_and_sync`) timeout, so that we get additional debug information when a failure happens.

This ticket is about triggering the debug functionality when `upload_and_sync` timeouts, so that we can understand why Swarm timeouts:
- it could be due to garbage collection removing parts of the uploaded content
- it could be due to failure in the retrieve requests

**Comment by holisticode** [comment]
Closed by https://github.com/ethereum/go-ethereum/pull/19101
