### ISSUE TITLE
Installation Unable to install Swarm via PPA

### ISSUE THREAD

**Issue by jdetychey** [ethersphere/swarm#12]
Hello,
Looks like the swarm package is missing:
`sudo apt-get install ethereum-swarm`
>Reading package lists... Done
>Building dependency tree       
>Reading state information... Done
>E: Unable to locate package ethereum-swarm

**Comment by homotopycolimit** [comment]
thank you for the report.
We are in fact in the process of rewriting all the ppa configs.

**Comment by nonsense** [comment]
Sorry @jdetychey , our documentation is not accurate with respect to the Ubuntu Swarm package right now :( Here is the PR which addresses this, and hopefully this will be resolved within a week-or-two on next release - https://github.com/ethereum/go-ethereum/pull/16988

Until then, you can install `swarm`, but adding the `ethereum` ppa (as explained in the docs) and then running:

```
apt-get install swarm=1.8.12+build14270+xenial
```
(or change `xenial` to your distro)

**Comment by nonsense** [comment]
Note that `swarm` is actually conflicting with another package, and because of this we are renaming it to `ethereum-swarm`, so that you don't have to specific exact versions in the future.

**Comment by jdetychey** [comment]
<3 you guys rock, swarm is such a great tool!

**Comment by nonsense** [comment]
A bit too quick. Our PPA repository hit its maximum size, so the latest stable builds are not there yet. Will comment here when this is addressed.

**Comment by nonsense** [comment]
@jdetychey this should work now. You can install v0.3.1 through `ethereum-swarm`

**Comment by homotopycolimit** [comment]
New downloads page: 
https://swarm-gateways.net/bzz:/theswarm.eth/downloads/

New swarm package in ubuntu ppa
```
sudo apt-get install software-properties-common
sudo add-apt-repository -y ppa:ethereum/ethereum
sudo apt-get update
sudo apt-get install ethereum-swarm
```
