### ISSUE TITLE
Rewrite the stream package

### ISSUE THREAD

**Issue by adamschmideg** [ethersphere/swarm#1204]
Make it unit testable, not only with simulation.
Remove unneeded generalization.
Do not introduce unnecessary abstractions too early.
Revisit requirements.

**Comment by nonsense** [comment]
I find this ticket underspecified. Rewriting this package is a huge task, we should probably include more details on:
1. Why we want to rewrite the package - basically describe the current state of the system, and its current problems with specific examples.
2. Define the ideal scenario we envision.
3. Describe in concrete steps (if we know these already) how to achieve 2.
