### ISSUE TITLE
swarm/network: Prefer external address in discovery.

### ISSUE THREAD

**Issue by nolash** [ethersphere/swarm#1219]
Example; Nodes `A`, `B` and `C` are started without `--nat` flag. Their enode strings _used in the swarm handshake_ will all have localhost.

You find a subnet ip for `A` that's reachable from `B` and `C`. You replace the localhost in the enode string with this ip. Then you execute RPC call `admin.addPeer` with that enode string to `B` and `C`. 

**Result: `B` and `C` will have connected to `A`, but not have connected to each other.**

It seems that in the discovery protocol, `B` and `C` still "convince" A that they exist on localhost, and when A suggests B to C, it will be with localhost as the host part.

Instead, it would be more natural that A stores the ip from the interface the request can in on, and propagates _this_ as the host part.

Note; the same problem applies if you do the `admin.addPeer` on `A` to `B` and `C`.

**Comment by nonsense** [comment]
I am not sure this is a bug. If `peer A` is connecting to `peer B` with a given `enode`, `peer B` should not infer and overwrite the address that `peer A` is advertising.

If `peer A` is advertising `localhost`, then this is misconfiguration on A's side.

In the world of NAT, you might have many different remote IPs along the way, and it is not safe to infer the actual remote peer IP.
