### ISSUE TITLE
Swarm helm chart: Expose websocket interface

### ISSUE THREAD

**Issue by skylenet** [ethersphere/swarm#1220]
Currently the [swarm helm chart](https://github.com/ethersphere/helm-charts/tree/master/swarm) is only exposing the http (--bzzport) and it would be nice if we could also expose the websocket interface (--wsport) via an ingress resource.

This should be optional and disabled by default.

A use case given by @nolash would be to call some PSS apis via the websocket interface.

Also double check which wsapi's are enabled by default, we don't want to expose admin interfaces to the internet :)

**Comment by skylenet** [comment]
@nolash What was a good use-case for this again? I was just wondering why a simple tunnel using `kubectl proxy` or `kubectl port-forward` isn't enough. Maybe we should really try to avoid exposing this port to the internet.

**Comment by nolash** [comment]
Let's say I want to demo something pss with someone who's not technically inclined. I could bring up a few nodes, demo whatever needs to be demoed, take it down again. The alternative would be that person has to run a swarm node themselves. It is only intended as short temporary fixtures. If you want and feels better (and if it's possible) you can limit the access to expose that port to the internet for my namespace only. @skylenet

**Comment by skylenet** [comment]
PR in here: https://github.com/ethersphere/helm-charts/pull/57
