### ISSUE TITLE
network/stream: investigate TestDeliveryFromNodes timeouts

### ISSUE THREAD

**Issue by frncmx** [ethersphere/swarm#1247]
From @zelig:
> this test really should not time out, it is either set to too small timeout duration or there's a bug.

src: https://github.com/ethersphere/go-ethereum/pull/1243#discussion_r258516601

**How to reproduce**

1) Create a branch.
2) Modify `.travis.yml` to run just the Race Detector job, but the whole suite. Timeout does not happen if the test runs just by itself. (Remove everything else from `- include` group.)
3) Push that branch to ethersphere and make sure your job gets triggered. [Travis builds](https://travis-ci.org/ethersphere/go-ethereum/builds)
=> The job should fail. (`TestDeliveryFromNodes github.com/ethereum/go-ethereum/swarm/network/stream`)

**Test run time**

*If run alone*

```
--- PASS: TestDeliveryFromNodes (77.97s)
    --- PASS: TestDeliveryFromNodes/testDeliveryFromNodes_2_200_skipCheck_true (4.40s)
    --- PASS: TestDeliveryFromNodes/testDeliveryFromNodes_2_200_skipCheck_false (4.51s)
    --- PASS: TestDeliveryFromNodes/testDeliveryFromNodes_4_200_skipCheck_true (5.92s)
    --- PASS: TestDeliveryFromNodes/testDeliveryFromNodes_4_200_skipCheck_false (5.76s)
    --- PASS: TestDeliveryFromNodes/testDeliveryFromNodes_8_200_skipCheck_true (8.99s)
    --- PASS: TestDeliveryFromNodes/testDeliveryFromNodes_8_200_skipCheck_false (9.27s)
    --- PASS: TestDeliveryFromNodes/testDeliveryFromNodes_16_200_skipCheck_true (19.27s)
    --- PASS: TestDeliveryFromNodes/testDeliveryFromNodes_16_200_skipCheck_false (19.87s)
```

**Questions**

* Do we care about the added complexity of `if testutil.RaceEnabled`?
* Do we expect to learn anything new if we run not just 2 and 4 nodes, but 8 and 16? 
* Does that - having more nodes - worth the extra 60s added to total testing time? **Even if we can run the tests, should we?**
~* Is this investigation and possible fix the best way to use our time?~ *obsolete*: tests are passing after https://github.com/ethereum/go-ethereum/pull/19443

**Comment by frncmx** [comment]
Note: running with https://github.com/ethereum/go-ethereum/pull/19443 - the PR frees up 10% of Travis memory - the tests seem to pass even with 8 and 16 nodes.

If we consider all the questions from the description, **should we enable the tests and add 60s to total test run time**? 

What do you think @nonsense  and @janos?

**Comment by frncmx** [comment]
Actually, I think I would just change the comment. So it would not be misleading, but leave the tests disabled.

I think if we run more nodes we just might learn about a race in some weird error scenario that we don't have a test for. That doesn't worth the extra 60s for me.

**Comment by nonsense** [comment]
`skipCheck` has no effect on production code, so I am not sure what this test is supposed to test. This was never documented, it is dead code, and I have actually removed it in the in-progress branch `simplify-fetchers`.

**Comment by janos** [comment]
Maybe just to remove skipCheck option for subtests.

**Comment by frncmx** [comment]
@nonsense I see that you disabled `TestDeliveryFromNodes` by changing its name to `XTestDeliveryFromNodes` on your branch. Are you going to remove the test completely or just the `skipCheck` part?
