### ISSUE TITLE
ci: run race detector on p2p packages

### ISSUE THREAD

**Issue by frncmx** [ethersphere/swarm#1249]
In https://github.com/ethersphere/go-ethereum/pull/1205 we only run `-race` for `swarm/...` as [Elad suggests](https://github.com/ethersphere/go-ethereum/pull/1205#discussion_r256261721) that would be great to run `-race` on `p2p` ~~and `cmd/swarm`~~.

Let's try and see if something breaks.

**Prerequisite issues**
- [x] https://github.com/ethersphere/go-ethereum/issues/1285
- [x] https://github.com/ethersphere/go-ethereum/issues/1286

**Comment by frncmx** [comment]
@justelad you suggested to extend the scope of the race detector job. I think that's a great idea now I'm trying to make tnat work.

You suggested to cover the whole `p2p` but after looking at it I think a lot of code we don't own there. What do you think if we run the race detector on the following packages?

- `cmd/swarm/...`
- `p2p/{protocols,simulations,testing}/...`

**Comment by acud** [comment]
that would be great @frncmx. sounds good to me :+1:

**Comment by frncmx** [comment]
Covering `cmd/swarm` has been moved to https://github.com/ethersphere/go-ethereum/issues/1301

(just to follow small incremental releases as `cmd/swarm` seems to take more time than expected)
