### ISSUE TITLE
unhealthy snapshot passes health check in kademlia.go

### ISSUE THREAD

**Issue by acud** [ethersphere/swarm#1263]
A 6 node snapshot was generated in the `swarm-snapshot` passes the health check in `kademlia.GetHealthInfo`:
```
Thu Feb 21 13:27:31 UTC 2019 KΛÐΞMLIΛ hive: queen's address: 57d759
population: 2 (5), NeighbourhoodSize: 2, MinBinSize: 2, MaxBinSize: 4
============ DEPTH: 0 ==========================================
000  0                              |  2 c6c1 (1) e90d (0)
001  1 02de                         |  1 02de (0)
002  1 6ef4                         |  1 6ef4 (0)
003  0                              |  0
004  0                              |  0
005  0                              |  1 52b0 (0)
006  0                              |  0
007  0                              |  0
008  0                              |  0
009  0                              |  0
010  0                              |  0
011  0                              |  0
012  0                              |  0
013  0                              |  0
014  0                              |  0
015  0                              |  0
=========================================================================
```

The Swarm snapshot binary calls the `WaitTillHealthy` method which apparently returns a false true.
in `GetHealthInfo`, there is the following method call:
`gotnn, countgotnn, culpritsgotnn := k.connectedNeighbours(pp.NNSet)` which apparently returns `gotnn=true` as a false true.

**Comment by nolash** [comment]
Also the `simulation.WaitTillHealthy()` seems to only check that connection is made to NN. This _still_  makes it possible for something to be healthy with only 2 connected nodes, even if you have many more in the network. Any simulation test that passes with topologies generated from this case passes on a false premise.

**Comment by gluk256** [comment]
here is a [sample file](https://gist.github.com/gluk256/e4ce6e18b5d407d98acb299c1ca1879d)

**Comment by zelig** [comment]
thanks guys, rabbit hole ah? well. this should be pretty clearly not healthy. Could someone write a unit test that catches this?

**Comment by acud** [comment]
@zelig, @holisticode, the actual snapshot file might not necessarily reveal the problem WaitTillHealthy as the Healthy function might be called before the node knows all NNs
