### ISSUE TITLE
p2p and p2p/protocols packages handle messages synchronously

### ISSUE THREAD

**Issue by nonsense** [ethersphere/swarm#130]
The `p2p` and `p2p/protocols` packages are reading and then handling requests/messages synchronously.

As a result the PSS protocol is deadlocking on the `sim` adapter (which uses a `net.Pipe`).

```
# p2p/peer.go

func (p *Peer) readLoop(errc chan<- error) {
	defer p.wg.Done()
	for {
		msg, err := p.rw.ReadMsg()
		if err != nil {
			errc <- err
			return
		}
		msg.ReceivedAt = time.Now()
		if err = p.handle(msg); err != nil {
			errc <- err
			return
		}
	}
}

# p2p/protocols/protocol.go

// Run starts the forever loop that handles incoming messages
// called within the p2p.Protocol#Run function
func (p *Peer) Run(handler func(msg interface{}) error) error {
	for {
		if err := p.handleIncoming(handler); err != nil {
			return err
		}
	}
}
```

In effect the PSS protocol is handling one request/message at a time.

Let's discuss what's the best way to address the deadlock:
1. Add concurrent multi-message handling to the PSS protocol ?
2. Keep the synchronous behaviour, but make sure we have a sufficiently big read/write buffer on each connection/adapter ?
3. Other ideas ?

**Comment by lmars** [comment]
> The p2p and p2p/protocols packages are reading and then handling requests/messages synchronously.

I think this is the correct behaviour. There is a read loop which "dispatches" the message to a handler (albeit synchronously). If the handler needs to handle more than one message at a time, it should spawn a goroutine to handle the message and then continue to handle the next message.

As a typical example:

```
func handler(msg interface{}) error {
	if err := validate(msg); err != nil {
		return err
	}
	go process(msg)
	return nil
}
```

This is the pattern used in Ethereum, for example [here](https://github.com/ethereum/go-ethereum/blob/master/eth/handler.go#L620-L650) a block is received, it is validated then passed to a goroutine.

**Comment by nonsense** [comment]
@lmars thanks for the example! This is exactly how I understand it as well.

**Comment by nolash** [comment]
We decide then to go with 1.
