### ISSUE TITLE
garbage collection overflow

### ISSUE THREAD

**Issue by nonsense** [ethersphere/swarm#1300]
We are getting the following logs from nodes on swarm-gateways.net

```
DEBUG[03-18|09:11:15.741|swarm/storage/ldbstore.go:213]        startgc                                  requested=-209428885 target=-20942888
DEBUG[03-18|09:11:15.741|swarm/storage/ldbstore.go:335]        collectGarbage                           target=-20942888 entryCnt=18446744073500122731
DEBUG[03-18|09:11:15.741|swarm/storage/ldbstore.go:378]        garbage collect done                     c=0
DEBUG[03-18|09:11:15.742|swarm/storage/ldbstore.go:213]        startgc                                  requested=-209428885 target=-20942888
DEBUG[03-18|09:11:15.742|swarm/storage/ldbstore.go:335]        collectGarbage                           target=-20942888 entryCnt=18446744073500122731
DEBUG[03-18|09:11:15.742|swarm/storage/ldbstore.go:378]        garbage collect done                     c=0
DEBUG[03-18|09:11:15.743|swarm/storage/ldbstore.go:213]        startgc                                  requested=-209428885 target=-20942888
DEBUG[03-18|09:11:15.744|swarm/storage/ldbstore.go:335]        collectGarbage                           target=-20942888 entryCnt=18446744073500122731
DEBUG[03-18|09:11:15.744|swarm/storage/ldbstore.go:378]        garbage collect done                     c=0
DEBUG[03-18|09:11:15.745|swarm/storage/ldbstore.go:213]        startgc                                  requested=-209428885 target=-20942888
DEBUG[03-18|09:11:15.746|swarm/storage/ldbstore.go:335]        collectGarbage                           target=-20942888 entryCnt=18446744073500122731
DEBUG[03-18|09:11:15.746|swarm/storage/ldbstore.go:378]        garbage collect done                     c=0
```

I am not sure if we are supposed to be getting a negative values for `target`.

**Comment by nonsense** [comment]
Additionally, we are running nodes on swarm-gateways.net with 10000000 store.size, but we have nodes with 57GB, 52GB, 48GB datadirs, which seems a bit excessive.

**Comment by acud** [comment]
@nonsense, the negative values are due to the fact that our entry count key is corrupt and causing the gc run calculation to overflow. i'm not sure why or how this happened but we should think about a way to rebuild this piece of information. maybe do a consistency check on boot with the shed functionality of counting how many entries for a specific index? WDYT @nonsense @janos

**Comment by acud** [comment]
i think what we could also add is a read of the persisted value on boot, then actually count the entries in the retrieval index, and print a message `if persistedValue != actualValue`, it would allow us to see if there are some possible data races that we haven't caught yet.

**Comment by nonsense** [comment]
@justelad @janos this is on current master - isn't this going to solve itself when we release the new local store?

**Comment by janos** [comment]
@nonsense yes, that is correct.

**Comment by acud** [comment]
but we still don't have any safety or safeguard to verify that these values are correct - we don't perform any consistency checks. for me this has been consistently a pain point

**Comment by janos** [comment]
@justelad this issue is for code that is not used in the new localstore and does not use shed. We can discuss about gcSize, locking and tests in new localstore, again, if you want.
