### ISSUE TITLE
Automate bzz:/theswarm.eth website deployment

### ISSUE THREAD

**Issue by nonsense** [ethersphere/swarm#1306]
Our website code is located at https://github.com/ethersphere/swarm-home and a beta preview is available at https://ethersphere.github.io/swarm-home/

However our main website is hosted on Swarm at bzz:/theswarm.eth/ available from https://swarm-gateways.net/bzz:/theswarm.eth/ as well as https://ethswarm.org

Automate the releaser proccess so that every time we merge a PR to the code repo:
1. A release gets generated
2. Release gets published to swarm
3. ENS gets updated (Maybe use feeds for this, instead?)

This wasn't done the last time we merged a PR, so we should do it now :)

**Comment by skylenet** [comment]
A Travis job has been added and we can now automatically create releases and upload them to swarm. See the most recent releases: https://github.com/ethersphere/swarm-home/releases 

The missing question now is: How do we want to deal with ENS updates?

**Comment by nonsense** [comment]
These happen manually, and @homotopycolimit does them.

Once we have a stable Swarm release, we could add a Swarm Feed, but we are not there yet.
