### ISSUE TITLE
network fetcher should not request peers outside nearest neighbourhood if chunk falls within depth

### ISSUE THREAD

**Issue by zelig** [ethersphere/swarm#1328]
in the current implementation of the `delivery.RequestPeer` we allow node to send request to a peer ourside the nearest neighbourhood even in case the chunk falls within the node's depth (area of responsibility). 

While such extention of the request might make sense for request forwarders that relay the retrieve request toward the chunk address since it has the potential to generate alternative routes to access the chunk's storer nodes. 

However, the method is dangerous for nodes that should already hold the chunk for the following reason. 

If the chunk does not exist or not synced properly, the requests time out and if the fetcher's lifetime allows, requests get 'escalated' to nodes farther and farther from where they are supposed to be, i.e., it spreads in a gossip-like fashion. 
Beyond the obvious issue of creating massive amounts of useless retrieve requests and spread the chunk to be cached on nodes that it should not be with deliveries clogging the network.

Moreover, in some cluster sizes, the request eventually leads to the uploader node and the request succeeds. But in this case combined network tests for syncing and retrieval, it shields problems with syncing, which did happen according to @janos 
The fix involves adding an additional condition to `RequestPeer` that prevents the node to request a chunk in its area of responsibility from peers outside it. Such a fix is already implemented in @nonsense's PR here https://github.com/ethersphere/go-ethereum/pull/1316/files#diff-fce2723a1afd65f8ba1491345600a102R262

**Comment by acud** [comment]
isn't this fixed as part of your efforts @nonsense?
