### ISSUE TITLE
Support for uploading 100gb files

### ISSUE THREAD

**Issue by jmozah** [ethersphere/swarm#1356]
This is an umbrella issue for fixing all the issues related to large file uploads.

**Comment by jmozah** [comment]
Issue that i see for now
- Go routine leaks 
- Chunk corruption when uploading file greater than 8.5gb in size
- DBCapacity lower than uploaded file size issue

**Comment by nonsense** [comment]
@jmozah we are going to have a Swarm release next week. I would be very happy and would really appreciate if you have some time to walk me through your changes or add a bit more elaborate explanation/description on your PR if you think it is better than what we currently have on `master`!
