### ISSUE TITLE
Add test for `from-1` bug

### ISSUE THREAD

**Issue by nonsense** [ethersphere/swarm#1361]
With the new `LocalStore` the underlying system serving `SetNextBatch` changed from:

(see previous version of Swarm, for example git tag `v1.8.24`
```
		err := s.store.Iterator(from, to, s.po, func(key storage.Address, idx uint64) bool {
```

to:

(see `swarm-rather-stable`)
```
	descriptors, stop := s.netStore.SubscribePull(context.Background(), s.po, from, to)
```

The behavior of `store.Iterator` and `SubscribePull` however are different, and the intervals they cover with respect to `from` and `to` are not identical. From the `SubscribePull` godoc we read that the interval is open on the `from` side, unlike with `s.store.Iterator`.

---

This task is about adding a test for `SetNextBatch` with respect to subsequent intervals, so that we make sure it is using its underlying subsystems correctly.

The actual bugfix is already part of `swarm-rather-stable` at:

```
	//TODO: maybe add unit test for intervals usage in netstore/localstore together with SwarmSyncerServer?
	if from > 0 {
		from--
	}

	descriptors, stop := s.netStore.SubscribePull(context.Background(), s.po, from, to)
```

Prior to the `from--` statement, subsequent calls to `SetNextBatch` were missing 1 chunk in between intervals.

**Comment by gluk256** [comment]
@nonsense: what happens if from = 0 ?
chunk at 0 is unreachable / invalid ?

**Comment by nonsense** [comment]
Addressed at https://github.com/ethereum/go-ethereum/pull/19599/files
