### ISSUE TITLE
investigate kademlia connectivity and suggest peer functionality

### ISSUE THREAD

**Issue by nonsense** [ethersphere/swarm#1436]
Related to: https://github.com/ethersphere/swarm/issues/1396

The way we build our Kademlia table right now is not very well defined - for example in a given deployment we might have a lot peers in bin 0, or very few, for example:

7 connections in bin 0 (network of 20 nodes)
```
➜  ~ kubectl -n tony exec -ti swarm-private-9 -- /geth --exec="console.log(bzz.hive)" attach /root/.ethereum/bzzd.ipc
Defaulting container name to swarm.
Use 'kubectl describe pod/swarm-private-9 -n tony' to see all of the containers in this pod.
INFO [06-08|20:08:15.464] Bumping default cache on mainnet         provided=1024 updated=4096

=========================================================================
commit hash: 53457a1fd
Sat Jun  8 20:08:15 UTC 2019 KΛÐΞMLIΛ hive: queen's address: efb323de97afdaf1d59cff99f239552d0b86864afac696a1d8a765bdbe0850ec
population: 15 (20), NeighbourhoodSize: 2, MinBinSize: 2, MaxBinSize: 4
000  7 2d5f 6006 7408 7090          | 12 2d5f (0) 1d0e (0) 117f (0) 0f53 (0)
001  6 8185 84a6 982f a0e9          |  6 8185 (0) 84a6 (0) 982f (0) a0e9 (0)
============ DEPTH: 2 ==========================================
002  0                              |  0
003  1 f4a2                         |  1 f4a2 (0)
004  0                              |  0
005  0                              |  0
006  0                              |  0
007  1 eefd                         |  1 eefd (0)
008  0                              |  0
009  0                              |  0
010  0                              |  0
011  0                              |  0
012  0                              |  0
013  0                              |  0
014  0                              |  0
015  0                              |  0
=========================================================================
```

vs

2 connections in bin 0 (same network of 20 nodes)
```
➜  ~ kubectl -n tony exec -ti swarm-private-10 -- /geth --exec="console.log(bzz.hive)" attach /root/.ethereum/bzzd.ipc
Defaulting container name to swarm.
Use 'kubectl describe pod/swarm-private-10 -n tony' to see all of the containers in this pod.
INFO [06-08|20:09:15.434] Bumping default cache on mainnet         provided=1024 updated=4096

=========================================================================
commit hash: 53457a1fd
Sat Jun  8 20:09:15 UTC 2019 KΛÐΞMLIΛ hive: queen's address: eefdfe73b0f47187312c1fdcea5377b7668d6f6cbee33c4e4c344475a53e7edd
population: 8 (20), NeighbourhoodSize: 2, MinBinSize: 2, MaxBinSize: 4
000  2 2d5f 5ab8                    | 12 2d5f (0) 1d0e (0) 117f (0) 0f53 (0)
001  4 8185 a0e9 b373 b8ec          |  6 b373 (0) b8ec (0) a0e9 (0) 982f (0)
============ DEPTH: 2 ==========================================
002  0                              |  0
003  1 f4a2                         |  1 f4a2 (0)
004  0                              |  0
005  0                              |  0
006  0                              |  0
007  1 efb3                         |  1 efb3 (0)
008  0                              |  0
009  0                              |  0
010  0                              |  0
011  0                              |  0
012  0                              |  0
013  0                              |  0
014  0                              |  0
015  0                              |  0
=========================================================================
undefined
```

The number of connections are supposed to be within the range `MinBinSize: 2, MaxBinSize: 4`, but this doesn't work and we've known that for a while.

This is problematic, because half of the chunks for a given upload would end up in bin 0, so once we trigger a retrieve request, we will be making requests for 1/2 of all chunks to our peers in bin 0. If we want to support larger files in Swarm (100MB ... 100GB), as defined in our active Epics, this won't be feasible with only a small number of peers.

-----

At the same time our current implementation establishes syncing with all peers, meaning that if we have a lot of peers in bin 0, we would be syncing 1/2 of our chunks with all of them - which seems to be a lot of waste... we should make an effort to sync content in Swarm without spamming the whole network.

-----

Because of the issues above, I suggest we review our Kademlia functionality and current implementation and discuss and maybe implement something along the lines of:
1. Make sure we have a lot of peers in bin 0, as they are responsible for retrieve requests for half of the chunks on any given download, and we should run fetch requests to all of them. For example, if we are supposed to fetch a 4GB file in a timely fashion, then 1/2 * 4GB == 2GB chunks will be retrieved from bin 0 peers, then we need at least 10 peers for bin 0, in order to deliver adequate user experience.
2. Make sure we don't establish syncing with all our peers in a given bin (and bin 0), but only to a small number K, where K is 3-4 (this exact value is TBD).

In general I think if we have N peers in bin 0, then N should be around 1/2 of all our peers, and probably 1/2 of the `maxpeers` setting. Peers in bins 1..16 should probably be 1/2^(bin_number+1) * maxpeers.

cc @acud @zelig @homotopycolimit

**Comment by nonsense** [comment]
BTW in our current implementation, even though we generally have >1 peers in bin 0, I still see that we retrieve chunks only from the first peer. For example, for a 100MB download (and 16KB chunk size), 48MB of chunks (3049 * 16kb) were delivered by 1 peer, when the downloader node actually had 2 peers in its 0 bin:

<img width="1607" alt="Screenshot 2019-06-08 at 22 29 46" src="https://user-images.githubusercontent.com/50459/59152021-f5526780-8a3c-11e9-935d-e83c8067c677.png">

```
➜  ~ kubectl -n tony exec -ti swarm-private-10 -- /geth --exec="console.log(bzz.hive)" attach /root/.ethereum/bzzd.ipc
Defaulting container name to swarm.
Use 'kubectl describe pod/swarm-private-10 -n tony' to see all of the containers in this pod.
INFO [06-08|20:09:15.434] Bumping default cache on mainnet         provided=1024 updated=4096

=========================================================================
commit hash: 53457a1fd
Sat Jun  8 20:09:15 UTC 2019 KΛÐΞMLIΛ hive: queen's address: eefdfe73b0f47187312c1fdcea5377b7668d6f6cbee33c4e4c344475a53e7edd
population: 8 (20), NeighbourhoodSize: 2, MinBinSize: 2, MaxBinSize: 4
000  2 2d5f 5ab8                    | 12 2d5f (0) 1d0e (0) 117f (0) 0f53 (0)
001  4 8185 a0e9 b373 b8ec          |  6 b373 (0) b8ec (0) a0e9 (0) 982f (0)
============ DEPTH: 2 ==========================================
002  0                              |  0
003  1 f4a2                         |  1 f4a2 (0)
004  0                              |  0
005  0                              |  0
006  0                              |  0
007  1 efb3                         |  1 efb3 (0)
008  0                              |  0
009  0                              |  0
010  0                              |  0
011  0                              |  0
012  0                              |  0
013  0                              |  0
014  0                              |  0
015  0                              |  0
=========================================================================
```

The issues described above, together with our only download API being the HTTP GET one are some of the main reasons why Swarm downloads are so slow.

**Comment by cobordism** [comment]
>  I still see that we retrieve chunks only from the first peer. 

that is not even how it should work.
Until we have better connection metrics (see [here](https://swarmresear.ch/t/rating-your-peers-connection-metrics/34/2) ) we should be requesting each chunk from the _closest_ node that we are connected to.

If a chunk falls into our bin 0, it can be that it falls within bin 1 for our first peer in this bin, bin 3 for another and bin 8 for a third. ... we should request from the closest.


As for your suggestion of having a large bin 0 but only syncing with a few of them: this is a good strategy for nodes that wish to consume data but not for nodes that are only meant to be run as 'servers' and not for local consumption.
I have started collecting some thoughts on this subject on swarmresear.ch "[light connections between full nodes](https://swarmresear.ch/t/light-client-connection-strategy/17/3).

**Comment by nonsense** [comment]
@homotopycolimit see https://github.com/ethersphere/swarm/issues/1533 about the current state of swarm with respect to how chunks are retrieved from bin 0 - TLDR if we have 10 peers in bin 0, and we need to get 1/2 of the chunks from bin 0, Kademlia has no state about our usage of our peers, so it keeps on suggesting the first peer... even if we assume that by their PO, all peers in bin 0, have the same PO to the necessary chunk, Kademlia should have feedback about how much we utilise our peers and select the `best` peer - for example one that is under utilised by us.

**Comment by cobordism** [comment]
> even if we assume that by their PO, all peers in bin 0, have the same PO to the necessary chunk

that in itself is very unlikely ... and no two peers will have the same distance to the chunk ;).

> Kademlia should have feedback about how much we utilise our peers and select the best peer

indeed this ties in to a much greater need to rate peers and persist such information. We will need to build a framework for rating and evaluating peers and connections and then we must decide how we want to rate them. (on [rating peers](https://swarmresear.ch/t/rating-your-peers-connection-metrics/34).)

**Comment by nonsense** [comment]
`that in itself is very unlikely` why would it be unlikely - take any chunk that falls in our bin 0, where we have 4-5 peers... why would the chunk necessarily have different PO with respect to those 4-5 chunks... I am pretty sure for some of them it has the same PO, for example 2 or 3 or whatever.

We currently use PO and not XOR, so two peers can have the same distance to a chunk.

**Comment by nonsense** [comment]
> indeed this ties in to a much greater need to rate peers and persist such information. We will need to build a framework for rating and evaluating peers and connections and then we must decide how we want to rate them. (on [rating peers](https://swarmresear.ch/t/rating-your-peers-connection-metrics/34).)

Yes, makes total sense and Kademlia should be aware of it. It should basically be able to compare peers and ultimately decide between 2 peers. Initially this can be as simple as `select the peer that has fewer in-flight requests from our node right now`, and can be as complex as including rating, SWAP balances, etc.

I suggest we start simple and have that function, the discussion on what this function should be is much deeper I think.

**Comment by cobordism** [comment]
> where we have 4-5 peers

I thought it was 10 " if we have 10 peers in bin 0" 

> I am pretty sure for some of them it has the same PO, for example 2 or 3 or whatever.

I thought you meant all 10 peers "all peers in bin 0, have the same PO to the necessary chunk" 

:)

**Comment by nonsense** [comment]
@homotopycolimit yeah, sorry for not being clear enough... the point is if you have `a few` peers in a given bin that have the same PO to the necessary chunk, it seems like Kademlia is always suggesting the first one, meaning we are not at all using our other peers right now.

**Comment by kortatu** [comment]
> @homotopycolimit yeah, sorry for not being clear enough... the point is if you have `a few` peers in a given bin that have the same PO to the necessary chunk, it seems like Kademlia is always suggesting the first one, meaning we are not at all using our other peers right now.

That has been changed in #1774 now, when several peers have the same distance to a certain address, the least used will be selected. In that PR the framework for doing that has been implemented but it is only used in PSS forwarding. It would be great to use `kademlialoadbalancer.go` also for retrieving chunks (maybe that should be part of the PR, but I didn't have the knowledge to modify that part).

**Comment by nolash** [comment]
Bin cardinalities relative to distance from depth is being worked on here https://github.com/ethersphere/swarm/pull/1833

There is also an experimental version https://github.com/ethersphere/swarm/pull/1869 described in SWIP https://github.com/ethersphere/SWIPs/pull/32
