### ISSUE TITLE
Define and implement thresholds

### ISSUE THREAD

**Issue by holisticode** [ethersphere/swarm#1440]
Currently, the accounting module only operates through the `Add(amount int64, peer *protocols.Peer) function - it does just adds positive (credit) or negative (debit) amounts.

We need to implement thresholds so that it is possible to take action based on threshold crossing.

Refer to Figure 2 in chapter 2.1 of the SW3 paper documentation: 
https://www.overleaf.com/project/59c298da5b3a6e3b7ec80d56

The following thresholds need to be implemented:
* Payment trigger 
* Peer-ignore (in [SW3 paper defined as “disconnect threshold”)

**Comment by vojtechsimetka** [comment]
@mortelli will start working on this one

**Comment by mortelli** [comment]
Pending due to open research questions.
