### ISSUE TITLE
Allow parametrization of thresholds

### ISSUE THREAD

**Issue by holisticode** [ethersphere/swarm#1441]
Issue #1440 is about implementing thresholds into accounting.

This issue is about making these thresholds parametrizable, so that it is possible to provide different values to the code, allowing for experimentation with different thresholds.

Questions to be answered (may need coordination/sync with research track):
* What happens if nodes have different thresholds in production? 
* Is it ok for nodes to have their own thresholds?
* Should this parametrization only be allowed for testing?
* Should there be some kind of protocol to set these thresholds network-wide?

This issue is about allowing experimentation; thus the questions above are meant to obtain clarity, but do not need to find implementation as part of this issue.

The most obvious solution for parametrization is to provide values via command line parameter. Other options may be proposed as part of this issue.

**Comment by Eknir** [comment]
This topic was discussed during the last research call (Friday 30th of August). I posted a brief summary [here](https://swarmresear.ch/t/adjusting-payment-thresholds/42/2).

Making parametrization via the command line/config is a good idea, but if these are not provided, the value must be read from an oracle which provides the same thresholds for the whole Swarm network.
 
Nodes who will use this parametrization during a live network are at risk of being disconnected by not sending their payments in time.
