### ISSUE TITLE
Generate go-bindings for the incentives smart contracts

### ISSUE THREAD

**Issue by holisticode** [ethersphere/swarm#1442]
The Swarm incentives layer runs with a set of smart contracts. These smart contracts are implemented and maintained in the https://github.com/ethersphere/swap-swear-and-swindle repo.

The bridge to run these contracts is through generating go-bindings from these contracts.

This issue is about generating these go-bindings and integrate them into the go codebase.
Familiarize with the tools needed, standardize the process if smart contracts are being updated, propose tooling and development process improvements to create a smooth workflow for generating and integrating go-bindings

**Comment by ralph-pichler** [comment]
Integrated in #1683
