### ISSUE TITLE
Integrate smart contracts go-bindings into the Swarm code

### ISSUE THREAD

**Issue by holisticode** [ethersphere/swarm#1443]
https://github.com/ethersphere/swarm/issues/1442 is about the generation of go-bindings and the exploration and potential implementation of automating the process.

This issue is about connecting the go-bindings with the actual Swarm code which is meant to use them.

Where are the "entry points"? Where does the go code need to interact with the go-bindings? Where the interfaces? When do we need to call smart contracts?

**Comment by ralph-pichler** [comment]
Integrated in #1683
