### ISSUE TITLE
Complete swap imbalance settlement

### ISSUE THREAD

**Issue by holisticode** [ethersphere/swarm#1446]
https://github.com/ethersphere/swarm/issues/1444 is about implementing the swap cheques exchange protocol.

This issue is about making sure that automatic settlement of imbalances accrued through Swap exchanges works.

It needs to integrate the cheque exchange with the Swap smart contracts. Write tests that test automatic settlement.

**Comment by ralph-pichler** [comment]
What is still missing here?

**Comment by holisticode** [comment]
I think this can be closed
