### ISSUE TITLE
Offical download link for windows is 0.3.16 but shown 0.4.0 and ens-api for win10 fault

### ISSUE THREAD

**Issue by ljq8896** [ethersphere/swarm#1455]
#### System information

Swarm version: `swarm version`0.4.1
OS & Version: Windows 10 1903
Commit hash : (if `develop`)

#### Expected behaviour
1.Download normally from Offical site.
2.use `--ens-api ipc://./pipe/geth.ipc` for windows users.

#### Actual behaviour
1.Offical site binary download link for windows [x86](https://ethswarm.blob.core.windows.net/builds/swarm-windows-386-0.4.0-c3b317a4.zip) and [x64](https://ethswarm.blob.core.windows.net/builds/swarm-windows-amd64-0.4.0-c3b317a4.zip) shown 0.4.0 is acturlly **swarm version 0.3.16-unstable-184af72e** and can not connect to 0.4.0 networks. Users may complie source to get client for windows.

2.Windows Users (Maybe windows 10) can't using the docs [here](https://swarm-guide.readthedocs.io/en/latest/gettingstarted.html#how-do-i-enable-ens-name-resolution) 
`$ swarm --ens-api %HOMEPATH%\AppData\Roaming\Ethereum\geth.ipc \
--bzzaccount $BZZKEY `
to access geth ipc. We may use
 `$ swarm --ens-api ipc:\\.\pipe\geth.ipc \
--bzzaccount $BZZKEY`  
but got 
`Fatal: Error starting protocol stack: error connecting to ENS API ipc://./pipe/geth.ipc: no known transport for URL scheme "ipc"` .

#### Backtrace

````
[backtrace]
````

**Comment by nonsense** [comment]
@skylenet let's have a look at this tomorrow.

**Comment by skylenet** [comment]
Thanks for reporting this bug @ljq8896 ! 

Indeed the `v0.4.0` release for Windows is wrong. I've removed it from the download page for now.

Please try the new `v0.4.1` release which has the correct version of swarm :)

**Comment by skylenet** [comment]
@ljq8896 regarding using ENS: On windows, geth uses [Named Pipes](https://docs.microsoft.com/en-us/windows/desktop/ipc/named-pipes) for IPC. 

This means that when you start geth (with default flags), you'll see something like: 

```
INFO [06-17|13:32:22.491] IPC endpoint opened                      url=\\\\.\\pipe\\geth.ipc
```
(It outputs too many backslashes, it should actually be `\\.\pipe\geth.ipc`)

This means that on the swarm side, you can connect to that named pipe using the following:

```
swarm.exe --bzzaccount $BZZKEY --ens-api \\.\pipe\geth.ipc
```

More info on rpc.Dial(...): https://godoc.org/github.com/ethereum/go-ethereum/rpc#Dial 

Hope that helps!

**Comment by nonsense** [comment]
Thank you, @skylenet . @ljq8896 I think this solves it, please re-open if something is not clear, or you have other concerns! :)
