### ISSUE TITLE
Define useful information for node operators

### ISSUE THREAD

**Issue by holisticode** [ethersphere/swarm#1474]
There are couple of issues we have defined which allow to query information about the status of accounting. This allows some visibility for the operator of a node about how her node is performing from an economics point of view.

However, the information to be visualized so far hasn't been defined out of a broader discussion, but just from a point of view of one person.

It would be good to formalize what needs to be there are so that appropriate and useful endpoints and visualization/display tools are created.

Related issues:
https://github.com/ethersphere/swarm/issues/1473
https://github.com/ethersphere/swarm/issues/1447
https://github.com/ethersphere/swarm/issues/1445

**Comment by vojtechsimetka** [comment]
I'll take this

**Comment by holisticode** [comment]
After devcon and the workshop experiences this should be clear if we need more than we have today. @vojtechsimetka
