### ISSUE TITLE
Investigate ReadTheDocs deployment

### ISSUE THREAD

**Issue by holisticode** [ethersphere/swarm#1490]
We are moving the documentation from the swarm-guide into the `/docs` folder.

The swarm-guide is hosted on `readthedocs.io/`.

We need to make sure that if we move the repo that the automatic deployment will still work. 

This issue is not about moving the repo, but about providing the information about automatic deployments for `master` and also for arbitrary branches in order to publicly preview changes.

If the above results in too much complexity or problems, this task may very well suggest that a move is not recommended.

**Comment by acud** [comment]
@zelig can you please give access to the rtd account to @skylenet and @nonsense?

**Comment by skylenet** [comment]
Login to readthedocs.org > Select "swarm-guide" project > Admin > Maintainers:
Or the direct link: https://readthedocs.org/dashboard/swarm-guide/users/

**Comment by skylenet** [comment]
Done via https://github.com/ethersphere/swarm/pull/1513
