### ISSUE TITLE
calling t.Fatal within a simulation does not break the simulation

### ISSUE THREAD

**Issue by acud** [ethersphere/swarm#1508]
if we use `t.Fatal` within a simulation, the simulation execution does not immediately break for some reason.
We should either pass `sim` instead of `testing.T` and fail the simulation. When calling `testing.T` the simulation just times out and we don't get any feedback on why it fails

**Comment by nonsense** [comment]
is this why you changed all the `errors` to `panics`?

**Comment by acud** [comment]
@nonsense in the scope of the pull sync pr yes. it is just impossible to get any indication for an error within a test that fails explicitly with `t.Fatal`. this is borderline ridiculous. it just times out and does not give any further information.

**Comment by acud** [comment]
i started to look into this by inspecting how `t.Fatal` works. it seems that there's a certain shutdown sequence for the test that waits for all goroutines to finish before actually terminating the simulation. we should definitely look into this as we're probably losing a lot of debugging information over this problem (all of those tests that have been "flaking" and "timing out" on travis might actually been giving out valuable information we have been just ignoring because of this "feature").

**Comment by acud** [comment]
cc @skylenet. this might a low hanging fruit

**Comment by acud** [comment]
actually i correct myself. it does give out the failure reason, but we have such long default timeouts on simulations that i never even waited for the output. anyway we should look into this

**Comment by nonsense** [comment]
@acud `Simulation` is not coupled with the `testing.T` framework/library.

If you want to return or stop a simulation, you just return an `error`, and then `simulation.Close()` is called.

You also have to display the result of the `Simulation.Result` outside of the `simulation.Run`, when in tests with `t.Fatal`.
