### ISSUE TITLE
Need proper URL handlers for browser

### ISSUE THREAD

**Issue by cobordism** [ethersphere/swarm#151]
We need an easy way to teach browser about bzz:// bzz-raw:// bzz-list:// bzz-hash:// and bzz-immutable:// URLs.

There is one URL handler in the repository since forever but it does not work correctly.

This is also important because at the moment we use relative links "bzz:/theswarm.eth/a/b/c" in our HTML when we should be using absolute links "bzz://theswarm.eth"

One of these works on the gateway, the other works with proper URL handling... what should the correct solution be?

**Comment by cobordism** [comment]
perhaps a little brower plugin is in order too? To select the bzz provider, be it localhost:8500, swarm-gateways.net or infura-swarm-gateay (*hope*)

**Comment by gbalint** [comment]
> There is one URL handler in the repository since forever but it does not work correctly.

Can you elaborate what is the problem with it?

**Comment by gbalint** [comment]
@homotopycolimit I love the browser plugin idea, moved it into a separate issue: https://github.com/ethersphere/go-ethereum/issues/152

**Comment by cobordism** [comment]
> There is one URL handler in the repository since forever but it does not work correctly.

Can you elaborate what is the problem with it?

All I can say is that I could not get it to work on any of my browsers. https://github.com/ethereum/swarm-dapps/blob/master/examples/bzzhandler.html Maybe I was just being dumb, but I'm allowed to be dumb. We have to make it easy.

Can you get that file to work for you?

**Comment by gbalint** [comment]
Do you mean that e.g. the bzzr url doesn't work? It works for me:
```
curl http://0.0.0.0:8502/bzzr:/b6ce5b9b5d9b125bef01395f4bd9bd3789ea514cb82b8f98222fde8f7ea3e203/
{"entries":[{"hash":"94f78a45c7897957809544aa6d68aa7ad35df695713895953b885aca274bd955","contentType":"text/plain","mode":420,"size":9,"mod_time":"2017-12-13T12:52:57.6734522Z"}]}%
```

**Comment by cobordism** [comment]
I don't understand your comment. I want my browser to load bzz:// URLs

**Comment by gbalint** [comment]
I thought you mean the special handling of bzzh, bzzi, etc urls
How could we do that if browsers do not support the bzz protocol?
Isn't the browser plugin issue is about this? https://github.com/ethersphere/go-ethereum/issues/152

**Comment by cobordism** [comment]
I understood that the file https://github.com/ethereum/swarm-dapps/blob/master/examples/bzzhandler.html should be enough to get your browser to recognize bzz bzzi and bzzr URLs. I can't get it to work - i.e. I cannot use the file to register URL handlers in my browser. 
That's all.
We need an easy way to register http://localhost:8500 has the bzz:// protocol handler (and bzzi, bzz-hash and all the rest)

**Comment by cobordism** [comment]
we want to avoid URLs like this: https://github.com/ethersphere/swarm-home/blob/master/index.html#L321

**Comment by cobordism** [comment]
Update:
We cannot register bzz:// URL handlers. 
See here:
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/registerProtocolHandler#Permitted_schemes
and
https://developers.google.com/web/updates/2011/06/Registering-a-custom-protocol-handler

Thus I am closing this issue in favour of:
https://github.com/ethersphere/go-ethereum/issues/152
