### ISSUE TITLE
Define Incentives MVP deployment

### ISSUE THREAD

**Issue by holisticode** [ethersphere/swarm#1511]
How is Swap being deployed onto the current Swarm's existing networks?

Should Swap be kept on a separate branch?
Should it be merged onto master?

If we merge to master, do we enable Swap per default?
If not, people may still switch it on if it is available, which means potentially operational problems as nodes may get disconnected, cheques requested, etc.

**Comment by mortelli** [comment]
The first implementation of SWAP is being deployed to the `master` branch. 

Only the Network ID `5` is allowed to run the protocol.

For more information, see #1550.
