### ISSUE TITLE
extend http downloader with asynchronous lookahead 

### ISSUE THREAD

**Issue by zelig** [ethersphere/swarm#1524]
The  http reader is suboptimal since it downloads in syncronous batches translating to range queries for the `LazyChunkReader`. Previously we optimised for buffersize in this reader, however, this still leaves longer latencies since each batch is blocking until the slowest chunk arrives. 

A low hanging fruit to improve is to extend this reader with an asyncronous lookahead that brings concurrent network retrieval across batches and thereby significantly reduce download latencies.

**Comment by FantasticoFox** [comment]
This should not be in here. The specifications need to go into a SWIP the timeline is a result of the issues which are assigned to the user-story. In This case it's the 200 MB / 500 MB iterative file-size support increase and the improvement on stability.
