### ISSUE TITLE
GET request /favicon.ico should return our favicon 

### ISSUE THREAD

**Issue by gbalint** [ethersphere/swarm#153]
bzz:/22481deec05d53e909e4f3933842686113927c67ab2a22c8ad5614e4e3dc505c/favicon.ico

**Comment by cobordism** [comment]
I'd prefer a local response instead of a bzz request. It should work on private networks too (or even on offline hosts.)

**Comment by cooganb** [comment]
@homotopycolimit So that means it's included in the local installation?

**Comment by cobordism** [comment]
yes. local. it's only a tiny favicon after all

**Comment by homotopycolimit** [comment]
yes. local. it's only a tiny favicon after all

**Comment by cooganb** [comment]
@homotopycolimit okay, i'd be happy to open up a branch

**Comment by cobordism** [comment]
sure. go ahead.

**Comment by cooganb** [comment]
@homotopycolimit this is a solution I found on SO after much hunting. let me know what you think.

**Comment by cooganb** [comment]
@gbalint this has been resolved and merged into `ethereum/go-ethereum`:

https://github.com/ethereum/go-ethereum/pull/15958#event-1475963495

**Comment by cobordism** [comment]
http://localhost:8500/favicon.ico gives me an HTTP error 400 page, no favicon. Am I doing something wrong?
(built swarm using swarm-network-rewrite branch on ethersphere on June 17 2018, commit 86c5515baa60f149211edb9b3f618f8ad735d705)

**Comment by cooganb** [comment]
@homotopycolimit it's been a minute, but i believe we discussed using data blobs rather than putting a file locally. so, you're not getting an error, the .ico is a data blob rather than a file.

**Comment by cobordism** [comment]
All that interests me is what an HTTP request to /favicon.ico returns.
File vs datablob means very little to me.

**Comment by cobordism** [comment]
so on a running swarm node, we should get the icon at http://localhost:8500/favicon.ico

**Comment by cooganb** [comment]
File vs. datablob does matter, because a file is in a separate location
whereas the datablob is served up within the template held in the
go-template.
