### ISSUE TITLE
Kademlia peers are not utilised adequately during retrieval

### ISSUE THREAD

**Issue by nonsense** [ethersphere/swarm#1533]
I started a 30 node network, uploaded 100MB to node 0, and tried to download the content from node 24.

It appears that 1/2 of all chunks were found on node 24, because it is in the 0 bin of node 0.
The other 1/2 were all delivered again through node 0, and a small amount from a different node.

<img width="1315" alt="Screenshot 2019-07-03 at 14 51 05" src="https://user-images.githubusercontent.com/50459/60593116-610cc380-9da2-11e9-848a-f2bb1735aa6d.png">

```
➜  ~ kubectl -n tony exec -ti swarm-private-0 -- /geth --exec="console.log(bzz.hive)" attach /root/.ethereum/bzzd.ipc
Defaulting container name to swarm.
Use 'kubectl describe pod/swarm-private-0 -n tony' to see all of the containers in this pod.
INFO [07-03|12:52:35.782] Bumping default cache on mainnet         provided=1024 updated=4096

=========================================================================
commit hash: de1c601d5
Wed Jul  3 12:52:36 UTC 2019 KΛÐΞMLIΛ hive: queen's address: c3d437a5f2358e60da01e92108139a6bfb056aae74dfda7f0bac595a953fc0ba
population: 23 (30), NeighbourhoodSize: 2, MinBinSize: 2, MaxBinSize: 4
000 16 2f7d 0f69 04af 1f0f          | 17 2f7d (0) 0f69 (0) 04af (0) 1f0f (0)
001  2 889a b560                    |  5 90d7 (0) 8757 (0) 889a (0) b87b (0)
002  2 fe02 ef84                    |  5 faef (0) ff9f (0) fe02 (0) e3f5 (0)
============ DEPTH: 3 ==========================================
003  0                              |  0
004  0                              |  0
005  2 c62c c7e3                    |  2 c62c (0) c7e3 (0)
006  0                              |  0
007  0                              |  0
008  1 c37a                         |  1 c37a (0)
009  0                              |  0
010  0                              |  0
011  0                              |  0
012  0                              |  0
013  0                              |  0
014  0                              |  0
015  0                              |  0
=========================================================================
undefined
➜  ~
```

Idea of where this problem comes from: Looks like our suggest peer functionality might not work as expected.

**Comment by nonsense** [comment]
Another example with a download from node 27.

<img width="1312" alt="Screenshot 2019-07-03 at 15 00 08" src="https://user-images.githubusercontent.com/50459/60593568-59015380-9da3-11e9-9080-c473c2cb3e44.png">

Again it is visible we don't utilise adequately our peers.

<img width="1260" alt="Screenshot 2019-07-03 at 15 01 13" src="https://user-images.githubusercontent.com/50459/60593677-92d25a00-9da3-11e9-8f70-70f4ef85256c.png">

**Comment by nonsense** [comment]
In both examples, it is clear why we have 0 requests from our NN - chunks that fall within NN are synced across all nodes in the NN, so no point asking our NN peers about chunks - we already have them.

However in the first example, I find it interesting that all chunks that we don't have (namely half of them), are all coming from 0 bin. I would have expected for some to come from (0;depth) range.

**Comment by cobordism** [comment]
> I find it interesting that all chunks that we don't have (namely half of them), are all coming from 0 bin. I would have expected for some to come from (0;depth) range.

For any file, you expect half of all chunks to come from bin 0. These are the chunks to which your bin 0 peers are closer than you are.
During syncing, your bin 0 peer gave you the other half of the chunks - those to which you are closer than it is. It is this half of chunks that you would have gotten from the (0;depth) range if you had not been a sync recipient.

**Comment by nonsense** [comment]
> > I find it interesting that all chunks that we don't have (namely half of them), are all coming from 0 bin. I would have expected for some to come from (0;depth) range.
> 
> For any file, you expect half of all chunks to come from bin 0. These are the chunks to which your bin 0 peers are closer than you are.
> During syncing, your bin 0 peer gave you the other half of the chunks - those to which you are closer than it is. It is this half of chunks that you would have gotten from the (0;depth) range if you had not been a sync recipient.

you're totally right, this makes perfect sense, apparently a brain fart.

still ultimately this ticket is about the fact that 11k came from the first peer, and only 400 came from the second peer. we should have more peers in bin 0, and we should utilise those peers a bit better.

**Comment by nolash** [comment]
Covered by https://github.com/ethersphere/swarm/issues/1436
