### ISSUE TITLE
GET request for robots.txt should return a valid robots.txt

### ISSUE THREAD

**Issue by gbalint** [ethersphere/swarm#154]
What should be the contents?

**Comment by cobordism** [comment]
default - don't index anything 
certainly don't crawl anything... otherwise (in future) you could incur costs due to crawling.

**Comment by cobordism** [comment]
```
User-agent: *
Disallow: /
```

**Comment by gbalint** [comment]
Do you mean robots.txt on the gateway, like http://swarm-gateways.net/robots.txt?

**Comment by cobordism** [comment]
... or localhost:8500/robots.txt ... so that whenever localhost:8500 is served through a transparent proxy (gateway) then /robots.txt exists and returns a valid response to not crawl anything

**Comment by gbalint** [comment]
Fixed in https://github.com/ethersphere/go-ethereum/pull/402
