### ISSUE TITLE
GET request for '/' should return HTTP 200

### ISSUE THREAD

**Issue by gbalint** [ethersphere/swarm#155]
GET request for just '/' (as opposed to `bzz:/` etc.) should return a HTTP 200 and some minimal status info, not an error about an invalid protocol

https://github.com/ethereum/go-ethereum/blob/master/swarm/api/http/server.go#L555

**Comment by cobordism** [comment]
Ideally this page would also explain how to add a bzz:// URL handler to your browser (if there isn't one yet)

**Comment by gbalint** [comment]
Note: you can not add a bzz:// handler to your browser, see https://github.com/ethersphere/go-ethereum/issues/151#issuecomment-351439175

**Comment by cooganb** [comment]
@gbalint just FYI, i'm poking around here to see if i can help on this issue.

**Comment by cooganb** [comment]
@gbalint what kind of status info do you think would be good? and would that be delivered as an error message? 

just for reference, here's what i'm getting when i ping `localhost:8500/` :

![screen shot 2017-12-24 at 12 02 23 pm](https://user-images.githubusercontent.com/8144425/34328059-9cfcc9dc-e8a2-11e7-82ad-24b6ce3fb82e.png)

**Comment by cobordism** [comment]
Here is an idea. 
The page starts with

Welcome to Ethereum Swarm.

and then have an input form with title "enter a name or a hash" and default value theswarm.eth and when the button is clicked, the user gets redirected to bzz://theswarm.eth


Than, in future, we can extend this landing page with links to the stats page, admin page etc. etc.

**Comment by holisticode** [comment]
I agree it should be a landing page for swarm. And can serve as 'status'
until a more detailed definition of what 'status' should return.

Should maybe check for accept header, also json requests should be accepted
(returning just 200 OK).

**Comment by cooganb** [comment]
Great, so we're thinking about making it a landing page with an input form that can accept hashes or ENS domains, knit together the correct address and send the user on their way?

Any other links to be provided on the landing page?

@holisticode how (if at all) does the page currently handle json requests? And what's the protocol now for accept header?

Last, are there any web development guidelines for swarm that could direct what the landing page looks like?


Thanks in advance for any help!

**Comment by cobordism** [comment]
I feel like having a minimally functional landing page is a good first step.
Once it is up and running, we can talk about tweaking it and adding features.

The current landing-error-page I consider to be (almost) a bug. 

>Great, so we're thinking about making it a landing page with an input form that can accept hashes or  ENS domains, knit together the correct address and send the user on their way?

that's my feeling for a good minimal working example, yes.

> Any other links to be provided on the landing page? 

Perhaps just one to https://swarm-guide.readthedocs.io/en/latest/ ?

**Comment by cooganb** [comment]
@homotopycolimit okay, sounds good. 

i'd like to get some work done on this. i want to make sure my git etiquette is correct: i'll create a new branch from the ethereum-go master and work on a new method for the `HandleGetFile` function where entering in an "empty" address, like `/` or `bzz://` would result in the user getting a very basic landing page which would have a header, an input form & button for hashes / ENS and link to swarm docs?

**Comment by cobordism** [comment]
> an "empty" address, like / or bzz://

I think this issue is specifically only for `/` but apart from that you are correct.
You create a new branch on a forked master and then you can make a PR to https://github.com/ethersphere/go-ethereum/ referencing this issue. You make that PR right away - before you have actually fixed the issue - this let's us know that you intend to work on it.

@gbalint What's our policy for moving from ethersphere/go-ethereum to ethereum/go-ethereum repo? Shall we say that when we are all happy here at ethersphere, cooganb shall create a PR to the ethereum/go-ethereum repo and we approve and merge there? I forgot what (if anything) we had decided.

**Comment by gbalint** [comment]
@homotopycolimit I think we decided that currently we stay with ethersphere fork. I suggest @cooganb the same method as ours: first make a PR against ethersphere/go-ethereum/master and when the discussion is over there and the PR is accepted, then make another PR against ethereum/go-ethereum/master, mention that the swarm team approved the change, and get it reviewed by the go-ethereum team too.

**Comment by gbalint** [comment]
Another question: what should be the result if the content-type in the request header is application/json? Let's not reduce our usecase to the web browser.

**Comment by cobordism** [comment]
> what should be the result if the content-type in the request header is application/json? Let's not reduce our usecase to the web browser.

ah! I had only considered the browser!

I don't know what the json response should be. You want there to be a default json response too? ...Maybe just a very simple json files with a single entry `supported_protocols:[bzz,bzz-raw,bzz-list,bzz-immutable]`. (OK I just made that up, do you have any better suggestions? Can we just give HTTP 200 and an empty json `{}`?)

**Comment by gbalint** [comment]
I like having standard-like extra fields in the json with meta-information, something like:
{
   "success": false,
   "error": {
       "code": XXX,
       "message": "Empty bzz url"
   }
}

But that would mostly make sense if we would use the same format across our json responses.

**Comment by cobordism** [comment]
> But that would mostly make sense if we would use the same format across our json responses.

What could be a good first step to solve the issue at hand (i.e. get from an error to a valid HTTP 200)?
We can always iterate later and expand the response.

I'd also like to emphasize that the browser http://localhost:8500 landing page is the first thing that **most** people who are currently playing around with swarm will see; at it will be the first thing they see after successfully installing and starting swarm.

**Comment by gbalint** [comment]
Ok, let's skip the json response for this issue, it can be a separate one: https://github.com/ethersphere/go-ethereum/issues/185

**Comment by cooganb** [comment]
hey all, i'm trying to get my setup going and encountered a few issues.

first, i checked out a local branch from the ethersphere/go-ethereum master, but when trying to push the new branch back to the master to create the first "blank" PR, i get this:

```
[ec2-user@ip-172-31-58-0 go-ethereum]$ git push origin issue-155
Username for 'https://github.com': cooganb
Password for 'https://cooganb@github.com':
remote: Permission to ethersphere/go-ethereum.git denied to cooganb.
fatal: unable to access 'https://github.com/ethersphere/go-ethereum/': The requested URL returned error: 403
```

does someone need to grant me permission to push? or am i doing something incorrectly with the command line?

second, i'm trying to figure out how to test my code before asking for a pull-request. i'm a novice, so my apologies in advance for basic questions, but how exactly do i go about testing changes on the code locally to be confident enough to issue a real PR?

**Comment by cobordism** [comment]
you want to fork the ethereum/go-ethereum repository and push to your own fork.
You create a Pull Request from your fork of the repo to the ethersphere fork.
You can issue a PR right away even before your code is ready and update the code later.

**Comment by cooganb** [comment]
Let me know if I did this correctly!

**Comment by gbalint** [comment]
No, your pull request is not correct:
"cooganb  wants to merge 58 commits into cooganb:master from ethersphere:master"

You would like to submit the PR in the other direction: into ethersphere:master from your fork. And I would also create a branch in your fork and not submit the PR from master.

You can also see that it is not what you wanted because the diff contains a lot of stuff which is not made by you:
https://github.com/cooganb/go-ethereum/pull/1/files

**Comment by gbalint** [comment]
@cooganb I suggest you to read this guide, it helps understanding forks, PRs and the whole workflow to contribute to an open source project: https://gist.github.com/Chaser324/ce0505fbed06b947d962

**Comment by cooganb** [comment]
this is great! thank you!

**Comment by cooganb** [comment]
@homotopycolimit okay! round 2. apologies for my earlier issue . followed the doc you sent @gbalint  and hopefully did it correctly this time.

**Comment by gbalint** [comment]
@cooganb Yes, the PR is in correct format now 👍
