### ISSUE TITLE
Running SWAP on non-swap networks should cause the client to terminate with fatal error

### ISSUE THREAD

**Issue by vojtechsimetka** [ethersphere/swarm#1550]
# Problem
Once we merge to master, anyone will be easily able to start node with SWAP enabled. This could confuse users since their nodes will likely start disconnecting for peers. This could also potentially even negatively affect the whole health of network.

# Proposed solution
Create a blacklist of networks that can not be joined if SWAP is enabled. Upon starting the node, if the node attempts to connect to this network, kill it.

**Comment by mortelli** [comment]
Solved by PR #1606.
