### ISSUE TITLE
Unify naming for `issuer` & `beneficiary`

### ISSUE THREAD

**Issue by vojtechsimetka** [ethersphere/swarm#1553]
In the smart contracts we are now using `issuer` to indicate the owner of the SWAP chequebook who is also issuing cheques and `beneficiary` as the recipient of the cheques and ultimately the payments.

However, in the go code we still sometimes use a different names like `owner` that are confusing.

**Comment by santicomp2014** [comment]
On hold until PR #1718 is merged.
A refactor on my side will be necessary to incorporate the changes made in that PR.
