### ISSUE TITLE
Review Incentive logging levels

### ISSUE THREAD

**Issue by vojtechsimetka** [ethersphere/swarm#1563]
# Problem
Currently we only use a lot of `log.Info` and `log.Error` messages. This could be quite polluting for when we run production version.

# Task
Review the logging we use and use different levels of verbosity.

**Comment by mortelli** [comment]
Also, check that after an error occurs and is returned, the layer that handles the error after receiving it should be the one logging it.

**Comment by vojtechsimetka** [comment]
Outcome from discussion with @nonsense and @acud:

- Currently there is no consistent way of handling errors in the codebase and there is no support for propagating error's context
- The recommendation was to rather log errors duplicately than lose the context
- When [xerrors](https://crawshaw.io/blog/xerrors) become available in go 1.13 we should review this

**Comment by mortelli** [comment]
See also #1593.

**Comment by mortelli** [comment]
PR #1559 has been merged, and this will be further iterated on #1593/#1623.

Closing.
