### ISSUE TITLE
review PSS and pushsync

### ISSUE THREAD

**Issue by nonsense** [ethersphere/swarm#1574]
It'd be nice to review PSS sending of messages and handling/processing of messages, as there are a few unclear design decisions or bugs:

As an example:
1. `enqueue` is using a very large buffered channel with `outbox`
2. `outbox` is processing synchronously one message at a time.
3. `SendRaw` is not just sending, but also executing handlers synchronously.

These are a some of the issues I've come across while trying to understand why PSS gets slow when running Swarm with Push Sync functionality.

Changing these results in many failed tests, so before I spend more time on it, I think it'd be helpful to pair up with @nolash to understand better the request/handle flow.

**Comment by nonsense** [comment]
@nolash let's arrange a meeting early next week when you're back from vacation, to show you my findings are review how we can approach some of the identified problems :)

**Comment by zelig** [comment]
are being addressed in https://github.com/ethersphere/swarm/pull/1680, https://github.com/ethersphere/swarm/pull/1392
