### ISSUE TITLE
Broken link on swarm guide - introduction

### ISSUE THREAD

**Issue by thecircleoflifefree** [ethersphere/swarm#1588]
#### Current information

This is the link being used: https://swarm-guide.readthedocs.io/en/latest/introduction.html

#### Expected behaviour

Click hyperlink and be directed to a non broken URL.

#### Actual behaviour

404 Page not found.

#### Steps to reproduce the behaviour

Go to the introduction web page:
https://swarm-guide.readthedocs.io/en/latest/introduction.html

On the 1.3 Overview section the following text has the word 'Roadmap' anchored to a broken href.

"(see Roadmap for more details)."

Anchor:
<a class="reference external" href="https://github.com/orgs/ethersphere/projects/5">Roadmap</a>

#### Backtrace

Not sure if it should be using this one instead:
<a class="reference external" href="https://github.com/ethersphere/swarm/wiki/roadmap">development roadmap</a>

Not a big issue really.. Cheers!

**Comment by skylenet** [comment]
This seems to be fixed now. The roadmap link now points to https://github.com/orgs/ethersphere/projects/8

Thanks for reporting this issue :+1:
