### ISSUE TITLE
Create a configurable price oracle for testing

### ISSUE THREAD

**Issue by holisticode** [ethersphere/swarm#1597]
The first testnet deployments of `Swap` enabled nodes will have to be experimented with heavily on many levels, specifically:
* different pricing
* different thresholds

So we need a way to dynamically (and easily) update the network with the latest prices. This means we will have to run some kind of `ConfigurablePriceOracle` in some way.

This  task is about specifying and implementing such an oracle

**Comment by Eknir** [comment]
Is somebody working on this already? I would be happy to take upon me this issue, as I already implemented configurable thresholds (#1441). 

When we talk about different pricing, do we talk about different message prices (in honey( or different honey prices (in Wei), or both.

We are introducing many configuration options here, which only have purpose in testing (I am talking about the possibility to adjust payment thresholds and set your own prices as a node). Do you think it is the way to go to have such configuration options exposed to the user (i.e. config / flag) or shall we perhaps create a way for configuration which is meant solely for the purpose of experimentation (perhaps this already exists?)?

**Comment by mortelli** [comment]
Price oracles are no longer implemented in Go, so this idea will be continued on issue #1848.
