### ISSUE TITLE
On node startup, check the contract is already deployed

### ISSUE THREAD

**Issue by holisticode** [ethersphere/swarm#1599]
Currently, when we start up the node, we deploy the contract every time.

We need to check when we start the node if the contract has already been deployed, and if it has, not deploy again.

**Comment by vojtechsimetka** [comment]
I would go even further. User should be able to provide the contract address through config/argument. 

Arguably it should only be deployed when the first cheque is needed to be issues, but not sure.

**Comment by ralph-pichler** [comment]
> Arguably it should only be deployed when the first cheque is needed to be issues, but not sure.

That would break the way we currently exchange contract addresses. We expect both parties to already have the address at the moment of the handshake of the swap protocol.

**Comment by mortelli** [comment]
for clarification purposes: could someone please document here (or there) the difference between this issue and #1548?

relevant PR: #1718
