### ISSUE TITLE
Cash-in delay

### ISSUE THREAD

**Issue by Eknir** [ethersphere/swarm#1631]
Currently, the `defaultCashInDelay` is set as a constant in `defaults.go`. 

However, `timeout` is a field of a cheque, hence it could be very well the case that one person sends a cheque with a timeout x, and the other one sends a cheque with a timeout y. Setting the timeout as a constant - applicable to all peers does not reflect the fact that timeout can change for every peer.

This issue becomes redundant once the chequebook simplification is in place.

**Comment by ralph-pichler** [comment]
The current logic only accepts cheques which have timeout 0. Therefore it is actually the same for all (accepted) cheques and all peers.

**Comment by holisticode** [comment]
@ralph-pichler @Eknir can you confirm we can close this issue now that we have the `SimplestSwap` PR merged?

**Comment by ralph-pichler** [comment]
Cash-in delay no longer exists as of #1683
