### ISSUE TITLE
Implement an MVP on-chain price oracle

### ISSUE THREAD

**Issue by Eknir** [ethersphere/swarm#1632]
Currently, the go-code houses a file ``oracle.go``. To make the codebase more realistic, we should implement a very simple on-chain price oracle.

**Comment by holisticode** [comment]
Keep in mind that we need easy unit testing, and we may not want to have to run blockchains for simple tests. So we will need mocking of the on-chain oracle or something equivalent.

**Comment by holisticode** [comment]
Duplicate of https://github.com/ethersphere/swarm/issues/1848
