### ISSUE TITLE
Never send cheques when not enough balance in chequebook

### ISSUE THREAD

**Issue by Eknir** [ethersphere/swarm#1639]
SWAP should make sure that the user never ovepromises on his cheques. 
If a peer ever writes a cheque that increases the total amount of uncashed cheques above the total amount of balance in the chequebook (assuming no hardDeposits), he risks that his chequebook fires a chequeBounced event and that peers will disconnect (?) from his. 

Proposed solution:
1) Keep track of the amount of all submitted cheques (cashed / uncashed), 
2) keep track of the amount of money deposited. *
3) Make sure that 1 never goes above 2. Auto-send more funds or temporarily halt all operations until there is money again in the chequebook. 

* the chequebook fires a Deposit event when money is deposited and money can be deposited also outside of the SWARM repository. Therefore, the SWARM sourcecode should just assume naively that only money is deposited via it's own process, but when it attempts to submit money (3), it should query the smart-contract for deposit events before depositing itself, to make sure that the internal account of deposit equals the blockchain count of deposit.

**Comment by mortelli** [comment]
duplicate of #1885?

**Comment by Eknir** [comment]
Yes, duplicate! Closing this issue
