### ISSUE TITLE
Exchange lastCheque 

### ISSUE THREAD

**Issue by Eknir** [ethersphere/swarm#1640]
Based on a TODO in the code:
When two peers connect and they already have cheques submitted to each other before, they should exchange the last known cheque with each other. 

Up for discussion: why would an issuer of a cheque do this? It is in his incentive to not exchange the last known cheque in the hope that a node loses his cheque. 
Besides, if a peer peer has lost a cheque for whatever reason, the peer will be on-track again (in the current implementation) right after he receives a new cheque from the issuer (as the cheque amount is always cumulative). 

My personal opinion is that sending last-know cheques at handshake seems like a pre-mature optimization and that we can wait for the network to be live to gather statistics on lost cheques and how nodes behave if the do.

**Comment by mortelli** [comment]
@ralph-pichler do you agree on deprecating this through #1887?

**Comment by ralph-pichler** [comment]
I don't think the PR addressed the things described here. But I don't think there is any plan for this exchange at this point, so maybe we should close this?
