### ISSUE TITLE
Failing test in protocol_test.go

### ISSUE THREAD

**Issue by Eknir** [ethersphere/swarm#1642]
This code block was found in the source code. Copying it as an issue now to clean-up the code:

TODO: This test actually fails now, because the two Swaps create independent backends, thus when handling the cheque, it will actually complain (check ERROR log output) with `error="no contract code at given address"`.
Therefore, the `lastReceivedCheque` is not being saved, and this check would fail. So TODO is to find out how to address this (should be by having same backend when creating the Swap) if creditorSwap.loadLastReceivedCheque(debitor.ID()) != cheque {t.Fatalf("Expected exactly one cheque at creditor, but there are %d:", len(creditorSwap.cheques))}

**Comment by holisticode** [comment]
Addressed in #1721
