### ISSUE TITLE
Sending cheques return value

### ISSUE THREAD

**Issue by Eknir** [ethersphere/swarm#1643]
In swap/swap.go sendCheque, we send a cheque to a peer, but never check whether sending the cheque succeeds.
The function sendCheque should take into account the possibility of sending not succeeding, attempt to re-send (if the error condition allows this) and not reset the balance if sending is not possible.

**Comment by mortelli** [comment]
Should be completed along with/after #1601 and #1635.

**Comment by ralph-pichler** [comment]
The error is now handled (albeit not optimally) and the pending cheque mechanism takes care of the resending.
