### ISSUE TITLE
Implement chequebook without waivers in go-code

### ISSUE THREAD

**Issue by Eknir** [ethersphere/swarm#1644]
Dependent on https://github.com/ethersphere/swap-swear-and-swindle/issues/71, currently being implemented.

This task is completed if the go-bindings are updated and all references to waivers are deleted from the go-code. More clarity will be provided once the smart-contracts are ready.

**Comment by Eknir** [comment]
Replaces: #1631

**Comment by ralph-pichler** [comment]
implemented in #1683
