### ISSUE TITLE
pss: Modularize crypto and remove Whisper

### ISSUE THREAD

**Issue by nolash** [ethersphere/swarm#1655]
The use of `whisper` in `pss` is a hack, and should be cleanly implemented that limits the components used to components required. 

Furthermore, `pss` should allow for any encryption and key exchange/shared secret scheme. 

This process has the following steps:

[ ] - Distill `whisper` elements in `pss` to a custom fallback crypto that ideally takes just the elements from the `whisper` source code that are needed.
[ ] - Define a modular crypto API based on a selection of reference message crypto implementations
[ ] - Implement API
[ ] - Move fallback crypto into separate package, connected to abovementioned API

**Comment by kortatu** [comment]
I've started working on this. First I want to extract all whisper usage to a unique file.
Then I want to stop using whisper types and use our own types (Topic, Envelope, ReceivedMessage).
This way it will be easier to see which functions and data are we using from whisper and which not.

This will facilitate the extraction of the crypto library.
