### ISSUE TITLE
Unify and complete SWIPs describing generic payment modules, L2 settlements and selection during handshake of payment method.

### ISSUE THREAD

**Issue by diegomasini** [ethersphere/swarm#1657]
The unification will cover the description of generic payment modules that abstract the specific payment mechanism being use, the selection mechanism for nodes to negotiate which payment module to use and and the required APIs.

This functionality is not integral to Swarm's design nor operation. However, it is of high interest to partners.

**Comment by mortelli** [comment]
@diegomasini what's the status here? can we close this?

**Comment by Eknir** [comment]
@diegomasini , heads up please!

**Comment by Eknir** [comment]
1 week
