### ISSUE TITLE
multihash support in swarm

### ISSUE THREAD

**Issue by cobordism** [ethersphere/swarm#166]
We are often asked about multihash support.

We should have a proper discussion about pros and cons at least. I suggest this issue shall be the place for that discussion until someone formulates this as an EIP (or is it SIP?)

**Comment by cobordism** [comment]
I'll start:

Pros: allows multi-hashes to be stored in ENS making it easy to use ENS with swarm and ipfs and other p2p storage solutions.

Cons: Makes ENS registration a little more expensive (store two words instead of one because multihash is longer than a swarm hash)

**Comment by Arachnid** [comment]
I'd like to see Swarm move to Multihash for ENS, at least, because it would allow us to have a single resolver profile for all content-addressed networks, and because it provides an upgrade path for changes in hash function.

**Comment by nagydani** [comment]
Is the proposal only for root hashes or also for intermediate chunk hashes in low-level Merkle trees?

**Comment by cobordism** [comment]
I must admit that I'm not entirely sure how multihashes look. I understand that it is a hash with metadata about what type of hash it is.
Thus I thought we could keep the internal structure of swarm intact and just use the longer multihashes (swarm hash + extra data?) as roothashes stored on ENS.

**Comment by nolash** [comment]
the metadata bytes should be a separate data field from the hash value itself

storing metadata should be optional, meaning I should be able to only pay for / use 32 bytes if I want to.

As long as we open this discussion, another question that follows is should ENS allow for even longer data values than this? In fact, should it allow for arbitrary values? Let's say someone comes along who wants to use ENS with some scheme that uses 512 bit or 1024 bit hashes? The latter would thus require 5 data fields. 

Yes, internally in swarm we should definitely keep the hash as-is.

**Comment by cobordism** [comment]
> should ENS allow for even longer data values

That's a question about the resolver contracts. As such it is possible to write a resolver that stores any data. 
The current discussion pertains to the content() field of the default resolver contract. How can we use it to store hash such that we can easily use Swarm and IPFS and other hash-based storage networks?

**Comment by zelig** [comment]
ok I dont see a problem with using multihash in ENS. 
As long as intermediate hashes of the swarm hash as well as hashes in manifest entries remain 32 byte long

**Comment by cobordism** [comment]
but doesn't the ens entry have to be a swarm root hash?

**Comment by cobordism** [comment]
@zelig 
as we discussed at the cafe today: let' s do it:
https://github.com/ethersphere/go-ethereum/issues/186
