### ISSUE TITLE
add documentation for pin API

### ISSUE THREAD

**Issue by zelig** [ethersphere/swarm#1666]
as per 
https://github.com/ethersphere/swarm/pull/1509
and
https://github.com/ethersphere/swarm/pull/1658

**Comment by jmozah** [comment]
@zelig Should this be only explaining the HTTP APIs or do i add some text about what pinning is all about?

**Comment by jmozah** [comment]
@zelig  https://github.com/ethersphere/swarm-docs/pull/21

**Comment by jmozah** [comment]
merged
