### ISSUE TITLE
Error pages should not contain swarm-gateways.net

### ISSUE THREAD

**Issue by cobordism** [ethersphere/swarm#167]
Currently the error pages contain hard-coded links to swarm-gateways.net

These should be replace with straight-up bzz:// URLs.

Examples: 
https://github.com/ethersphere/go-ethereum/blob/master/swarm/api/http/error_templates.go#L390
https://github.com/ethersphere/go-ethereum/blob/master/swarm/api/http/error_templates.go#L542
also line 365, 214 and possibly more.

**Comment by gbalint** [comment]
But the straight up bzz:// urls will not work in normal browsers, isn't that a problem?

**Comment by cobordism** [comment]
a hardcoded "swarm-gateways.net" is certainly wrong. If we want the link to work now (without URL handlers or plugins) we can change the URL to either

1. href="/bzz:/theswarm.eth/"

2. https://ethersphere.github.io/swarm-home/

**Comment by cobordism** [comment]
the bzz:// will only work in dedicated swarm browsers such as Mist

**Comment by gbalint** [comment]
Isn't the 1st solution broken in swarm browsers? You are on bzz://something, then you click on /bzz:/theswarm.eth, it will bring you to bzz://something/bzz:theswarm.eth, which is broken.

**Comment by cobordism** [comment]
yes. Thus I am not advocating that solution.
In fact I want to get rid of those kinds of links. Here is one https://github.com/ethersphere/swarm-home/blob/master/index.html#L321

**Comment by zelig** [comment]
see https://gist.github.com/gbalint/9e43a97a781b482731f1542ff683cf35
related to #152, #165 and #174
