### ISSUE TITLE
Test with go-ethereum 1.9.2 are failing

### ISSUE THREAD

**Issue by janos** [ethersphere/swarm#1690]
#### System information

Swarm version: 0.4.4-unstable
OS & Version: any
Commit hash : becd14092d8bac9130ad5fa3692c3c863036de8a

#### Expected behaviour

All test should pass successfully.

#### Actual behaviour

After upgrading go-etehreum dependency to version 1.9.2, some tests are failing or timing out.

This is demonstrated in PR https://github.com/ethersphere/swarm/pull/1689.

#### Steps to reproduce the behaviour

```
go run build/ci.go test
```

#### Backtrace

https://travis-ci.org/ethersphere/swarm/jobs/575854374

**Comment by zelig** [comment]
fixed  in #1689
