### ISSUE TITLE
SWAP: Refactor contractAddress

### ISSUE THREAD

**Issue by Eknir** [ethersphere/swarm#1728]
Currently, the contractAddress of the chequebook contract is stored at two places:

- `Swap.owner.Contract` 
- `Swap.contract`

To avoid mistakes in the future and clean up some redundant code, we should only set it at one place. I propose to delete the contract reference in the `Owner` struct, and make sure that the contractAddress is publicly exposed via `Swap.contract.ContractParams()` or elsewhere.

**Comment by ralph-pichler** [comment]
Can we close this?
