### ISSUE TITLE
Write JS snippet which rewrites bzz:// urls to gateway urls

### ISSUE THREAD

**Issue by gbalint** [ethersphere/swarm#174]
We would like to provide a small JS script which can be added to webpages to rewrite bzz:// links to  http://current.gateway/bzz:/ links, so the page can work for users who don't run swarm nodes or any other special swarm software.

See the details here:  https://gist.github.com/gbalint/9e43a97a781b482731f1542ff683cf35

**Comment by gbalint** [comment]
https://github.com/ethersphere/swarm-url-rewriter/

**Comment by cobordism** [comment]
Why do we need to include "swarm-gateways.net" in the javascript file?

Can we not automatically use whichever host we are on? i.e. if a user is browsing at localhost:8500 then the script will replace `bzz://` with `http://localhost:8500/bzz:/` and if a user is browsing on swarm-gateways.net then the script will use that?.. and so on.

**Comment by lmars** [comment]
Or, just replace `bzz://...` with `/bzz:/...`?

**Comment by cobordism** [comment]
yeah, that might work too. Indeed I think it's simpler, yet functionally equivalent.

**Comment by gbalint** [comment]
Ok, please check this: https://github.com/ethersphere/swarm-url-rewriter/commit/d369f6688248e73d8cc50a396d8cd4ffa577fa10

**Comment by cobordism** [comment]
So we should add this JS sippet to all our swarm pages, yes?

**Comment by gbalint** [comment]
See https://github.com/ethersphere/go-ethereum/pull/192 for the error templates. As I see there are no other gateway urls in the swarm codebase. As next step I'm checking the swam homepage

**Comment by gbalint** [comment]
I realized that there are only relative urls in the swarm homepage, so no need to update that.
@homotopycolimit Do you think there is anything else I should update?

**Comment by cobordism** [comment]
let me see... there is the swarm homepage, there is fabio's dapp overview (swarmapps.eth), and then there are the dapps - but they don't contain bzz:// URLs ...

**Comment by gbalint** [comment]
Too hacky solution, conflicts with the js of the dapps
