### ISSUE TITLE
Add constructors to price

### ISSUE THREAD

**Issue by holisticode** [ethersphere/swarm#1785]
This issue comes out of a PR: 
https://github.com/ethersphere/swarm/pull/1771#pullrequestreview-290319467

"great change. looking at the code maybe best time to add constructors to price:"

```
SenderPays(1)
ReceiverPays(1).PerByte()
```

**Comment by ralph-pichler** [comment]
Considering the old pricing scheme is dead i think we can close this, @Eknir ?

**Comment by Eknir** [comment]
Yes!
