### ISSUE TITLE
Refactor swap logs with actions prefix

### ISSUE THREAD

**Issue by santicomp2014** [ethersphere/swarm#1788]
In order to filter swap logs, the prefix of swap logs has to be refactored

currently swap logs are prefixed with 

> swap-logs "*"

This creates a conflict when searching such logs.

as @skylenet mentioned we should change the logs to use actions instead of a generic prefix. 

> For now I would prefer to just tag your log line like:  swap.{action}  e.g. swap.contractDeployed   addr=1234 owner=4123. You can then easily filter the logs by those tags.

**Comment by Eknir** [comment]
@santicomp2014 , what is the status of this issue?

**Comment by santicomp2014** [comment]
3 Working days
