### ISSUE TITLE
Saving cheques

### ISSUE THREAD

**Issue by Eknir** [ethersphere/swarm#1796]
`balanceKey`, `sentChequeKey` and `receivedChequeKey` are the keys for looking up respectively the balance, sent cheques and received cheques from a peer. However, the peers might be peers on multiple Ethereum networks, hence the keys must be appended with a networkID value (just as in the `usedChequebookAtNetworkKey`)

Without fixing this issue, accounting and peer interacting will probably result in bugs if the node has been connected to the same peers on different networks.

**Comment by holisticode** [comment]
Decisions as per 24th September:

* One `StateStore` instance per bzz NetworkID
* The `StateStore` has no prefix for the blockchain ID
* It is assumed that when you start the node and provide the swap-backend-url (and thus to which the chequebook is being deployed to and the factory you are going to use), that this is the backend you are going to use for this node
* In other words, the node stores the first provided blockchain ID. If you restart the node and provide a different swap-backend-url, this would result in an error (and not boot the node)
