### ISSUE TITLE
Mutable resource updates outstanding tasks

### ISSUE THREAD

**Issue by zelig** [ethersphere/swarm#180]
* [x] API for lookups: (1) latest (2) historical (3) particular version
* [x] ~use swarm storage stack for resource update chunks~ 
* [x] signature implementation: the text that owner signs should contain the key `K=Hash(name|period|version)`. so `S = Sign(Hash(K|CH)` where CH  is the content hash of the version in question and the data of the update chunk is `D=S|CH|period|version|name`. This is needed otherwise any hash the owner ever signs can be submitted by malicious parties as resource update.
* [x] resource update validation . content hash, period, version and name should be parsable from the data in order to validate the resource update. as per the previous point 
* [x] http API for the API lookups
* [x] manifest entry content type to allow server to follow mutable resources; 
* [x] strict lookup mode: complain if version forks (usecase: sw3 promise of no fork truthline)
* [ ] resource update stream using network rewrite stream subscription layer; use pss for remote broadcast
* [x] ~create ENS resolver that accepts transactions with arguments `blockNumber, version, CH, S` from any third party to update the record~ see https://github.com/ethersphere/go-ethereum/issues/205
* [x] ~The ENS resolver should register blockNumber and frequency of updates (the latter only changable by the owner). Then root entry chunks are not needed.~
* [x] instead of blockNumber, period should be represented by the index of period. I.e., `latestPeriod = (currentBlock - startBlock) / frequency`. This would make period and version more like major and minor version numbers plus we could use 32 bit integers for both 
* [x]  Parse update data as multihash if datalength is set to 0

**Comment by cobordism** [comment]
> resource update stream using network rewrite stream subscription layer; use pss for remote broadcast

Is this what you would use if you wanted two fuse-mounted dropbox like directories to remain in sync?
(I mean the same directory mounted on two different machines))

**Comment by zelig** [comment]
@homotopycolimit yes i think so

**Comment by nolash** [comment]
@zelig Concerning the data format:

`D=S|CH|period|version|name`

Currently the code does not opinionate the actual data part to be a content hash, but of course it can be (and will be in most cases). Thus right now it looks like this:

`D=S|headerlength|period|version|name|data`

Where `CH` will be `data` (but not necessarily the other way around) and `headerlength` is the byte length of `period|version|name`

`headerlength` is 2 bytes, `period` and `version` is 4 bytes each. `name` allows for arbitrary length.

I suggest we keep it like this.

**Comment by adamschmideg** [comment]
Done
