### ISSUE TITLE
Network rewrite streamer/syncer related issues

### ISSUE THREAD

**Issue by zelig** [ethersphere/swarm#181]
network rewrite streamer phase breakdown of tasks
* [x] persistent stateStore implementation for kademlia table
* [x] there should be a test in discovery to see if the persisted peer set (1) is found and loaded (2) bootstraps healthy kademlia without any connections (3) benchmark the reduction of time reaching health
* [ ] allow syncer to operate in mock storage mode, i.e., no need to pass the chunk data
* [x] chunk validity check should be abstracted (different for content chunk, resource chunk, test-mock-storage)
* [ ] ~chunk interface~
* [x] after the request fails it should be removed from the  @memstore
* [ ] ~request repeat if downstream disconnects~
* [x] streamer API, syncer API. used in sim test => simplifies tests
* [x] write in batches https://github.com/ethersphere/go-ethereum/blob/swarm-gateways-db-fixes/swarm/storage/dbstore.go
* [x] for proper handling of waiting for storage #179 dbStored field should be lock protected
* [x] possibly combine with https://github.com/ethersphere/go-ethereum/blob/swarm-db-sync-fix-pyramid and test 
* [x] streamer protocol message exchange unit tests using `p2p/testing`
* [x] request/delivery functional tests using `p2p/simulations` chain of nodes
* [x] per-bin syncer functional tests using `p2p/simulations` chain of nodes
* [x] fix `network/simulations/discovery_test.go` and rework it using `p2p/testing/simulations`
* [x] implement unsubscribe message and method
* [x] implement subcribe error responses
* [x] implement Client Close (just like Server Close) and call it in https://github.com/ethersphere/go-ethereum/commit/f568ef178e686d6540c6614f74d6d20a5d71a616#diff-524f169c33e854ca57a6e668ce319a9bR345
* [x] pass Live bool flag similarly to Key
* [x] adapt syncer iterator to new syncer
* [x] save intervals - needs to be concurrent for racing mode light client download request
* [x] upstream peer sends sessionAt on subscribe
* [x] functional tests for historical syncing using intervals
* [x] functional tests for historical syncing across sessions using persisted intervals
* [ ] ~db purge/delete triggsers provable syncer ~
* [ ] ~cached deliveries should not enter syncpool?~
* [ ] ~light node client/server streamers for requests~
* [ ] adapt livepeer streams
* [ ] ~rework `network/stream/testing` as `p2p/testing/simulation.go` unless we want to keep it in our own yard~
* [x] implement subscribe request for light node upload  
* [x] dbstore: export import to be adapted adapted, dump, reindex, cleanup removed, 
* [ ] ~write syncer tests with netsim and mock storage for old syncers~

**Comment by gbalint** [comment]
> syncer streams are

@zelig this looks like a typo, what is this wanted to be?
