### ISSUE TITLE
Don't give error if hashes are prefixed with 0x

### ISSUE THREAD

**Issue by cobordism** [ethersphere/swarm#182]
The hash for the site theswarm.eth is currently `2c2d2adb8fd0cba399282fb59f8219e5fbbd67ba06fcf5c8d343f5eb1c8be022`

It is documented that if you are setting a content hash in ENS and you submit that hash, you are making an error. The correct hash to submit to ENS is `0x2c2d2adb8fd0cba399282fb59f8219e5fbbd67ba06fcf5c8d343f5eb1c8be022`

Conversely, I have just discovered that calling the **0x** hash on bzz gives an error too
See for example:
http://swarm-gateways.net/bzz:/0x2c2d2adb8fd0cba399282fb59f8219e5fbbd67ba06fcf5c8d343f5eb1c8be022/

Surely this can be fixed. 

Possibly solutions:
- * If you encounter a bzz:/0xHASH request, redirect HTTP 301 to bzz:/HASH
- * Serve the same content at 0xHASH as you would at HASH
- * Display a helpful error to the user, telling them to remove the 0x form the URL

**Comment by cobordism** [comment]
possibly related: https://github.com/ethersphere/go-ethereum/issues/166

**Comment by acud** [comment]
The first approach seems like the most feasible if we really want to actually display the content seamlessly. API consistency would lead to actually throwing an error. A few questions:

- should this reflect just on GET operations? or do we want to reflect on all CRUD operations? I would just fear how clients will handle a redirect on a POST/DELETE (in case it's a custom client)
- should this reflect on all GET operations, or just when fetching the root hash? (e.g. also on `HandleGetList`, `HandleGetFile` etc)
- the hash could hypothetically start with a `0x`, which means we need to introduce hash size checks, which in turn means tight coupling with the hashing algorithm (not a big fan of this idea)

**Comment by gbalint** [comment]
@elad-nach 

- POST and PUT is only available in case of bzz-raw requests, either without a hash (upload), then the question is not relevant (no hash to add `0x` to), or with a hash and a path (to add a manifest entry). See http://swarm-guide.readthedocs.io/en/latest/usage.html?highlight=post#the-http-api . The manifest update is a relevant case, I'm not sure what we should do, I agree that redirect could be problematic.
- I think all GET operations should be affected, I don't see that problematic

Doesnt' this problem suggest that maybe the second solution is better: "Serve the same content at 0xHASH as you would at HASH"

@homotopycolimit ?

**Comment by acud** [comment]
i think that requested resource should reflect itself - a browser/client should redirect and request the correct resource name and not transparently serve resource aliases. less magic and less abstraction that we need to maintain.

it might also lead to implementation divergence when 3rd party developers will interface to the API, leaving us with a necessity to support both interfaces in the future.

thinking about this more - it looks more tempting to actually throw a helpful error rather than supporting both implementations. but in any case it might be nice to have a look at the swarm-gateways access logs and see if anyone at the moment tries to access resources this way.

**Comment by cobordism** [comment]
> but in any case it might be nice to have a look at the swarm-gateways access logs and see if anyone at the moment tries to access resources this way.

I found the error from somebody's question in the swarm channel. 
It is also confusing that when registering a swarm hash in the ENS you _have_ to add the 0x. This is unfortunate.

I don't mind an error message.... we could even have the error page offer the corrected link.

**Comment by gbalint** [comment]
Let's go with the error then
