### ISSUE TITLE
Create a custom 502 page for the gateway

### ISSUE THREAD

**Issue by holisticode** [ethersphere/swarm#184]
In our `swarm-gateways.net` cluster, we run a nginx server reverse proxying to swarm nodes. If swarm nodes can't be reached, nginx displays a standard `502 Bad Gateway` error message.

The gateway should have a nicer and more informative custom page.

**Comment by nonsense** [comment]
@gbalint @holisticode we return 502 Bad Gateway, when our nodes crash. I think we shouldn't waste any time configuring those pages as part of nginx or Swarm. Not sure we need this issue at all.

**Comment by cobordism** [comment]
a less scary error page is always nice... but we don't _need_ it.
since this is an issue for the cluster and not for swarm, I'll close this issue here. We can always re-open on the cluster repo if we decide we want to do this.

**Comment by nonsense** [comment]
I'd rather we have the ugly error page, because 502 are triggered by `panics` or really long timeouts - we should be addressing those immediately when we notice them.
