### ISSUE TITLE
Implement on-chain oracles (smart contracts) and integrate into go code (query)

### ISSUE THREAD

**Issue by holisticode** [ethersphere/swarm#1848]
We now have defined that prices will be queried via oracles.

We need to implement these oracles and the actual querying of them from the go code.

For testing, we would deploy different oracles (on a test net), and for experimentation we can change at will the test oracle prices

**Comment by holisticode** [comment]
Keep in mind that we need easy unit testing, and we may not want to have to run blockchains for simple tests. So we will need mocking of the on-chain oracle or something equivalent.

**Comment by ralph-pichler** [comment]
Which oracles are still planned at this point?

**Comment by holisticode** [comment]
Current pricing design is different from the original pricing oracles scheme. Closing this issue.  New pricing strategy should create new issues as needed.
