### ISSUE TITLE
Allow refunding

### ISSUE THREAD

**Issue by Eknir** [ethersphere/swarm#1886]
Currently, the Swarm source-code allows an operator to fund his chequebook at one point: upon deployment.

To make the life of a node operator easy, I propose to allow him to refund his chequebook when, upon boot up, the availableBalance is below or at the paymentThreshold.
Dependent upon #1884

**Comment by mortelli** [comment]
this is a good quality of life type of feature, but let's remember not to block the regular way of booting up swarm with a prompt.

other than that, i'm all for this one :+1:
