### ISSUE TITLE
Rename swarm deb package

### ISSUE THREAD

**Issue by gbalint** [ethersphere/swarm#191]
the ubuntu package for go-ethereum is conflicting with an existing package which also has an executable named `swarm`. `bzz` is also taken
 
Rename to:
- ~`bzz`~ taken
- `go-swarm`   
- `gbzz`
- `go-bzz`- 
- `bzzd`
- `bee` after all you control/start/config a bee of the swarm

**Comment by cobordism** [comment]
to `go-swarm` or `gswarm` or something to prepare for multiple implementations, multiple swarm clients. Let's not confuse the network with the client.

**Comment by gbalint** [comment]
I would vote for `gswarm`, it is consistent with `geth`

**Comment by zelig** [comment]
no its not, `gbzz` is consistent with `geth`

**Comment by gbalint** [comment]
Fair enough, I meant this only between `go-swarm` and `gswarm`

**Comment by nolash** [comment]
I think `go-swarm` seems most intuitive.

**Comment by lmars** [comment]
> the ubuntu package for go-ethereum is conflicting with an existing package which also has an executable named swarm

I don't think the name of the ubuntu package should influence the name of the binary (for example to install `ping` you install the `iputils-ping` package, not the `ping` package, they don't have to match).

As mentioned [here](https://github.com/ethereum/go-ethereum/issues/3457#issuecomment-344585007), we should just change the package name to something different like `ethereum-swarm`, but the binary can still be called `swarm`.

To do so, we would need an extra field in [this entry](https://github.com/ethereum/go-ethereum/blob/master/build/ci.go#L110-L113) to indicate that the package name should differ from the binary name.

This does of course mean that running `apt-get install ethereum-swarm swarm` will lead to a conflict because both packages provide a `swarm` binary, but I think that is an edge case we don't need to worry about (this is also the case if you run `apt-get install iputils-ping inetutils-ping`).

**Comment by gbalint** [comment]
> I don't think the name of the ubuntu package should influence the name of the binary (for example to install ping you install the iputils-ping package, not the ping package, they don't have to match).

The problem is not the package name, but that it installs an executable named swarm.

**Comment by gbalint** [comment]
Sorry @lmars , I just realized that in your last paragraph you describe the binary name conflict too.

**Comment by nolash** [comment]
@lmars @gbalint what about `go-swarm` and a symlink that links to `swarm` if not exist? We could add a `bzz` symlink too.

**Comment by gbalint** [comment]
Let's just go with @lmars 's solution because that is the easiest, and ignore the executable name conflict.
Just fix the package name

**Comment by cobordism** [comment]
I know this issue was made specifically regarding the conflict, but not naming the executable `swarm` has come up several times already. Let's fix both at the same time.

**Comment by lmars** [comment]
@homotopycolimit can you expand on the reasons for needing to change the binary name? I'm not refuting your claim, just curious what the reasons are.

**Comment by cobordism** [comment]
I was thinking again, it might be ok to close this issue with just the fixed deb package name.

Changing the executable name came up (repeatedly) in the past. it was a common feedback for a while... I think it went like:

(1) It can be confusing - when you say swarm, do you mean the client or the network? (maybe think of the problems of not boing able to distinguish between bitcoin the network and bitcoin the token and bitcoin the client software... it's conceptually cleaner to separate them geth/ether/ethereum)
(2) want to allow for multiple clients interacting with the same network - swarm is this network and you interact with it using go-swarm, cppswarm, swarmctl, pyswarm or beekeper.
(3) solves the name conflict


...I don't remember all really, so I retract my objection and let you guys decide. I'm ambivalent on this.

**Comment by lmars** [comment]
Ok thanks, personally I'm not confused by the binary being called `swarm` (I in fact prefer it to all other alternatives proposed here), because it is a "CLI for Swarm" (just like `aws` is a "CLI for AWS"), but maybe that is just me.

I suspect other clients after the reference one will pick their own names (like Parity picked a name for the Rust Ethereum client, `parity`).

**Comment by nolash** [comment]
`archlinux` uses the `-cli` suffix for cli-apps... `swarm-cli`?

**Comment by lmars** [comment]
@nolash I assume you are proposing to change the ubuntu package name to `swarm-cli` (rather than the binary)?

If so, that seems reasonable, but if you mean the binary then, even in archlinux, the AWS CLI package is called `aws-cli` but it installs a binary called `aws`.

**Comment by nolash** [comment]
@lmars I use `telegram-cli` too, that installs binary as `telegram-cli`, so there seems to be some wiggle room. (`telegram-cli` is in AUR, though)

**Comment by gbalint** [comment]
I would vote for `ethereum-swarm`, because the `-cli` postfix is not typical in debian packages, and it is also clearer than `swarm` alone, which is not really a unique name.
So even if it would not be a name conflict I think it is helpful to really specify that this is the ethereum swarm, and nothing to do with plenty of other stuff out there which is called swarm, e.g. Foursquare Swarm, Docker swarm, Swarm City, etc.

**Comment by lmars** [comment]
@gbalint this is my vote too (i.e. rename Ubuntu package to `ethereum-swarm`), and I think it should still install a binary called `swarm` :v:

**Comment by lmars** [comment]
@homotopycolimit some form of change to [this code](https://github.com/ethereum/go-ethereum/blob/master/build/ci.go#L110-L113).

**Comment by cobordism** [comment]
"Ethereum Swarm daemon and tools" 
The daemon is also the tools :)

**Comment by nonsense** [comment]
Correct me if I am wrong, but the current code seems to support only packages with the same name for an executable. Do we want to go through the trouble of adding functionality for packages that install binaries with other names?

**Comment by cobordism** [comment]
I think that's what we'll have to do. Let's not re-open the renaming debate. It took too long last time ;)

**Comment by cobordism** [comment]
is it hard to do?

**Comment by nonsense** [comment]
It is the only binary/package out of all the others listed at `build/ci.go:85`, and we are just adding complexity.

It is not that I am completely against that, but we should def involve the `go-ethereum` team, before doing it.

**Comment by nonsense** [comment]
Geth team is fine with having different names for `package` and `binary` so we can go ahead and refactor `build/ci.go` (debExecutables, templates, etc.)
