### ISSUE TITLE
TestDeploy magical constant for initial deposit

### ISSUE THREAD

**Issue by Eknir** [ethersphere/swarm#1928]
Currently, the function `testDeploy` uses a magical constant for the initial deposit:
```golang
	opts.Value = big.NewInt(9000 * int64(RetrieveRequestPrice))
```
We need to make this value parametrizable for testDeploy in order to prevent cheques from being bounced and make other tests not dependable on changing this constant.

**Comment by mortelli** [comment]
should solve one of the pending issues in #1925
