### ISSUE TITLE
Low balance mode

### ISSUE THREAD

**Issue by Eknir** [ethersphere/swarm#1996]
A low balance mode for SWAP is might be used for:

- zero-eth entry
- boot up while synching
- blockchain backend now working during operation
- Out of balance during operation
- Not depositing during deployment

Such a low balance mode will ensure that the node does not cross the payment threshold with any node, thus disabling requesting of chunks and limiting routing of chunks (when near the payment threshold with a node from whom you buy a chunk for the purpose of routing).

On October 24, we spoke about this during the [research office hours](https://hackmd.io/hUuvDcIBQg6zIrA-rAonIQ#October-24) 

I propose to make a SWIP to describe the behavior of a node when he has a low balance and subsequently implement it.

**Comment by mortelli** [comment]
related, possibly duplicate: #1948

**Comment by mortelli** [comment]
per discussion during the weekly research call on 19/12:
> we shouldn't have this as a mode, as this should be the regular behavior of the nodes. 
>
> if we are processing messages which would put our node above (our version of) the payment threshold, we should stop processing those messages until either: a payment is made, or: messages are exchanged in a way that this debt is reduced. then, we'd resume processing messages until we are at this point again.
>
>we are still keeping the disconnect threshold for the purposes of dropping nodes which don't play nice, i.e. by this rule precisely.

related work on this will be continued on #1948.
