### ISSUE TITLE
Don't allow negative *big.Int in blockchain interactions

### ISSUE THREAD

**Issue by Eknir** [ethersphere/swarm#2014]
Some functions in the package `contracts/swap` have a *big.Int as input parameter. We should do an input verification that this value is not below zero, to prevent unexpected input or reverted blockchain transactions.

**Comment by Eknir** [comment]
@mortelli , as you moved this issue to "In progress": who is currently working on this issue? Is it covered by #1581?

**Comment by mortelli** [comment]
> @mortelli , as you moved this issue to "In progress": who is currently working on this issue? Is it covered by #1581?

apologies for not replying to this one up until now.

this is indeed covered by #1581. 

closing
