### ISSUE TITLE
Fix overlay simulation in swarm-network-rewrite

### ISSUE THREAD

**Issue by gbalint** [ethersphere/swarm#207]
From @holisticode on Gitter:
The overlay simulation may not be taken care of in the current rewrite branch, as it is easily missed as it is a main executable
It may be a good idea to add a test to it if we want to keep the overlay simulation
Please also add it to CI, to keep it working

**Comment by cooganb** [comment]
@holisticode I am interested in dipping into this. Any heads-up or things I should know?

**Comment by holisticode** [comment]
Well it is a bit of a moving target, as the simulation in question is contained in the `swarm-network-rewrite` branch, which is currently under (more or less heavy) development.

Nevertheless the task description for the time being is simple: Make it compile and able to be run as a main executable in the `swarm-network-rewrite` branch. Maybe add a test so when running tests we find out if it's broken (currently we only find out when we try to run it).

**Comment by gbalint** [comment]
PR: https://github.com/ethersphere/go-ethereum/pull/272

**Comment by gbalint** [comment]
Please remove throttling from https://github.com/ethersphere/go-ethereum/pull/272 and then it can be merged.
