### ISSUE TITLE
mod_time in manifest should be optional or better documented

### ISSUE THREAD

**Issue by gbalint** [ethersphere/swarm#211]
When uploading using bzz, a manifest is created which includes a timestamp of when the upload was created, so it creates a different hash each time. Uploading using `bzz-raw` (i.e. just uploading the raw bytes), will always lead to the same hash.
To demonstrate, if I upload the same data twice I'll get two hashes but inspecting the manifests, I see the same hash was stored under the path:
```
$ curl -F "my-file=data" http://localhost:8500/bzz:/
ca16a6b21ddb375fd718bb931cb039b0ff3fdaabc90b4c5e0e82604345764182

$ curl -F "my-file=data" http://localhost:8500/bzz:/
09b70636040f1a9cd88d399dc9cca3fe740e4b1283b5100e1eb57ac4d1b9c5ae

$ curl -s http://localhost:8500/bzz-raw:/ca16a6b21ddb375fd718bb931cb039b0ff3fdaabc90b4c5e0e82604345764182/ | jq .
{
  "entries": [
    {
      "hash": "61cc094e478970c7e58bf44cd1e13b2851d9cea254327d08dbdd1918b454b9f8",
      "path": "my-file",
      "size": 4,
      "mod_time": "2018-01-24T11:30:10.24894844Z"
    }
  ]
}

$ curl -s http://localhost:8500/bzz-raw:/09b70636040f1a9cd88d399dc9cca3fe740e4b1283b5100e1eb57ac4d1b9c5ae/ | jq .
{
  "entries": [
    {
      "hash": "61cc094e478970c7e58bf44cd1e13b2851d9cea254327d08dbdd1918b454b9f8",
      "path": "my-file",
      "size": 4,
      "mod_time": "2018-01-24T11:30:13.609200639Z"
    }
  ]
}
```
This being said, perhaps the addition of mod_time should be optional if people just want deterministic manifest creation.

this has been causing people headache so we should consider documenting it properly or make it optional

**Comment by cobordism** [comment]
suggestion: 1) make it optional 2) set the default as using the mod_time of the file/dir itself and not the current time. So even if I upload the same file at two different times and have mod_time turned on, I get the same hash.

**Comment by lmars** [comment]
So my original comment was incorrect, using `swarm up` with the same data creates the same hash because it uses a tar upload, which sets the mod time to the mod time of the file:

```bash
# create a file
$ echo data > file.txt

# note the modified time
$ stat -c '%y' file.txt
2018-01-24 18:38:49.000000000 +0000

# upload the file multiple times, get the same hash
$ swarm up file.txt 
a87da99aa2f3a574dd74beca0922763d80a7cce2c3bade49f9aba8cbbd898272

$ swarm up file.txt 
a87da99aa2f3a574dd74beca0922763d80a7cce2c3bade49f9aba8cbbd898272

# same for a manual tar upload
$ tar cf - file.txt | curl -X POST -H "Content-Type: application/x-tar" --data-binary @- http://localhost:8500/bzz:/
f4058423fb14fe73cd51064628b6a736ba916273198429b7d2980727ed7e5767

$ tar cf - file.txt | curl -X POST -H "Content-Type: application/x-tar" --data-binary @- http://localhost:8500/bzz:/
f4058423fb14fe73cd51064628b6a736ba916273198429b7d2980727ed7e5767
```

So it seems the issue is just with multipart-form uploads, where there is no concept of a mod time, so the server just [picks the current time](https://github.com/ethereum/go-ethereum/blob/master/swarm/api/http/server.go#L243).

**Comment by cobordism** [comment]
so what do you suggest we do @lmars? 

> the issue is just with multipart-form uploads

Should they default to having no mod_time set or should they explicitly ask for a time, or ...?

**Comment by lmars** [comment]
I think we should remove the default mod-time, and support a custom header to set it via multipart uploads (it is not the intended use, but we could consult the `Last-Modified` header in the request).

**Comment by xrn** [comment]
Hi guys !

Another day another question in my mind - i have hash of resource on swarm - like XXX i did it just by "up" command this is not Mutable Resource (here i have meta fields). Is an option to get metadata of this XXX "file" - when was created (current timestamp) and who is the owner (public key / address / digital signature?) - if this is not possible by up command how can I upload file to have this meta data (it can not be set via user it need to be set via network like timestamp of block)

Sorry if this question is stupid I made 1h research and I cannot find proper answer. I found only https://swarm-guide.readthedocs.io/en/latest/usage.html#manifests but "mod_time" is setting time from uploader machine - in my case this is not what i need - I need global timestamp.

**Comment by lmars** [comment]
@holisticode why is this closed, did we fix it?

**Comment by holisticode** [comment]
I am not sure.

We were rearranging tickets in the swarm board that day during the roundtable, and @zelig requested me to drive the session, so I was sharing my screen and moving tickets around. 

I have no clear memory of this specific ticket. It may have happened by mistake or on instruction. @zelig please review
