### ISSUE TITLE
accounting lock leads to deadlock with retrieval

### ISSUE THREAD

**Issue by ralph-pichler** [ethersphere/swarm#2110]
`retrieval` currently does not work if `swap` is enabled. The reason for this is the peer lock introduced in #2051. In this PR accounting was split into two parts `Validate` and `Apply`. `Validate` computes the cost and checks if it would allow the call and `Apply` applies the actual balance change if the request was successfully sent or handled. A peer lock was introduced to prevent another request from interfering with accounting between those two calls (imho this lock is already a bad idea because it prevents concurrent handling of messages, also it wouldn't help if there were multiple incentivised protocols).

The same lock is acquired when receiving a message and when sending one. When `retrieval` sends a message during its message handler, this causes a deadlock.

**Comment by ralph-pichler** [comment]
I think we should just remove that lock. While it does mean that an `Apply` can fail after a successful `Validate`, the damage caused by this is quite low and should be covered by the tolerance in the thresholds. All the data access is already protected by other locks.

**Comment by Eknir** [comment]
Thanks for making the issue!

In the Beehive, you showed that removing the lock solves the problem, so I think we should proceed with this. 

With regards to the possibility that `Apply` does not work after `Validate`... We should instantiate metrics to count how often this happens. If it appears to happen often in a live network, we obviously need to do something about this, but I agree that for now, there is no reason why we have to worry about it.

It shows, IMO, that our testing framework is not ready for Swarm to be incentivized by default. We need to work on this.
