### ISSUE TITLE
calibrate ideal wait time for chunk re-retrieval

### ISSUE THREAD

**Issue by santicomp2014** [ethersphere/swarm#2172]
When a chunk is not retreived in `netstore` it invokes the `recoveryCallback` and wait for 500 ms 
and tries to `RemoteFetch` the reupload chunk.

This is related to #2171 for monitoring the chunk reuploaded.

The timeout should be calibrated accordingly, to guarantee the chunk was reuploaded without spending too much deadtime.

**Comment by mortelli** [comment]
we might also want to look into the timeout for the recovery feed query while we're at it

**Comment by mortelli** [comment]
Closing, since we are returning error code `402` rather than retrying the fetch within the scope of the original get.
