### ISSUE TITLE
add publisher info when using gateway

### ISSUE THREAD

**Issue by santicomp2014** [ethersphere/swarm#2180]
The Manifest contains the publisher address, currently the `swarm up ` contains a flag `swarm up --publisher`

When the upload is done via the gateway, there is no option to specify this information.

Thus a dialog box or some other UI interfaces is needed to add the publisher when uploading a file

**Comment by mortelli** [comment]
we are no longer working with manifest publishers, so i'm closing this.

we can re-open it if we later go back to the manifest implementation.
