### ISSUE TITLE
Swap with no chequebook contract

### ISSUE THREAD

**Issue by gbalint** [ethersphere/swarm#219]
Let's make swap work without chequebook contract, so people can start to use swarm without having any ethers.
If the node provides an account address instead of a chequebook contract let's just send ether there directly

**Comment by cobordism** [comment]
We should allow a hybrid network of swap and no-swap. 

During the testing period, some nodes can use swap (on rinkeby for example) but would still connect with other nodes that do not have swap enabled at all.

...regardless of whether the swap peers use a chequebook or another form of payment between them. (they could conceivably also be using separate blockchains entirely in future).

**Comment by holisticode** [comment]
@homotopycolimit this may be difficult if we implement it as devp2p protocol. If the protocol won't match, default behavior is to drop the peer.

Maybe we can introduce a temporary hack for the time being.
