### ISSUE TITLE
pinned content disappears when gc is triggered multiple times

### ISSUE THREAD

**Issue by santicomp2014** [ethersphere/swarm#2195]
When doing the global pinning test, a bug was found in the local pinning, there are pinned chunks that are being garbage collected when multiple GC is run.

This can be verified by
- uploading a chunk/pinning it
- downloading it (works ok)
- upload random chunks multiple times the store capacity (500 chunks) to flush all chunks with GC
- try to download the chunk it can fail if the GC is run multiple times (40000 chunks)

This should be tested by pinning once the content, and also by pinning multiple times the same chunk and repeating the test.

After the first run of the Garbage collection, the pinned chunk is removed from `gcExcludeIndex`
So the next time the GC is run it will be deleted from the chunks.

**Comment by Eknir** [comment]
@jmozah , just for you. I know you are also working on it in Bee
