### ISSUE TITLE
Negotiate on chunk price in link

### ISSUE THREAD

**Issue by gbalint** [ethersphere/swarm#223]
Upon connection nodes should agree on a swap chunk price
Minimal implementation: offer prices, if it is the same, connect, otherwise do not connect.
Use a default price

**Comment by holisticode** [comment]
I wonder though - that should result in different prices between different nodes? Is that a problem at all?

**Comment by holisticode** [comment]
I also believe there should be a basic documentation explaining how the swap accounting should work (e.g. what is written in this issue, that is will be accounted in ETH, ...)
