### ISSUE TITLE
Syncer in mock storage mode

### ISSUE THREAD

**Issue by gbalint** [ethersphere/swarm#226]
Allow syncer to operate in mock storage mode, i.e., no need to pass the chunk data

Chunk validity check should be abstracted (different for content chunk, resource chunk, test-mock-storage): https://github.com/ethersphere/go-ethereum/issues/263

Syncer tests should pass, see: https://github.com/ethersphere/go-ethereum/issues/242

**Comment by zelig** [comment]
this should be spelt out again properly as part of #971 etc
