### ISSUE TITLE
Adapt DBStore export/import to network rewrite

### ISSUE THREAD

**Issue by gbalint** [ethersphere/swarm#231]
Make sure export/import in dbstore works in swarm-network-rewrite and includes everything
Check if dump, reindex, cleanup removed
This should be ported from master
There was a merge: https://github.com/ethersphere/go-ethereum/commit/95d01cb354c57013025a7fa43fe05d9ce22c936c
But it doesn't necessarily include everything, please investigate

**Comment by nonsense** [comment]
It might make sense to first finish https://github.com/ethersphere/go-ethereum/issues/236, before we fix this issue. At the moment generating chunks on `master` and trying to export them on `swarm-network-rewrite` doesn't work, but this is expected due to the major refactor.

```
WARN [03-01|16:09:30] Chunk 00ff7e58fa92fd9a9fda3f72e5acd11524ba9f70b69face482f7c9603104f98375 found but could not be accessed: leveldb: not found
WARN [03-01|16:09:30] Chunk 00ffdcf51f6ea7ed778f3413752f4e77c32086432069543dd0d6643affd16040a9 found but could not be accessed: leveldb: not found
INFO [03-01|16:09:30] successfully exported 0 chunks
```

**Comment by nonsense** [comment]
I tried again to `export` and `import` chunks, and it seems to work. We are still getting quite a few warnings about chunks that are found, but could not be accessed, and I am still not sure if this is a problem. I continue to investigate how exactly this is supposed to behave.

**Comment by zelig** [comment]
was this postponed? @nonsense @gbalint this is needed for rewrite

**Comment by gbalint** [comment]
Yes, @nonsense just talked about this on today's standup that he is picking it up as a next task

**Comment by nonsense** [comment]
I am a bit lost with this one. Can we define how this is supposed to work?

Reading from `swarm db --help` I see the following:
```
COMMANDS:
     export  export a local chunk database as a tar archive (use - to send to stdout)
     import  import chunks from a tar archive into a local chunk database (use - to read from stdin)
```

However when we actually try to invoke `export` or `import` we must also provide a `basekey` which is used as part of the distance function at:
```
// TODO: Instead of passing the distance function, just pass the address from which distances are calculated
// to avoid the appearance of a pluggable distance metric and opportunities of bugs associated with providing
// a function different from the one that is actually used.
func NewLDBStore(path string, hash SwarmHasher, capacity uint64, po func(Key) uint8) (s *LDBStore, err error) {
```

Currently when we trigger an export, if the local chunk database is ~50mb, the export contains chunks amounting to only ~500kb.

I am trying to understand all of `LDBStore` at the moment, but documentation is scarce and I am not sure what is the desired functionality for these commands.

cc @janos @zelig @gbalint
