### ISSUE TITLE
Simulation test for chunk retrieval

### ISSUE THREAD

**Issue by gbalint** [ethersphere/swarm#232]
This issue is dependent on https://github.com/ethersphere/go-ethereum/issues/242 and https://github.com/ethersphere/go-ethereum/issues/324

After the syncing tests are done, add extra benchmarking for retrieval.

Details:

There should be a healthy kademlia network.
Nodes should randomly generate chunks and other nodes should retrieve them.
It should check for each chunk that after every 100ms how many nodes were able to retrieve that chunk.
Do it with and without syncing.
With syncing create stats:
- for every PO of uploader and requestor how much time it takes to retrieve the chunks

With random uploads and downloads we should generate a table of retrieval times based on proximities.

This test should use the mock storage.

**Comment by holisticode** [comment]
Benchmarking will be postponed as of decision standup 6th April
