### ISSUE TITLE
Integrate new syncer into swarm.go

### ISSUE THREAD

**Issue by gbalint** [ethersphere/swarm#236]
When we start a swarm node it should use the new syncer.
When node A connects to node B, it should subscribe to sync bin PO(B,A) if B is not among the n nearest neighbours. Otherwise, A should subscribe to each bin PO(B,A)<=B<=maxproxbin

**Comment by zelig** [comment]
fixed by @nolash in https://github.com/ethersphere/go-ethereum/commit/79abcac95e865a9516dc8c9f39ec2777f558615b and in https://github.com/ethersphere/go-ethereum/commit/109426fea9b5186ac56063eaa52ee682aac5f898
