### ISSUE TITLE
Http status api endpoint

### ISSUE THREAD

**Issue by gbalint** [ethersphere/swarm#243]
This is an endpoint to show node state and configuration information

Things to include:
- hash of the node
- sync status
- info about kademlia
- connected peers
- disk usage (real/max)

This meant to be a backend API call, it should return a JSON

**Comment by holisticode** [comment]
I guess this would then be the backend for the status page? https://github.com/ethersphere/go-ethereum/issues/158

**Comment by gbalint** [comment]
@holisticode yes, i also added this info to the description of that issue
