### ISSUE TITLE
Http disk usage GET endpoint

### ISSUE THREAD

**Issue by gbalint** [ethersphere/swarm#244]
This is an endpoint to show max and actual disk usage
Return a json with the information

**Comment by acud** [comment]
what happens on systems with multiple volumes? do we transparently aggregate these readings or we expose the fact that different harddrives have different usage stats?

maybe it would be worthwhile to consider the fact that we should show disk usage for the disk that the swarm node is running on (e.g.: disk usage for the disk that `datadir` is on)

**Comment by zelig** [comment]
@elad-nach possible misunderstanding here. we report numbers through db store only how many chunks stored and what is set as dbStoreCapacity

**Comment by elad-nach** [comment]
@zelig, understood.

what's your standpoint on including a dependency to some sort of a REST framework such as Gin/Web.go/Gorilla? Would be good to make a step forward to standardise API responses and routing, this will facilitate faster development and integration in the future. 

This however depends on how thick the API is planned to be in the future. 
If it's just a few API endpoints on the roadmap - I'll stick to parsing routes manually (or add a simple way of maintaining and keeping track over routes and controllers), however if there's a lot more planned I'd highly advise for integrating another framework (the leaner the better).

Let me know your thoughts.
