### ISSUE TITLE
Test for persisted state

### ISSUE THREAD

**Issue by gbalint** [ethersphere/swarm#262]
There should be a test in discovery to see if the persisted peer set (1) is found and loaded (2) bootstraps healthy kademlia without any connections (3) benchmark the reduction of time reaching health

**Comment by acud** [comment]
@gbalint was this already done?

**Comment by gbalint** [comment]
@justelad I think it is mostly done, except 3)

**Comment by gbalint** [comment]
@justelad nobody worked on this since your contrbution in Vienna
