### ISSUE TITLE
Fix flaky `TestHTTPNodeRPC` test

### ISSUE THREAD

**Issue by nonsense** [ethersphere/swarm#269]
Sometimes the test fails with a timeout of 10sec.

`go test ./p2p/simulations/... -run TestHTTPNodeRPC`

**Comment by gbalint** [comment]
@nonsense Is this still valid?

**Comment by nonsense** [comment]
probably not, as this test is enabled, and we haven't see this in a while.

**Comment by nonsense** [comment]
Still happening on `master`.

```
--- FAIL: TestHTTPNodeRPC (10.10s)
    http_test.go:594: context deadline exceeded
FAIL
coverage: 65.9% of statements
FAIL	github.com/ethereum/go-ethereum/p2p/simulations	10.851s
```
