### ISSUE TITLE
Test cluster requirements

### ISSUE THREAD

**Issue by nonsense** [ethersphere/swarm#309]
It would be good to gather the requirements we have for a `test` cluster, because it is apparent that we have different expectations on its functionality.

I suggest we organise a call, where we discuss whats feasible in the short and long term.

For example we have to answer the following questions:
1. What is the limit of nodes/machines and swarm containers that we want to support? Currently we have limits on AWS and Azure, which we have no control over.
2. How often do we want to be able to re-size this cluster? Should individual developers be able to re-size this cluster?
3. What kind of security we want in terms of persistence? Do we want backups/external disks for it, or is it fine to have data stored on local VM disks?
4. Which cloud should be used for this cluster - Azure or AWS?
5. How long should it take to provision a new test cluster? 10min vs 2 hours vs 4 hours? We should all have an understanding of how long it takes to provision new hardware on the different clouds.
6. How "close" must the test cluster be to a local environment? Ideally we should have a similar development environment locally, so that we can easily transition from one environment to another.
7. What is our budget for spinning up test clusters?

These are some of the questions I think we should answer before we move forward.

cc @gbalint @zelig @homotopycolimit

**Comment by gbalint** [comment]
@nonsense After having an open test cluster can you tell which points are still valid questions?

**Comment by nonsense** [comment]
All of the questions are still valid. Even though our clusters are currently on Azure, 5 and 4 are coupled, so if we want very fast provisioning, we will have to move to AWS.

**Comment by nonsense** [comment]
Closing since we have moved to a k8s environment on AWS.
