### ISSUE TITLE
Increase memstore cache capacity

### ISSUE THREAD

**Issue by nonsense** [ethersphere/swarm#315]
At the moment memstore's cache capacity is too low. We should increase it and make sure it works.

With the current capacity, it is not possible to upload our swarm-home website, because we trigger memstore purge. Increasing the capacity solved the problem.

**Comment by gbalint** [comment]
Investigate whether we really need the capacity, or it is just the lack of cleaning up.

**Comment by nonsense** [comment]
Addessed by https://github.com/ethersphere/go-ethereum/pull/336 - we might need to adjust the size of the cache as I think it is way too small currently, but we need proper benchmarks for that. Let's leave it as is, until it starts creating problems.
