### ISSUE TITLE
swarm/pss: Circumvent deduplication and persisting messages by changing expiry entry

### ISSUE THREAD

**Issue by nolash** [ethersphere/swarm#321]
There is an expiry-value as part of the unencrypted `PssMsg` header. This enables a sender node to create two messages with identical payload that will pass through the deduplication filter.

That's probably not a problem.

However, any relaying node could change the expiry value of a PssMsg. Thus the hash of the message (used to keep track of whether we've seen it before) will be different. So there is a way for malicious nodes to supress the deduplication mechanism.

This could be a problem.

Do we need to care for this?

For asymmetrically encrypted messages I guess we could sign the header, and check if the payload matches that signature. But for symmetrically encrypted messages we don't have that luxury. That is, we could always encrypt the header symmetrically so the receiving node who can decrypt the message can determine whether its a duplicate, but it doesn't stop the extra traffic the spoof would generate.

Also, it is be possible for relayers to replace the header with a previously seen expiry, in which case subsequent messages with identical payload could be surpressed.

**Comment by zelig** [comment]
@nolash ?

**Comment by nolash** [comment]
Closed due to @nolash trying to create problems out of thin air.
