### ISSUE TITLE
panic: nil in MemStore.removeOldest

### ISSUE THREAD

**Issue by 4h0q** [ethersphere/swarm#342]
Hi there,

I've bumped into the following panic shortly after running a Swarm node.

OS & Version: OSX 10.13
Commit hash : `166c3e7e5be09e1452df92137ca2fd1b7de71bab` (swarm-network-rewrite branch)

#### Expected behaviour
Swarm node runs without crashing.

#### Actual behaviour
Swarm node crashes shortly after being run

#### Steps to reproduce the behaviour
1. Run a Swarm Node with PSS enabled 
2. Connect other nodes to the node
3. Starting sending PSS messages through the network

#### Backtrace

````
panic: nil

goroutine 9 [running]:
client/vendor/github.com/ethereum/go-ethereum/swarm/storage.(*MemStore).removeOldest(0xc420244100)
	/Users/4h0q/go/src/client/vendor/github.com/ethereum/go-ethereum/swarm/storage/memstore.go:291 +0x63c
client/vendor/github.com/ethereum/go-ethereum/swarm/storage.(*MemStore).Put(0xc420244100, 0xc421c81c20)
	/Users/4h0q/go/src/client/vendor/github.com/ethereum/go-ethereum/swarm/storage/memstore.go:155 +0x8a4
client/vendor/github.com/ethereum/go-ethereum/swarm/storage.(*LocalStore).Put(0xc4201daee0, 0xc4216ed500)
	/Users/4h0q/go/src/client/vendor/github.com/ethereum/go-ethereum/swarm/storage/localstore.go:100 +0x225
client/vendor/github.com/ethereum/go-ethereum/swarm/storage.(*DBAPI).Put(0xc4200c7150, 0xc4216ed500)
	/Users/4h0q/go/src/client/vendor/github.com/ethereum/go-ethereum/swarm/storage/dbapi.go:51 +0x39
client/vendor/github.com/ethereum/go-ethereum/swarm/network/stream.(*Delivery).processReceivedChunks(0xc4203f08d0)
	/Users/4h0q/go/src/client/vendor/github.com/ethereum/go-ethereum/swarm/network/stream/delivery.go:209 +0x207
created by client/vendor/github.com/ethereum/go-ethereum/swarm/network/stream.NewDelivery
	/Users/4h0q/go/src/client/vendor/github.com/ethereum/go-ethereum/swarm/network/stream/delivery.go:50 +0xbe
````

**Comment by nolash** [comment]
@4h0q thanks, could you please post a longer backtrace please? The lines you posted are not relevant to `pss`

**Comment by nonsense** [comment]
@nolash I hit the same bug while running integration tests for upload and sync. This could possibly be triggered due to PSS storing messages through the DPA in the ChunkStore?

Anyway, this is not a PSS bug, but rather a MemStore one, and we should look into it. I will close the other ticket as duplicate.

**Comment by nolash** [comment]
@nonsense cool. DPA will be gone fra pss in a bit anyway, too

**Comment by nonsense** [comment]
@4h0q this should be fixed now. Let me know if you still have similar issues.
