### ISSUE TITLE
Check with Travis how we can speed up our builds

### ISSUE THREAD

**Issue by nonsense** [ethersphere/swarm#365]
Assigning this to @gbalint as he said he will follow up with contacting Travis to see how much it would cost to speed our builds and whether we can do anything about that.

**Comment by gbalint** [comment]
Status: I sent out an email, waiting for a reply

**Comment by gbalint** [comment]
I received an answer:
"It is indeed possible to increase the number of jobs your organization can run for its open source projects.

The normal, free package gives you five concurrent jobs (which equals five concurrent workers, so to speak).

Beyond that, the next step up includes 10 extra concurrent jobs, effectively raising the limit to 15, for $500/month, paid annually and in advance.

Do you need more options, and is this something you'd generally like to proceed with?"

**Comment by gbalint** [comment]
@nonsense After we merge `swarm-network-rewrite` to `master` our PR builds will run on the ethereum organization, so maybe it doesn't make sense to upgrade `ethersphere`?

**Comment by nonsense** [comment]
@gbalint good point, once our PRs run on `ethereum`, we won't have to scale the `ethersphere` organisation. Maybe it is best to postpone this decision until we merge, and see how our workflow changes then?

**Comment by gbalint** [comment]
@nonsense I agree, let's close this for now, we can reopen it if the problem persists somehow.

**Comment by gbalint** [comment]
@nonsense IMHO this issue can be reopened, because we still use our fork for PR-s.
I have just put this in today's roundtable agenda.

**Comment by nonsense** [comment]
We have sped up Travis a lot recently, so closing this.
