### ISSUE TITLE
Improve Store and Chunk interfaces

### ISSUE THREAD

**Issue by nonsense** [ethersphere/swarm#391]
At the moment we don't have a good interface for inserting chunks to various `ChunkStore` implementations. Our tests generally rely in synchronous insertion (just as some part of the production code), but the interface does not support that.

Discuss and refactor the interface of `ChunkStore`, `LDBStore`, etc. and refactor tests so that they use a common implementation.

See:

1. swarm/storage/common_test.go ; line 61
```
func mputChunks(store ChunkStore, processors int, n int, chunksize int, hash hash.Hash) (hs []Key) {
```

2. swarm/storage/localstore_test.go ; line 43
```
func putChunks(store *LocalStore, chunks ...*Chunk) {
```

3. swarm/storage/ldbstore_test.go

**Comment by gbalint** [comment]
@nonsense can you agree that maybe we can close this issue? We have to create smaller cards for the actual refactor itself

**Comment by nonsense** [comment]
This is not really about the Chunk refactor, but the way we write tests. They are indeed coupled, but I think this is quite fine-grained and I haven't seen another ticket which describes this problem.

Basically this is about refactoring the TEST code, not the actual Chunk interface.
