### ISSUE TITLE
Create an open test cluster

### ISSUE THREAD

**Issue by gbalint** [ethersphere/swarm#395]
We need a test cluster which is not isolated and people can connect to it from the outside

**Comment by holisticode** [comment]
I agree. In "conventional" deployments, usually for bigger projects you have a prod environment, a staging and a dev environment, so three envs, in order to address production, (public) testing, and (integration) development

**Comment by nonsense** [comment]
duplicate of https://github.com/ethersphere/go-ethereum/issues/394
