### ISSUE TITLE
Create a PR with the non-swarm changes of swarm-network-rewrite

### ISSUE THREAD

**Issue by gbalint** [ethersphere/swarm#419]
https://github.com/ethersphere/go-ethereum/pull/171 is a huge PR. Let's separate the non-swarm parts, submit them to `ethereum/go-ethereum`, and then after merging this we will be able to create a huge, but at least swarm-only PR to merge the rest

First you can try it on `ethersphere/master` to see if travis is green and everything is ok

**Comment by acud** [comment]
taking care of vendoring now

**Comment by acud** [comment]
vendoring PR on main eth repo is good to go.
the other changes are still pending review
