### ISSUE TITLE
Add HTTPS to *.swarm-gateways.net

### ISSUE THREAD

**Issue by nonsense** [ethersphere/swarm#421]
- [x] testing.swarm-gateways.net
- [x] open.swarm-gateways.net
- [x] swarm-gateways.net

For now I will leave HTTP on, but maybe later we might want to have all HTTP redirect to HTTPS by default.

**Comment by gbalint** [comment]
Fixed in https://github.com/ethersphere/go-ethereum/pull/424

**Comment by nonsense** [comment]
This is not really fixed in #424 and we still don't have HTTPS on the production gateway.

**Comment by gbalint** [comment]
@nonsense my bad, my mind just grepped for "swarm-gateways.net"

**Comment by cobordism** [comment]
Shall we add an automatic redirect from http to https for the gateway?

**Comment by nonsense** [comment]
I had it added, but now I am disabling it, because it creates issues. Somehow I misconfigured it and have to see what's wrong with it.
