### ISSUE TITLE
CLI cleanup for 0.3 release

### ISSUE THREAD

**Issue by cobordism** [ethersphere/swarm#426]
The CLI interface is a little clunky and should be cleaned up for the 0.3 release. I am collecting points as I am writing up the documentation.

**Entries marked with DOC:** 
Things I have written to the documentation that is not yet true. Either the documentation has to change again, or, as I suggest, we should implement the change.

**Entries marked with WISH:**
Things that I believe would make go-swarm easier to use and would make documentation easier to write but has not yet been written to the docs.

- [ ] DOC: the binary is called go-swarm and it is located in /cmd/go-swarm in the codebase.
- [ ] DOC: Whenever there is a key in the swarm data dir, the `go-swarm` command should not require the `--bzzaccount` flag. If there are several keys in the datadir, the client should give a helpful error message like "multiple bzz accounts found a, b, c, d, please specify which account to use with --bzzaccount ADDRESS"  or sth like that.
- [ ] WISH: As above, when there are no bzz accounts in use, but swarm finds accounts in the geth datadir, it should offer to use one of those.
- [ ] WISH: Maybe add `go-swarm down` dual to `go-swarm up`. It should simply be a wrapper for curl?
- [ ] WISH: Don't force strict order on CLI flags. Why should it be `go-swarm --defaultpath /path/to/file --recursive up /path/to/`? Why can't I start with `go-swarm up`? Why can't I add the default path at the end? 
- [ ] WISH: We need a `go-swarm mount` command. Or `go-swarm fs` accepting `mount`, `unmount` and `list`.

**Comment by cobordism** [comment]
Specifically the fixed order of CLI flags is annoying.

I regularly find myself thinking: does --bzzapi come before or after `up`? Does --defaultpath commute with --recursive and do they come before or after the `up`? 

this is not good.

**Comment by lmars** [comment]
@homotopycolimit on renaming the binary to `go-swarm`, has that decision been made now? I thought the jury was still out (see https://github.com/ethersphere/go-ethereum/issues/191).

I still vote for the binary being called `swarm` and the deb package `ethereum-swarm` (to differentiate from things like [Docker Swarm](https://docs.docker.com/engine/swarm/) and [this swarm](https://github.com/torognes/swarm) which has the [`swarm` deb package](https://packages.ubuntu.com/xenial/swarm)).

**Comment by cobordism** [comment]
If it's go-swarm in the doc, then we can change it at the end with a simple search-and-replace.
If it's called swarm, we cannot.
