### ISSUE TITLE
renew domains on namecheap

### ISSUE THREAD

**Issue by nonsense** [ethersphere/swarm#436]
swarm-gateways.net is about to expire on May 10th.

we should renew it.

cc @homotopycolimit

**Comment by cobordism** [comment]
@zelig let's move them away from namecheap to a registrar with proper 2fa support.
Then we can collectively and securely manage the DNS.

..perhaps a topic for SOS2018?

**Comment by nonsense** [comment]
@homotopycolimit I am going to close this as domains have been renewed. Let's create another issue if we decide to enable 2FA and move them away, etc.
