### ISSUE TITLE
Add a `swarm down` command that is dual to `swarm up`

### ISSUE THREAD

**Issue by cobordism** [ethersphere/swarm#439]
I suggest we add `swarm down` to the CLI interface.

It can be just a simple wrapper for `curl`.

**Comment by lmars** [comment]
@homotopycolimit no need to wrap curl, just use the Swarm client `DownloadXXX` methods:

https://godoc.org/github.com/ethereum/go-ethereum/swarm/api/client#Client.Download

**Comment by cobordism** [comment]
whatever is easiest, I suppose

**Comment by zelig** [comment]
@homotopycolimit there was already an issue for this https://github.com/ethersphere/go-ethereum/issues/320
