### ISSUE TITLE
Don't require --bzzaccount if there is a key already in swarm datadir.

### ISSUE THREAD

**Issue by cobordism** [ethersphere/swarm#447]
The first time you run swarm, you need to specify a --bzzaccount.

By the second time, this should no longer be necessary.
I suggest:

- Whenever there is a key in the swarm data dir, the swarm command should use that one. 
- If there are several keys in the bzz datadir, the client should give a helpful error message like "Multiple bzz accounts found a, b, c, d, please specify which account to use with --bzzaccount ADDRESS" or sth like that.
- If there are no bzz accounts in the swarm datadir, but there are keys in geth keystore, then swarm should offer the keys in the geth keystore as a suggestion: "You must specify an ethereum account to use as your swarm id with --bzzaccount. Ethereum accounts found: a, b, c, d"

**Comment by nolash** [comment]
Should it also create a key if there are none in the keystore?

**Comment by cobordism** [comment]
key generation is part of  geth.

**Comment by gbalint** [comment]
@zelig doesn't agree with this, bzzaccount should be explicit in his opinion
