### ISSUE TITLE
Redesign swarm error pages

### ISSUE THREAD

**Issue by gbalint** [ethersphere/swarm#457]
Error pages should look better

**Comment by cobordism** [comment]
related: https://github.com/ethersphere/go-ethereum/issues/156

**Comment by holisticode** [comment]
As the "designer" of the current pages, I do acknowledge the current poor design, but I would like to ask here what would be a nice design and how we'd proceed on this issue. Is there a designer we can ask? Who will be the designer?  Will there be a process for approval? Should we just take chances and update the current pages?

**Comment by cobordism** [comment]
@holisticode No, you did a lot more than just design the current error pages. You created error pages entirely where there was no system in place beforehand :)

I think minimally we should just change the colours to not be orange and green. Maybe we can change the green to the lighter colour from https://open.swarm-gateways.net/bzz:/photoalbum.test/#1

Beyond that, we should probably discuss how to move forward on this issue (and other design issues more generally) in the round table discussion.

**Comment by zelig** [comment]
👍 
and yes pretty please someone change those colours ASAP

**Comment by Mistra** [comment]
I was mocking the page (inspired by [this](https://www.google.com/search?q=unicorn+404&client=firefox-b-ab&tbm=isch&source=iu&ictx=1&fir=1xMpLO-SoeyxQM%253A%252CR_6n7qgFqI_hmM%252C_&usg=__uJ1R-Aer7pGpcCSRcJ-IgxdvcVU%3D&sa=X&ved=0ahUKEwi65cHzntbbAhUFnRQKHU3VDf8Q9QEIMjAE#imgrc=1xMpLO-SoeyxQM:)).
I can also produce some other mocks, maybe a light one, or bigger fonts, no swarm or with full logo etc... also I intended to make an svg of that minimal logo (if it's needed).

Tell me what you think guys, if you like it I'll go on working on it.

![screenshot](https://user-images.githubusercontent.com/1072183/41482563-4682534e-70d6-11e8-8cb0-a7e91baa2162.png)

**Comment by holisticode** [comment]
Awesome for me. Just take note that resources (images, etc.) should be encoded as data blobs inside the page, as if there is an error with itself on swarm, the page should be self-serving

**Comment by Mistra** [comment]
@holisticode It's already encoded and embedded in the mock as image/png;base64

But for a final version I really wanted to use svg, and work with @media to scale on mobile.

**Comment by holisticode** [comment]
Maybe you could embed it as svg image still, without base64 encoding? https://css-tricks.com/probably-dont-base64-svg/

**Comment by holisticode** [comment]
@homotopycolimit requested some logo versions recently, so he may have some better quality ones.
As for the error text, that's coming from the code, and shouldn't be addressed by this issue. Maybe create a different issue?

@Mistra I suggest you just complete your version of the error page and submit a PR. Then we can continue commenting there.

**Comment by cobordism** [comment]
@holisticode ok new issue. done: https://github.com/ethersphere/go-ethereum/issues/726

**Comment by cooganb** [comment]
I'd be very interested in helping with landing page redesign
