### ISSUE TITLE
CLI flags should commute with commands

### ISSUE THREAD

**Issue by cobordism** [ethersphere/swarm#490]
Currently our swarm cli is very brittle, it only accepts flags in a specific order.
For example `swarm --recursive up` works but `swarm up --recursive` does not. `--defaultpath` also does not work after the `up`

The second one is better. Ideally, both should work or at least the "wrong" order should give a meaningful error message.

**Comment by justelad** [comment]
@homotopycolimit do we want to allow both or just one format?

**Comment by cobordism** [comment]
Related EPIC https://github.com/ethersphere/user-stories/issues/13
