### ISSUE TITLE
Encrypted http API freezes under some circumstances

### ISSUE THREAD

**Issue by nagydani** [ethersphere/swarm#501]
Under certain circumstances, POST requests to endpoint `bzz-raw://encrypt` freeze up until timeout. Similar requests to the unencrypted endpoint `bzz-raw://` do not freeze.

#### System information

Geth version: `1.8.2`
OS & Version: Linux, OSX (confirmed on both)
Commit hash : `d3d787e16c9935d1863894b199398915ebaf7e28` (but probably the same issue is present with later versions as well)

#### Expected behaviour

Posting a file longer than 4 kilobytes to `bzz-raw://encrypt` and then changing  something in it affecting only some chunks but not others and posting it again would simply produce two different references, just like doing the same to endpoint `bzz-raw://`

#### Actual behaviour

The first POST request behaves as expected, the second one freezes.

Recursive uploads using `swarm up` also hang on slightly modified files (not surprising).

#### Steps to reproduce the behaviour

Easiest to reproduce with text files. Take a text file, upload it, edit it, reupload it.

**Comment by gbalint** [comment]
We discussed with @nagydani that the issue was not in swarm, but in other components of the software environment
