### ISSUE TITLE
CLI help options are inaccessible. 

### ISSUE THREAD

**Issue by cobordism** [ethersphere/swarm#512]
I cannot access the `help` section for `swarm up`.

`help` is a subcommmand of swarm, yet `swarm help` just gives the same result as `swarm -h`.

I cannot access the specific help for `swarm up` using `swarm up help`, `swarm help up`, `swarm up --help`, `swarm --help up` or similar variants.

The same is true for the other subcommands of swarm.

**Comment by acud** [comment]
this seems to be a bug in the `cli` package.
i added a commit to the FUSE PR to fix this. resetting the local help template for the CLI commands seems to resolve this issue
