### ISSUE TITLE
leb.io/hashland/keccakpg dependency used by swarm-network-rewrite/swarm/multihash/sum.go not available

### ISSUE THREAD

**Issue by 4h0q** [ethersphere/swarm#520]
Hi there,

leb.io/hashland/keccakpg dependency used by swarm-network-rewrite/swarm/multihash/sum.go is not available, which prevents from building the project.

```
go get leb.io/hashland/keccakpg

package leb.io/hashland/keccakpg: unrecognized import path "leb.io/hashland/keccakpg" (https fetch: Get https://leb.io/hashland/keccakpg?go-get=1: dial tcp 104.131.190.18:443: connect: connection refused)
```

**Comment by nonsense** [comment]
@4h0q we have all dependencies vendored, no need to run `go get`. See `vendor/leb.io/hashland/keccakpg/`
