### ISSUE TITLE
swarm/pss: Steganography api

### ISSUE THREAD

**Issue by nolash** [ethersphere/swarm#546]
Pss uses Whisper envelopes, which can handle payloads hidden in padding. However, pss offers no api to control the contents of the padding field. A simple API could offer the possibility to write arbitrary data to it (which in turn could be data encrypted by some external agent), and also to pass the padding to the handler.

**Comment by randomshinichi** [comment]
Steganography is also something I'm interested in, so I'd like to take this issue if it's still open
