### ISSUE TITLE
swarm/storage: Mutable Resource persistence

### ISSUE THREAD

**Issue by nolash** [ethersphere/swarm#547]
Nodes that are publishers of mutable resource updates should have the possibility to sync all resources on startup. This means that the root chunk keys (and possibly the names) of these mutable resources should be saved on shutdown. 

The persistence should be optional, and a setting in the resource handler itself for the particular resource.

**Comment by JekaMas** [comment]
@nolash Could you help to understand the difference with https://github.com/ethersphere/go-ethereum/issues/568 ?

**Comment by nolash** [comment]
There's no difference, and they're both obsolete. Thanks :)
