### ISSUE TITLE
swarm/storage: Autosync of mutable resources

### ISSUE THREAD

**Issue by nolash** [ethersphere/swarm#569]
When requesting a mutable resource, a request is forwarded to the netstore to retrieve update chunks until the current one (or specified one) is found.

It should be possible to poll these resources automatically on certain time intervals as a background task in the node, to reduce potential network latency when the updates are requested by a client call. Some use cases are:

* When a node first starts up after shutdown it will automatically get up to date (analogous to "normal" swarm syncing. 
* If a node wants to operate on the full history of updates, the syncing could make sure that the relevant chunks persist in cache.

**Comment by jpeletier** [comment]
This is very interesting. I think the node should keep a list of the resources interesting to the user and keep them updated for some time
The last version is probably the most interesting one to keep handy.
I can work on this feature if you like.

**Comment by nolash** [comment]
Great! I would like that very much :)

Would you mind syncing up with @dleonard00 also? He is working on some extended MRU functionality, and this was on the task list he's working from, too.
