### ISSUE TITLE
suggestion: refactor `bzz-hash` scheme to HEAD on `bzz`

### ISSUE THREAD

**Issue by acud** [ethersphere/swarm#580]
currently, on the CLI interface `swarm hash` returns a hash of the content provided (either a single file or a directory) without uploading it to swarm.

on the http api, `bzz-hash` actually resolves an ens name into a hash.

the http `bzz-hash` should be moved into the `bzz` scheme and supported through a `HEAD` request. if a mutable resource is reached (for example, `HEAD bzz:/somename.eth`, while `somename.eth` points to a multihash) - the hash of the latest mutable resource should be returned.
optionally, a header `X-Swarm-Mutable-Resource: true` should be returned with the response.

current `bzz-hash` scheme could be supported through the normal `bzz` scheme with a `/hash` at the end of the locator or a header that will toggle the 'dry-run' mode.

**Comment by lmars** [comment]
@justelad this was discussed back in December (see [here](https://gist.github.com/gbalint/ce09ada0bebc38f3a8a3dd2ce6c6299f) for the outcome). The reason against using `HEAD` and HTTP headers is that it makes it less useful in browsers / HTML.

**Comment by acud** [comment]
as far as i know browsers have been given the eternal transcendent gift of being able to produce also `HEAD` requests alongside `GET`. as far as i know they can also add headers to http requests.
i just think we are shooting ourselves in the leg with building more schemes over http without using the tools that the protocol gives us.
in any case - the cli command has to be renamed pronto. i'd say just add a `--dry-run` flag to `swarm up` that will just out the hash to STDOUT. then `swarm hash` could be used to make ens resolutions.

**Comment by lmars** [comment]
> i just think we are shooting ourselves in the leg with building more schemes over http without using the tools that the protocol gives us.

I actually agree (see my comments in https://github.com/ethereum/go-ethereum/issues/15238 and https://github.com/ethersphere/go-ethereum/pull/141), but after a lengthy discussion we decided on using URL schemes for this type of functionality (reasoning in the gist I linked). So in terms of removing `bzz-hash` in favour of using `HEAD` / HTTP headers, I think the ship has sailed.

Now, as for `swarm hash`, its currently functionality is to generate a hash of a local file, e.g.:

```
$ swarm hash some/local/file
```

and it seems you want to expand it to print the hash of something that already exists in Swarm, for example:

```
$ swarm hash bzz://mysite.eth/some/remote/file
```

It seems to me like this functionality can be added by just treating the argument as a URI, if it has no scheme treat it like a local file, if it is `bzz://` then get the hash using `bzz-hash://`?

**Comment by cobordism** [comment]
these are all good comments. Just to add to the confusion, I'd point out that `swarm hash file` returns the root hash of `file`, while `swarm up file` returns the hash of a (dated / time-stamped) manifest containing `file` as its only entry.
We should probably clear that up too.

**Comment by acud** [comment]
@homotopycolimit so `swarm up file` would return a different hash every time?

**Comment by cobordism** [comment]
@justelad that's the current behaviour

**Comment by cobordism** [comment]
Maybe the best thing to do it to return more informative output?
```
Upload Successful.
Raw File Hash: HASH1
Manifest Hash: HASH2
URL: http://localhost:8500/bzz:/HASH2
```

**Comment by acud** [comment]
could be. although i'd be happy to have upload idempontent. why do we need to timestamp it? let's have the manifest just contain the file's date created and date modified, then we won't have varying timestamps

**Comment by lmars** [comment]
@justelad that is exactly what `swarm up` does, it uses the modified time of the file, so the hash only changes if the modified time changes:

```
$ echo data > file.txt

$ swarm up file.txt
a3fc501b9edd843a6fb8282476ac161c7704f2ba1952ef1c107f9b92228b97c6

$ swarm up file.txt
a3fc501b9edd843a6fb8282476ac161c7704f2ba1952ef1c107f9b92228b97c6

$ touch file.txt 

$ swarm up file.txt
af411ff414775c398946cff10682d4a190690d6faa395ff0f5e94e7da8fe3f2e
```

There is an open question as to whether we should just drop the last modified time (see #211), but it seems that is unrelated to this issue?

**Comment by acud** [comment]
closing this since this has already been discussed and decided
