### ISSUE TITLE
swarm/api: Remove bzz-resource scheme

### ISSUE THREAD

**Issue by nolash** [ethersphere/swarm#581]
`bzz-resource` is supposed to provide low-level access to raw resource update data. But the http layer isn't really intended for this type of usage.

Low-level operations on resource updates should be kept to direct go integration, optionally through rpc if needed.

**Comment by jpeletier** [comment]
Hmm, after going through the code, I would keep this API endpoint. It is very useful for the user to create, update and obtain information about resources they want to update, or as of #704, obtain the information to be signed. Can we reconsider this?

**Comment by nolash** [comment]
it's a keep
