### ISSUE TITLE
Fix golint warnings

### ISSUE THREAD

**Issue by gbalint** [ethersphere/swarm#582]
They were fixed in master, let's fix all of them in swarm-network-rewrite before merge
Let of `self` usage should be renamed

**Comment by dleonard00** [comment]
remaining scope for this is:

- swarm
- bmt
- pot
- cmd/swarm

**Comment by acud** [comment]
@dleonard00 can i close this?

**Comment by dleonard00** [comment]
@justelad This is a much larger issue with many pull requests that touch almost every file in swarm. So this is just getting started. Please do not close it.

**Comment by dleonard00** [comment]
Updating the scope of this from this morning's standup: Commenting all undocumented functions will be considered out of scope of this issue.
