### ISSUE TITLE
swarm/pss: Add flags byte(s) in PssMsg structure

### ISSUE THREAD

**Issue by nolash** [ethersphere/swarm#593]
Three initial usecases for this:

* Upon migrating to whisperv6, the aesnonce field will disappear from the envelope, and thus the detection mechanism for pss to determine what type of encryption is used. Since pss is not necessarily concerned with whisper's requirements for darkness, we would have some other way of marking the encryption type.

* To process symmetric encryption, pss uses brute force on a mru cache. This could be mitigated by a hint value to reduce the domain of search.

* pss raw now uses a zero-value topic. But we want to use topics with raw messages. Having a flag bit for this is a better solution.

**Comment by zelig** [comment]
fixed in https://github.com/ethersphere/go-ethereum/issues/593
