### ISSUE TITLE
Proof of custody

### ISSUE THREAD

**Issue by gbalint** [ethersphere/swarm#613]
smash/crash proof of custody http://swarm-gateways.net/bzz:/swarm/ethersphere/orange-papers/2/smash.pdf

**Comment by karsrhyder** [comment]
link not working

**Comment by xrn** [comment]
@karsrhyder probably this should be ok https://swarm-gateways.net/bzz:/theswarm.eth/ethersphere/orange-papers/2/smash.pdf
