### ISSUE TITLE
How long a hash is should not be hardcoded.

### ISSUE THREAD

**Issue by dleonard00** [ethersphere/swarm#632]
Found this as I've been going through the code, figured I'd surface it to be prioritized, rather than remaining buried in the code.

[Code Location](https://github.com/ethersphere/go-ethereum/blob/90b7fb7122eecc2bc9ed38b2c77111840b997b4f/swarm/api/uri.go#L30)
```
//matches hex swarm hashes
// TODO: this is bad, it should not be hardcoded how long is a hash
var hashMatcher = regexp.MustCompile("^([0-9A-Fa-f]{64})([0-9A-Fa-f]{64})?$")
```

@gbalint can you add any additional context to this, I see you added this comment [here.](https://github.com/ethersphere/go-ethereum/commit/ca6b22ee7c6c45122163c860b92bdebdc6896c82#diff-fef6841a0baf3f186b872a9c657947fcR43)

**Comment by gbalint** [comment]
Imho this is not nice code, but since hashing should not change at all (because it breaks all the content addresses), and it has a fixed length, it is a low priority issue.

**Comment by nolash** [comment]
@dleonard00 theres ongoing work on hash stuff here: https://github.com/ethersphere/go-ethereum/pull/601 it aims to put all things hash related in one place
