### ISSUE TITLE
swarm/pss: Remove Pss prefix from method names

### ISSUE THREAD

**Issue by nolash** [ethersphere/swarm#645]
Certain methods and types have `Pss` as a name prefix. This is redundant as the package domain ensures this disambiguation. They should be removed.

**Comment by randomshinichi** [comment]
I would like to do this issue, but I'm not sure exactly which ones you mean. There's not that many of them, which makes me think that perhaps this issue has already been done?

``
pss.go:pssPeer, PssParams
protocol.go: PssReadWriter
types.go: PssAddress, pssDigest, PssMsg
``

**Comment by nolash** [comment]
@gbalint @dleonard00 this was resolved already, wasn't it?

**Comment by zelig** [comment]
@nolash ? add to tasks or close

**Comment by nolash** [comment]
This is done afair. Closing.
