### ISSUE TITLE
Received chunk can not be found in DB

### ISSUE THREAD

**Issue by gbalint** [ethersphere/swarm#694]
This is the logline:
```
swarm_30401 ERROR[06-08|08:26:22.022386|swarm/network/stream/delivery.go:217] processReceivedChunks db error addr=058b2c494354c46733107c570aa1db9eee0d164155b15710f93bc0268c552de2 err="chunk not found" chunk=nil
```
This is logged here, and it should not happen at all: https://github.com/ethersphere/go-ethereum/blob/swarm-network-rewrite/swarm/network/stream/delivery.go#L217
Chunks should be in db after receiving them.

**Comment by cobordism** [comment]
I'm confused as to how this code works. 
You receive a chunk on the delivery receive channel and you have an error on line 217 if you cannot get the chunk from the db ... 

...and all of this happens _before_ the chunk is stored to the db on line 227

You say "Chunks should be in db after receiving them.", but then why is there the `d.db.Put(chunk)` ? Can you walk me through it?

**Comment by gbalint** [comment]
@homotopycolimit I agree this is hard to grasp, imho it will be better after the chunk refactor. When you receive a chunk it should be already in the database, because a request was made for it. In this case a Chunk object is already there, which represents the request itself, without the SData.
After receiving it we put it again with the SData filled in, but this is just an update in the DB, not a new item.

**Comment by gbalint** [comment]
Let's close this until we don't encounter it again
