### ISSUE TITLE
Diffrenece with swarm-guide

### ISSUE THREAD

**Issue by thomaskuntzz** [ethersphere/swarm#7]
Can someone tell me how this compares to [swarm-guide](https://github.com/ethersphere/swarm-guide)? Thanks!

**Comment by lmars** [comment]
The swarm guide is a [readthedocs repo](https://readthedocs.org/), here is the source: https://github.com/ethersphere/swarm-guide.

**Comment by thomaskuntzz** [comment]
But why are there two docs repos?

**Comment by lmars** [comment]
Good question! I don't have the answer, but I will say that the docs are in need of an update.

**Comment by thomaskuntzz** [comment]
I think so too, everything about swarm is scattered around so many places!
