### ISSUE TITLE
Storage benchmark tests are failing:

### ISSUE THREAD

**Issue by gbalint** [ethersphere/swarm#703]
Storage tests are failing:
```
--- FAIL: BenchmarkMemStoreGet_1_5k
	common_test.go:199: mget failed: chunk not found
--- FAIL: BenchmarkMemStoreGet_8_5k
	common_test.go:199: mget failed: chunk not found
FAIL
```
Lot of errors in logs:
```
ERROR[06-11|14:20:16.168137|swarm/storage/ldbstore.go:571] spawn batch write (9661 entries): unable to write batch: leveldb: closed
```

**Comment by nonsense** [comment]
It is not just the `get` tests, but also:

```
BenchmarkDbStorePut_1_5k-8                     1        1586891497 ns/op        479714672 B/op   2433979 allocs/op
BenchmarkDbStorePut_8_5k-8                     1        1644220840 ns/op        478856224 B/op   2433693 allocs/op
```

This looks wrong.

**Comment by nonsense** [comment]
The `MemStore` benchmarks are no longer applicable, as you cannot use the `MemStore` without the underlying `LDBStore` - `MemStore` has capacity only for a few items, and waits on the `LDBStore` for eviction. As soon as you hit this capacity (and you probably do with the benchmarks), then we will block on the `<-dbStoredC`, and we also won't be finding the chunk in the `MemStore` as it will be evicted.
