### ISSUE TITLE
Mutable Resources - use HTTP headers instead of paths to get previous versions.

### ISSUE THREAD

**Issue by cobordism** [ethersphere/swarm#710]
Currently to get an older version of a mutable resource, you append to the path. For example:
`curl -X GET http://localhost:8500/bzz-resource:/yourdomainname.eth/3/1` will return version 3.1

This is described here.
http://swarm-guide.readthedocs.io/en/docs-overhaul/mru.html#retrieving-a-specific-mutable-resource-version

The suggested change is to move all of this into HTTP request headers and leave the URLs untouched as that is only going to give us headaches when it clashes with paths in manifests.

**Comment by jpeletier** [comment]
But `bzz-resource:` is only to create and update resources. It does not have to interpret paths.
`bzz-resource:` does not care what your data really is or what the hash you have stored points to, that is left to the `bzz:` part to process. 
Am I missing something?

**Comment by cobordism** [comment]
hm... maybe I'm missing something.
