### ISSUE TITLE
TestFUSE hanging

### ISSUE THREAD

**Issue by janos** [ethersphere/swarm#745]
TestFUSE test hangs on Linux (and Travis CI). It happens on any subtest. This problem may not be related only to tests on Linux.

The fuse.test process:
- ends up in `disk sleep` state
- does not respond to SIGQUIT, so no stack trace is avaliable
- does not respond to SIGTERM
- exposing pprof over http in tests works until the persistent `disk sleep` state is reached, after that no http response is served by (pprof) http server
- running test with strace gives some insight on the internals, but need more investigation

I am attaching here the output of `strace -f go test -v -count 1 -timeout 1m github.com/ethereum/go-ethereum/swarm/fuse`.

[test.log.gz](https://github.com/ethersphere/go-ethereum/files/2133254/test.log.gz)

**Comment by zelig** [comment]
@janos status on this?

**Comment by janos** [comment]
This test is disabled as flaky. As it can be only debugged with strace, it needs more investigation that involves fuse connectivity or deeper understanding of its internals.
