### ISSUE TITLE
Modify ethereum-swarm deb package version

### ISSUE THREAD

**Issue by gbalint** [ethersphere/swarm#753]
Instead of using the geth version number let's use a swarm version (e.g. 0.3.0) + build number

**Comment by cobordism** [comment]
please also add comments to https://github.com/ethereum/go-ethereum/issues/17085 as appropriate

**Comment by nonsense** [comment]
I am afraid this is not as easy/possible as initially anticipated. We supply a version for the debian package only at one place - in the `deb.changelog` for the whole set of packages, on a `debMetadata` global level.

```
{{.Name}} ({{.VersionString}}) {{.Distro}}; urgency=low
```

Therefore it is not just a matter of modifying the build/ci.go which prepares the debian package configuration files, but also modifying the whole package setup.

So far this is a no go, as I am no sure how to do it. Will investigate further and see if there is a solution.

**Comment by nonsense** [comment]
Here is a description file that should make the comment above more clear:

```
$ cat ethereum-unstable_1.8.12+bionic.dsc
Format: 3.0 (native)
Source: ethereum-unstable
Binary: ethereum-unstable, abigen-unstable, bootnode-unstable, evm-unstable, geth-unstable, puppeth-unstable, rlpdump-unstable, swarm-unstable, wnode-unstable
Architecture: any
Version: 1.8.12+bionic
Maintainer: Ethereum Builds <fjl@ethereum.org>
Homepage: https://ethereum.org
Standards-Version: 3.9.5
Vcs-Browser: https://github.com/ethereum/go-ethereum
Vcs-Git: git://github.com/ethereum/go-ethereum.git
Build-Depends: debhelper (>= 8.0.0), golang-1.10
Package-List:
 abigen-unstable deb science extra arch=any
 bootnode-unstable deb science extra arch=any
 ethereum-unstable deb science extra arch=any
 evm-unstable deb science extra arch=any
 geth-unstable deb science extra arch=any
 puppeth-unstable deb science extra arch=any
 rlpdump-unstable deb science extra arch=any
 swarm-unstable deb science extra arch=any
 wnode-unstable deb science extra arch=any
Checksums-Sha1:
 f529544744da1c79800d978a04e5df3c2434bba4 7283008 ethereum-unstable_1.8.12+bionic.tar.xz
Checksums-Sha256:
 28cda7bf51b81a01ae85238a777e3b7ea136a74fe555a8e3c4e7f42278d8f17b 7283008 ethereum-unstable_1.8.12+bionic.tar.xz
Files:
 606b9db732519d04d5ce4c545c61490a 7283008 ethereum-unstable_1.8.12+bionic.tar.xz
```

**Comment by nonsense** [comment]
One solution would be to get `swarm` out of the `ethereum` package, and package it separately in a separate Travis job, as `ethereum-swarm` with its own version.

I don't see how we can have individual versions for the packages defined in the global `ethereum` debian source package.

If we split from the `ethereum` package and build `ethereum-swarm` separately, we could probably add `ethereum-swarm` under the `Build-Depends` dependencies, so that a version of Swarm gets installed if someone installs the `ethereum` package.

**Comment by nonsense** [comment]
@gbalint at the moment if you install `ethereum`, it installs all packages. What you are asking (and suggesting) is getting rid of swarm when someone installs `ethereum`, which although might be fine from a dependency perspective, I think is not what we want.

**Comment by gbalint** [comment]
@nonsense There are 3 levels in deb packages to suggest other packages: dependencies, suggestions and recommendations. Imho setting swarm as a dependency is abusing this feature, because swarm is not crucial for ethereum. See doc https://www.debian.org/doc/manuals/debian-faq/ch-pkg_basics.en.html#s-depends :
"Package A depends on Package B if B absolutely must be installed in order to run A."

However, suggestion or recommendation is really what we need:
"Package A recommends Package B, if the package maintainer judges that most users would not want A without also having the functionality provided by B."
"Package A suggests Package B if B contains files that are related to (and usually enhance) the functionality of A."

And apt-get by default installs recommendations and suggestions too (except if you set the --no-install-recommends flag), so most users will install swarm with ethereum anyway.

**Comment by nonsense** [comment]
@gbalint ok, makes sense. When we refactor this, we could use the proper sections.
