### ISSUE TITLE
swarm/api/http: improve test coverage

### ISSUE THREAD

**Issue by acud** [ethersphere/swarm#779]
in the `http` package, the following scenarios are not yet tested:
- [x] `GET /` with an explicit `Accept: text/html`
- [x] `GET /` with `Accept: application/json`
- [x] `GET /robots.txt`
- [x] `GET /path_that_doesn't_exist` - expect 404
- [x] `DELETE /bzz:/<resource>/path` 
- [x] `PUT/PATCH /bzz:/<resource>/path` - expect 405
- [x] `POST /bzz-raw:/`
- [x] `POST /bzz-raw:/encrypt`
- [x] `PUT /bzz-raw:/` - expect 405
- [x] `GET /bzz[-raw/hash/etc]:/<malformed swarm uri that breaks the parser>` - expect 400 with `invalid URI` message
- [x] `GET /bzz:/<address>` with `Accept: application/x-tar`
- [x] `POST /bzz:/` with `Content-Type: multipart/form-data` (!)

**Comment by randomshinichi** [comment]
May I do  this issue? I think I got the hang of how things are done in swarm/api/http/server_test.go
I assume the code already behaves as expected

**Comment by acud** [comment]
Hi @randomshinichi!
gladly! all contributions would be highly appreciated.
I already covered one of these as part of the branch I'm working on right now - `ethersphere/http-refactor-2.1`. 
If you could please just branch out of that branch instead of `develop` it would be very helpful.
You can also ping me on gitter if you need any help.
The code (should) indeed already behave this way

**Comment by randomshinichi** [comment]
GET /nonexistent_path actually returns 400, not 404

**Comment by randomshinichi** [comment]
- [x]    GET / with an explicit Accept: text/html
- [x]    GET / with Accept: application/json
- [x]    GET /robots.txt
- [x]    GET /path_that_doesn't_exist - expect 404 (but returned 400)
- [x]    GET /bzz[-raw/hash/etc]:/<malformed swarm uri that breaks the parser> - ex$
- [x]    GET /bzz:/<address> with Accept: application/-[x]-tar
- [x]    PUT/PATCH /bzz:/<resource>/path - expect 405
- [x]    DELETE /bzz:/<resource>/path
- [x]    POST /bzz-raw:/
- [x]    POST /bzz-raw:/encrypt
- [x]    PUT /bzz-raw:/ - expect 405
- [x]   POST /bzz:/ with Content-Type: multipart/form-data (!)
