### ISSUE TITLE
swarm cli / mru: Allow resource updates to take data from stdin

### ISSUE THREAD

**Issue by jpeletier** [ethersphere/swarm#781]
Modify the mru CLI to detect data on stdin for `resource create` and `resource update` so that it takes data from stdin to initialize or update a resource

**Comment by nolash** [comment]
I like it when the application auto-detects whether there's something on stdin or not, so you don't have to explicitly specify source via flag.

**Comment by jpeletier** [comment]
ok. noted.

**Comment by jpeletier** [comment]
Closed as duplicate of #800
