### ISSUE TITLE
swarm  search for index.html in the manifest by default

### ISSUE THREAD

**Issue by winsvega** [ethersphere/swarm#783]
Would be a better user experience if swarm would try to locate index.html in the manifest by default

**Comment by cobordism** [comment]
I think this is better handled by the uploading tools (to set index.html as the defaultpath).

but what I would like to see is a better error message for when no default is set. I'd like to see a bzz-list output in the error. 
see also: https://github.com/ethersphere/go-ethereum/issues/726
