### ISSUE TITLE
FUSE should not require --ipcpath

### ISSUE THREAD

**Issue by cobordism** [ethersphere/swarm#795]
Currently the command `swarm fs mount theswarm.eth mountpoint` will fail because `swarm fs` requires(!) the `--ipcpath` cli flag.

This should not be the case if swarm is running with the default ipc endpoint. If `--ipcpath` is not specified, it should simply be assumed the the ipcpath is DATDIR/bzzd.ipc

**Comment by zelig** [comment]
can i close this? @homotopycolimit @justelad ?

**Comment by acud** [comment]
this was not yet merged to upstream. @frncmx?

**Comment by cobordism** [comment]
it was merged to ethersphere but not to upstream.. so what needs to happen now?

**Comment by acud** [comment]
@homotopycolimit it wasn't merged to ethersphere. there was just a PR that was reviewed and @frncmx said he will reopen on upstream

**Comment by cobordism** [comment]
so we can close it here?

**Comment by acud** [comment]
hab geduld

**Comment by frncmx** [comment]
Picking this one up now. There was some missing doc updates, that's why it was not ready for a merge.
