### ISSUE TITLE
Twitter handle

### ISSUE THREAD

**Issue by nonsense** [ethersphere/swarm#810]
If we are to continue to use `ethersphere` twitter handle for Swarm communication, should we change the picture to the Swarm logo, so that people recognise Swarm when they see `ethersphere` ?

https://twitter.com/ethersphere

Let me know what you think.

@gbalint @homotopycolimit @zelig

**Comment by cobordism** [comment]
it's viktor's (@zelig)

**Comment by cobordism** [comment]
I would just really, really, really want to change "ΞTHΞЯSPHΞЯΞ"  to "Ethersphere"
I find abusing foreign alphabets like this seems juvenile and hard to take seriously. It's the digital equivalent of graffiti tagging.
:D

**Comment by nonsense** [comment]
I was thinking of a style similar to https://twitter.com/ethswarm

**Comment by cobordism** [comment]
woah! who is that?
Is that ours?

**Comment by nonsense** [comment]
Yes, just registered it. We can share it within the team, or I can remove it if we are not happy with it.

**Comment by nonsense** [comment]
It was decided that we are going to use @ethswarm from now on.
