### ISSUE TITLE
Swarm downloads page

### ISSUE THREAD

**Issue by nonsense** [ethersphere/swarm#811]
Once we merge https://github.com/ethereum/go-ethereum/pull/16988 and release next Swarm patch version 0.3.1, we should add a `Downloads` page to https://swarm.ethereum.org , similar to https://geth.ethereum.org/downloads/

Users should be able to easily:
- install Swarm by downloading a stable release from our website
- install Swarm for Ubuntu PPA
- compile latest `master` (unstable) or specific release commit (stable), a list of which we should maintain on our website, similar to https://geth.ethereum.org/downloads/

**Comment by cobordism** [comment]
- [ ] whishlist: notify swarm clients when an upgrade is available

**Comment by nonsense** [comment]
Addressed in https://github.com/ethersphere/swarm-home/pull/26

**Comment by nonsense** [comment]
@homotopycolimit closing this. Let's think about the notification on update as a separate issue.
