### ISSUE TITLE
start up swarm(CLI) with https 

### ISSUE THREAD

**Issue by linkcryptocoin** [ethersphere/swarm#818]
Hi there,

Not sure it is an issue. I was able to launch swarm(CLI) on "http: //mylink.net:5000". Everything works just fine for uploading the contents until we switched the site to "https". 

'https://linkgear.net/home/claim?id=5b5c6833226cba727c063163' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://linkgear.net:5000/bzz:/'. This request has been blocked; the content must be served over HTTPS."

Is there a way or parameter for us to launch swarm under the console/terminal with https? If there is an answer already, please simply redirect me.

Thank you,
Simon  
my email: linkgeardev@gmail.com

**Comment by cobordism** [comment]
How are you forwarding traffic to your swarm node?

On https://swarm-gateways.net we have an nginx proxy sitting between the front end and the Swarm nodes in the background. This way all external traffic is https while internally the cluster just uses Swarm's HTTP interface.
