### ISSUE TITLE
Add a version or commit to https://swarm-gateways.net/

### ISSUE THREAD

**Issue by nonsense** [ethersphere/swarm#822]
It should be clear to users what version our gateways is running. Just adding the commit/version to the footer would do the trick as a start I think.

**Comment by cobordism** [comment]
...any swarm node should give its version in the footer of the localhost:8500 output. yes? This is not a gateway question then but an http interface question

**Comment by nonsense** [comment]
Yes, every HTTP interface should have it in the footer I think.

I imagine in the future some operators might not want to disclose the version they are running, but for now that'd be useful information.

**Comment by nonsense** [comment]
swarm-gateways.net is always running the latest stable Swarm release.
