### ISSUE TITLE
swarm/api/http: correct leaf links when navigating with bzz-list

### ISSUE THREAD

**Issue by acud** [ethersphere/swarm#826]
using `bzz-list` to navigate manifests through the browser does not yield the correct links for viewing the leaf nodes.
example:

https://swarm-gateways.net/bzz-list:/theswarm.eth/Swarm_files/
`analytics.js` hyperlink shows up as 
`https://swarm-gateways.net/bzz-list:/theswarm.eth/Swarm_files/analytics.js`
instead of:
`https://swarm-gateways.net/bzz:/theswarm.eth/Swarm_files/analytics.js`

**Comment by cobordism** [comment]
while on the topic, bzz-list output should make it clear when a manifest has a default (no-name / empty path entry) and offer a clickable link here too.

c.f. https://github.com/ethersphere/go-ethereum/issues/156#issuecomment-397266916
