### ISSUE TITLE
snapshot_sync_test flaky

### ISSUE THREAD

**Issue by gbalint** [ethersphere/swarm#828]
See:
https://travis-ci.org/ethereum/go-ethereum/jobs/410232519
https://travis-ci.org/ethereum/go-ethereum/jobs/410415722

**Comment by janos** [comment]
Actually, from this logs it is not sure whether the snapshot tests are failing. A great number of warn messages are suggesting that, but in available travis logs, it can be seen that all of this log messages are printed in around 2 seconds. They are printed as the test before them had a failure.

Issues:
- TestDeliveryFromNodes fails, but it is addressed in https://github.com/ethereum/go-ethereum/pull/17299.
- Snapshot tests check is in tight loop printing warn messages very fast, this is addressed in the same PR.

Stream tests are still hanging, and for this to debug, `go test` requires the `-v` flag which is deeply wrapped in ci.go.
