### ISSUE TITLE
Retrieval doesn’t always work

### ISSUE THREAD

**Issue by gbalint** [ethersphere/swarm#844]
And also slow

**Comment by cobordism** [comment]
can you explain what you mean by "doesn't always work"?

**Comment by gbalint** [comment]
It just happens that you upload a file and can't retrieve from a different node. Maybe it is just slow syncing, I don't know. 
This issue can be filled with more exact descriptions of cases when retrieval failed. The goal is to work on making sure that retrieval works - because we can not really say that now with confidence.

**Comment by gbalint** [comment]
Do it in the chunk refactor code
