### ISSUE TITLE
Swap: accounting

### ISSUE THREAD

**Issue by holisticode** [ethersphere/swarm#845]
Make sure accounting with Swap works with the new network rewrite

* Accounting in ethers, not as chunks

**Comment by holisticode** [comment]
Replaces  https://github.com/ethersphere/go-ethereum/issues/222

**Comment by cobordism** [comment]
accounting should not be in "chunks" but in "bytes" anyway.

On the low level there should be accounting in bytes and then those bytes can be converted into some other "currency". 
On the one hand it is conceivable that we could have chunks of different size and on the other hand that in future we trade in other content (streams? PSS data?) than just plain chunks. 
Bytes seems to be the most logical unit of accounting.
