### ISSUE TITLE
cmd/swarm: implement home directory expansion

### ISSUE THREAD

**Issue by acud** [ethersphere/swarm#853]
when a user inputs a tilde `~` as a part of a path input on the CLI - the home directory does not automatically get expanded.
as a result users have to type in absolute paths to files and folders.
this should be handled by a simple function that will expand the home directory and thereafter could be used wherever path cli flags are used in order to normalise input.

**Comment by cobordism** [comment]
I thought ~ expansion was the job of the shell. After all, if I replace ~ with $HOME the shell expands this correctly.
but ok, by all means let's handle this on our side.
