### ISSUE TITLE
access control: create ACT sanity check scenario

### ISSUE THREAD

**Issue by acud** [ethersphere/swarm#856]
ACT scheme needs sanity checks just as we've written for the PK strategy.

So in the spirit of the unit tests that already exist, we need a test with a known set of 3 parties that both their public and private keys are known to us.
The scenario should also specify what should be the resulting lookup keys and access key decryption/encryption keys for each grantee.

**Comment by nagydani** [comment]
Three public/private key pairs, derived according to BIP-39 from the following seed phrase:
```
sunny science wrist intact lens file arch security kitten antique segment link
```
derivation path | public key | Ethereum address | private key
--------------- | ---------- | ---------------- | ---
`m/44'/60'/0'/0/0` | `02e6f8d5e28faaa899744972bb847b6eb805a160494690c9ee7197ae9f619181db` | `0xE8505879090351e00dd44807095352106eC7E56e` | `ec5541555f3bc6376788425e9d1a62f55a82901683fd7062c5eddcc373a73459`
`m/44'/60'/0'/0/1` | `0226f213613e843a413ad35b40f193910d26eb35f00154afcde9ded57479a6224a` | `0x7DEFd3C34972C6B6d19E53395a04B4fCd23A8617` | `70c7a73011aa56584a0009ab874794ee7e5652fd0c6911cd02f8b6267dd82d2d`
`m/44'/60'/0'/0/2` | `023794a98d7b07c13ddcb0b1df267b939f72512f3418916b58dc47bd1cd68cdd2e` | `0x2De543098fd6C4F8063c518C65E222239b0da031` | `83c12e2b8aa45dbaf041b37f8ea84d09b73be461e922070c9d3df7b1f796e3a5`

**Comment by acud** [comment]
Test outline:
Key 0 - Alice, Key 1 - Bob, Key 2 - Carol
Secret string to be transmitted: "open sesame"
Publisher: Alice
Grantees: Bob and Carol
Salt: generate random (can be generated randomly on each test run as with PK?)
Access Key: generate random

To be calculated (for Bob and Carol):
Session keys, lookup keys, access key encryption keys, encrypted access keys

Assumption - access key decryption keys should be the same for all parties?

**Comment by acud** [comment]
The shared secrets computed independently are
AB: 0xa85586744a1ddd56a7ed9f33fa24f40dd745b3a941be296a0d60e329dbdb896d
AC: 0x8c233c2444368fa54012652b643924946705be1d90f254b0a401ee747713058d

**Comment by acud** [comment]
@nagydani to date i have from you just the ECDH (see above - pasted from gitter).
would you like me to create a test/is it of any use to create a test with predefined encryption scheme steps that we would assert in a unit test? or do you trust the implementation to an extent in which you think a unit test is irrelevant? if so - i'll close this ticket and scratch the topic
