### ISSUE TITLE
Add configuration to disable ACT

### ISSUE THREAD

**Issue by gbalint** [ethersphere/swarm#865]
We will use this on the gateway to disable ACT
Let's have a fun error message :)

**Comment by acud** [comment]
@gbalint @zelig this is implemented in https://github.com/ethersphere/go-ethereum/pull/863/commits/51131c588184b4b11ec00598741243fb3c72bd54
can you please review? if i understand correctly this is what you meant with the implementation detail

**Comment by gbalint** [comment]
I had something different in my head, this only allows ACT on localhost, but imho it should be a configuration parameter if you allow it or not. Maybe you run your own swarm node on your server what you trust, and then you don't access it through localhost.
@zelig ?
