### ISSUE TITLE
manifest: manifest entry type to facilitate metadata

### ISSUE THREAD

**Issue by acud** [ethersphere/swarm#886]
we need a better concrete manifest entry type that will allow us to describe metadata entries better.
for example - with ACT the manifest entries are *hacked* into the manifest structure using `hash` and `path`.

this could also be used to create a more generalised manifest entry type implementation that could accommodate for future requirements of information that would be stored in the manifest

**Comment by cobordism** [comment]
closing in favour of https://github.com/ethersphere/go-ethereum/issues/878
