### ISSUE TITLE
cmd/swarm: `--bzzapi` help documentation is confusing

### ISSUE THREAD

**Issue by acud** [ethersphere/swarm#891]
the command documentation should include that this should not be used to set the listening endpoint when starting a local node, but is rather used in conjunction with `swarm up`/`swarm down`/... commands

**Comment by randomshinichi** [comment]
Is this still open? I'd like to work on it

**Comment by acud** [comment]
sure 👍 much appreciated

**Comment by acud** [comment]
no, i mean that the command description says `Swarm HTTP endpoint (default: "http://127.0.0.1:8500")`, but this can be confusing, since it can also infer which address swarm is listening on
