### ISSUE TITLE
cmd/swarm: swarm does not listen on port 80

### ISSUE THREAD

**Issue by acud** [ethersphere/swarm#892]
when starting swarm with `--bzzport 80`, swarm does not listen correctly on the supplied port. this, however, does not happen on higher port numbers.

**Comment by nonsense** [comment]
The TCP/IP port numbers below 1024 are special in that normal users are not allowed to run servers on them. https://www.w3.org/Daemon/User/Installation/PrivilegedPorts.html

However we are currently swallowing the error from `ListenAndServe` which should be fixed.
