### ISSUE TITLE
running `swarm up`  fails

### ISSUE THREAD

**Issue by yann300** [ethersphere/swarm#923]
#### System information

swarm/v0.3.3-89451f7c/linux-amd64/go1.10

#### Steps to reproduce the behaviour

running ` swarm --bzzapi http://localhost:8500 --defaultpath ./index.html --recursive up ./`
with  `swarm --bzzaccount <a>` running

(one file is 17mb)

got

#### Backtrace
```
panic: runtime error: comparing uncomparable type tar.headerError

goroutine 21 [running]:
net/http.(*Request).write(0xc42024ab00, 0x10563c0, 0xc42001c000, 0x0, 0xc420018060, 0xc42046c000, 0x10583a0, 0xc42017bf40)
	/usr/lib/go-1.10/src/net/http/request.go:624 +0x71b
net/http.(*persistConn).writeLoop(0xc4202446c0)
	/usr/lib/go-1.10/src/net/http/transport.go:1825 +0x1ea
created by net/http.(*Transport).dialConn
	/usr/lib/go-1.10/src/net/http/transport.go:1238 +0x97f
```

**Comment by nonsense** [comment]
@yann300 you don't have to specify `bzzapi` when you want to upload to your local node.

Haven't encountered this panic just yet, will see if I can reproduce.

**Comment by yann300** [comment]
I got it work after restarting computer... i could not reproduce afterward...
