### ISSUE TITLE
 Remote Denial-of-service using continuous SubscribeMsg packets in stream subprotocol

### ISSUE THREAD

**Issue by gbalint** [ethersphere/swarm#928]
Attack scenario | An attacker can continuously send SubscribeMsg packets with Stream.Name = "RETRIEVE_REQUEST" and different Stream.Key, which could force the victim node to 100% memory utilization
-- | --
Components | Swarm client version 0.3.2
Reproduction | Continuously send SubscribeMsg packets with Stream.Name = "RETRIEVE_REQUEST" and different Stream.Key

see https://docs.google.com/document/d/1Tw1vFnZzUT9JEK65SdXyS2U37_fVNgHoN2AO3MRtoGw/edit

**Comment by acud** [comment]
fixed on https://github.com/ethereum/go-ethereum/pull/17747
