### ISSUE TITLE
Connected swarm node deletes locally uploaded content

### ISSUE THREAD

**Issue by winsvega** [ethersphere/swarm#931]
How to reproduce:

- start a clean node
- upload a directory with multiple files and subdirectories with multiple files (a web site) 
- wait for 1 - 2 days running the node online

After running for a couple of days chunks are lost. and even reuploading the content again does not help.

**Comment by holisticode** [comment]
Thank you for submitting this.

You are probably aware that without incentive system, data may be garbage collected. Although 1-2 days seems rather short for chunks to not be retrievable already. 

In any case, reuploading should fix it.

**Comment by winsvega** [comment]
The issue is that data is stored on local node and uploaded on local node. So it is my node that dont store the data. Reuploading does not help

**Comment by nagydani** [comment]
I think, the issue also exists with isolated nodes. There seems to be a major regression afoot.

**Comment by nolash** [comment]
@winsvega

> Reuploading does not help

It is also not available in singleton mode immediately after re-uploading?

**Comment by winsvega** [comment]
Immediatly after reuploading it works for few seconds, but then chunks lost again. 
Daniel said that chunks appear to be missing even on offline node

**Comment by nonsense** [comment]
I am unable to reproduce this. I started a local node with `--store.size 10000`
I perform the following manual steps:
1. I upload multiple small files (.pdf), which I can retrieve.
2. I upload many large binaries, which trigger garbage collection, and .pdfs from 1. are no longer retrievable.
3. I re-upload the .pdfs from 1 and they are again retrievable.

**Comment by nonsense** [comment]
@winsvega @nagydani if you are able to reproduce this, could you please give a bit more information on how you do that, and what is the exact problem?

1. What is your `store.size` ?
2. How much data (as in MB) do you have in your `datadir`?
3. How big is the folder that you recursively upload (this website that @winsvega mentioned)
4. Do you trigger garbage collection at all?
5. On which `commit` is your node? Which version of Swarm are you running?

**Comment by winsvega** [comment]
I dont know. I just start a swarm node and thats it. on a recent patch it took about 1 week for this issue to happen. 

however the error log now looks differen: 
```
INFO [09-28|17:05:54.559] setting request host                     ruid=2472cc77 host=127.0.0.1:8500
ERROR[09-28|17:05:54.566] lazychunkreader.join                     key=1c39eed303c4fa2bf81769627682ef61730ce62f37eb7dc16abf98aebc6588e2 err="no peer found"
ERROR[09-28|17:05:54.567] lazychunkreader.readat.errc              err="chunk 131072-135168 not found; key: 1c39eed303c4fa2bf81769627682ef61730ce62f37eb7dc16abf98aebc6588e2"
ERROR[09-28|17:05:54.567] lazychunkreader.readat                   read=0 err="chunk 131072-135168 not found; key: 1c39eed303c4fa2bf81769627682ef61730ce62f37eb7dc16abf98aebc6588e2"
ERROR[09-28|17:05:54.567] lazychunkreader.join                     key=023827841a0e8f642da736a06580a3d61f80c5c18caa1d0e9f6a429ae497ec99 err="no peer found"

```

go-ethereum hash: `89451f7c382ad2185987ee369f16416f89c28a7d`
command I use to start the node: 
`nohup swarm --bzzaccount 5229521f6b0da6a37a89ab04986e90ed3dfe03f0 --password /home/admin/go-ethereum/build/bin/pass &` 
upload operation:
` swarm --recursive --defaultpath index.html up ./swarm-social`

1.  default
2. 18.4 GB
3. ~35 mb (many files) and I hope it ignores .hidden files when uploading. (git hidden files are 52mb)
4. what ever swarm does by default
5. go-ethereum hash: `89451f7c382ad2185987ee369f16416f89c28a7d`

**Comment by winsvega** [comment]
> I upload many large binaries, which trigger garbage collection, and .pdfs from 1. are no longer retrievable.

if thats the case. this might be just what is happening on our node. as it get data from the network it could just overwrite out locally uploaded files. so even if I reupload it again it will be overwriteen (garbage collected rather soon (10 seconds actually))  so there should be `--presistent` flag that protects the data from being erased when using the command `swarm up `

But why data is becoming unavailable? should not it be stored on many nodes of the network?

**Comment by nonsense** [comment]
@winsvega thanks for your answers. It would be worth trying with `swarm v0.3.4` and see if it still happens.

3. swarm does NOT ignore hidden files, which means you are also uploading the `.git` files.

Based on your answer in 2. it sounds like you are hitting the default limit of 20GB and garbage collection is being triggered.

**Comment by zelig** [comment]
still wip #976
