### ISSUE TITLE
Setup a long running cluster

### ISSUE THREAD

**Issue by holisticode** [ethersphere/swarm#937]
We have the public cluster, running the latest stable version.

But we develop against `master`, and he should probably have a way to test against a long running network before releasing.

**Comment by nonsense** [comment]
I think this is the `open` cluster currently. Everyone on the team has access to it, and we deploy occasionally the `master` commit.

Could you expand on what your ideal setup is? Do you want us to deploy on every `master` commit?

**Comment by nonsense** [comment]
What would be run as tests? We are already running the CI test suite on every commit, and I am manually running the smoke tests when we deploy to the `open` cluster (which anyone can do).

What other tests should do you have in mind?

**Comment by nonsense** [comment]
Closing in favour of https://github.com/ethereum/swarm-cluster/issues/91
