### ISSUE TITLE
Create simulations for realistic environments

### ISSUE THREAD

**Issue by holisticode** [ethersphere/swarm#939]
It may be beneficial to create environments where we can test scenarios which should be expected in normal swarm operation.

For example 
* very dynamic clusters (lots of disconnects)
* very "alive" clusters (logs of uploads/downloads)

This can be achieved with complex simulations and/or planned test scenarios on "real" clusters.

**Comment by nonsense** [comment]
I find this a bit vague. What would be the expectation of such tests? In its current form, if we have `very dynamic cluster (lots of disconnects)`, then Swarm won't work at all, and I think this is expected.

I don't find this issue very actionable, I think we should define more precisely what we want from our test environment.

**Comment by holisticode** [comment]
Expectation: 
* What happens to swarm if there are many nodes disconnecting?

> In its current form, if we have very dynamic cluster (lots of disconnects), then Swarm won't work at all, and I think this is expected.

Yes and no. If all nodes are very dynamic, then of course you are right. But the scenario I am thinking of is a "core" set of stable nodes (could be our cluster and other "trusted" clusters and nodes), and a variable set of flaky nodes. 

I have always raised the issue that the easiest attack on Swarm is to just bring many nodes online, and then disconnect them. Many nodes would still be running in this scenario. I think we should be trying to at least anticipate some of such attacks, and see how swarm behaves.

In fact I maintain my suggestion made earlier that some kind of "trust" metric which simply represents uptime could be meaningful: only nodes which have some minimum "uptime" become trustworthy, or even "syncable" (of course this doesn't guarantee much but at least makes attacks more costly). Anyway, this is a topic of itself.

* `very "alive" clusters (logs of uploads/downloads)`
I believe this should be a core scenario which we need to address. It corresponds to long-running network behavior. What happens when a network is running for long, and there are many uploads and downloads? How do singular nodes behave (resource usage, chunk saving, garbage collection)? How does the network behave (do chunks get lost, how long are files retrievable, etc.)? It is also a good preparation for when we will have insurance and swap live, because in that scenario, nodes will of course try to maximize their profits, so what happens to non-insured chunks? Are they ignored altogether? How long do non-insured uploads remain retrievable? Etc. etc. etc.
