### ISSUE TITLE
EIP-1577 - implement resolver contract changes

### ISSUE THREAD

**Issue by acud** [ethersphere/swarm#940]
[EIP-1062](https://ethereum-magicians.org/t/eip-1062-formalize-ipfs-hash-into-ens-ethereum-name-service-resolver/281/22) has evolved into [EIP-1577](https://ethereum-magicians.org/t/eip1577-multiaddr-support-for-ens/1969), which incorporates the use of `multiaddr` schemes into the resolver contract on ENS.

This allows clients to know from which Dstorage provider to request the content addressed hash directly from the resolver.

See:
https://ethereum-magicians.org/t/eip1577-multiaddr-support-for-ens/1969
status-im/status-react#6688
https://eips.ethereum.org/EIPS/eip-1577
ethereum/EIPs#1577

New contract: https://github.com/ensdomains/resolvers/blob/master/contracts/PublicResolver.sol

**Comment by acud** [comment]
related to https://github.com/ethereum/swarm-dapps/issues/28

**Comment by acud** [comment]
ref https://www.npmjs.com/package/content-hash for documentation

**Comment by cobordism** [comment]
In particular, Swarm needs to support the new resolvers with the multiaddr field.

For example the resolver deployed here: 0xd3ddccdd3b25a8a7423b5bee360a42146eb4baf3
