### ISSUE TITLE
TTL or hop counting to prevent infinite request loops

### ISSUE THREAD

**Issue by gbalint** [ethersphere/swarm#942]
There is already one PR to solve this: https://github.com/ethersphere/go-ethereum/pull/941

**Comment by acud** [comment]
idea:
what about that when doing a search for a chunk - once a node forwards a request for a chunk from another node - its search should not be sent to more distant nodes and only the node which is the request originator can escalate the search and ask which are farther away nodes once the current depth cascade exhausts itself. @zelig wouldn't this work in a healthy kademlia? the node should know the lookup scope according to the chunk address in conjunction with the node address.

**Comment by nonsense** [comment]
Solved by https://github.com/ethereum/go-ethereum/pull/17757
