### ISSUE TITLE
Better test environment in AWS

### ISSUE THREAD

**Issue by gbalint** [ethersphere/swarm#943]
This could be a whole project, with on-demand cluster, simulating network environments, etc.

Let's make a plan for this

Think about these:
https://github.com/ethersphere/go-ethereum/issues/937
https://github.com/ethersphere/go-ethereum/issues/938
https://github.com/ethersphere/go-ethereum/issues/939

**Comment by nonsense** [comment]
I consider this ready, so will close for now.

We can iterate further based on requirements from the team.
