### ISSUE TITLE
change file mime type detection to magic number

### ISSUE THREAD

**Issue by acud** [ethersphere/swarm#944]
currently, when uploading a single file, swarm detects the mime type using the file extension with a fallback to the http package's mime type detection which detects MIME through magic numbers.

when uploading a directory though, the content type for each file is set using an extension-to-mime detection.
both should use the same mime detection mechanism which is magic-number based.

**Comment by nizsheanez** [comment]
But using only magic-number based detection looks not enough featured: 
- It will return "application/octet-stream" for .js, .css, .html files. For all extensions defined in `mime.builtinTypesLower` 

I feel that `mime.builtinTypesLower` is useful if you wanna serve websites from Swarm without additional front http server to rewrite Content-Type of .js/.css/.html 

I had free time and did example implementation: https://github.com/ethersphere/go-ethereum/pull/945/ 
- implementation has 1 problem - tests now based on non-exist files, i can mock `os.Open` method. Didn't for simplicity.

**Comment by acud** [comment]
> It will return "application/octet-stream" for .js, .css, .html files. For all extensions defined in mime.builtinTypesLower

Fair enough, I did not take this fully into consideration and am convinced. 
I would however, change the order of detection to be magic-number first (to also take into account cases where files have incorrect/no extension at all), then if you get an `application/octet-stream` from that - try extension based detection, with a fallback to `application/octet-stream` in the end.

About testing for real files - as long as the way that we call the `http.DetectContentType` as per the go spec - I'm fine with the test cases you have provided (testing for fallbacks).

For the sake of overcoming the sequence of magic-number-first - you can create a temp file with the extension you're looking for and check that the fallback to the extension content type detection works.

**Comment by nizsheanez** [comment]
Done
