### ISSUE TITLE
p2p/simulations: panic in RegisterServices

### ISSUE THREAD

**Issue by divan** [ethersphere/swarm#946]
Hi there,

## Problem
in [p2p/simulations/adapters/types.go](https://github.com/ethersphere/go-ethereum/blob/master/p2p/simulations/adapters/types.go#L239) there is a panic call in `adapter.RegisterServices()` when service is already registered and the design of this package assumes that service registration should be done only once (in init).

I'm [using](https://github.com/status-im/simulation/blob/master/propagation/whisperv6/simulator.go#L47) this for simulations server, where on each request a new simulation is being created and executed, and this design/panic doesn't play well.

## Solution
I guess the naive solution would be to add `UnregisterServices()` method or add `sync.Once()` wrapper, but I also feel like there is a space for a redesign. Maybe `services` could be made a property of `SimAdapter`, instead of being global package property? That should simplify simulator API and make it possible to creates/destroy new simulations on demand.
What do you think?

I can work on it as soon as there is a consensus on the solution.

**Comment by zelig** [comment]
i am closing aas non-issue @divan 
please reopen if necessary
