### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by sakabrawala** [ethersphere/swarm#949]
Hi there,
I am trying to implement a private Ethereum based blockchain between multiple nodes (Raspberry Pi's - a small microcontroller) which can share files between the nodes using 'swarm'. I followed the steps provided by the [swarm documentation](https://swarm-guide.readthedocs.io/en/latest/gettingstarted.html#running-swarm). Everything was working fine until I encountered this problem.
The swarm console crashes on typing the 'swarm up /file OR swarm --bzzapi http://localhost:8500 up /file'. I have attached the actual outputs and expected outputs below. Before heading to that here's my system information - 

#### System information

Geth version: `1.8.17-unstable
Architecture: arm
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10.3
Operating System: linux`

Swarm Version: 0.3.5-unstable

Go Version: go1.10.3

#### Expected behaviour
`swarm up /path/to/example.md
> d1f25a870a7bb7e5d526a7623338e4e9b8399e76df8b634020d11d969594f24a`

Here the file converts into hash. And can be accessed on the local host by typing - 

`http://localhost:8500/bzz:/d1f25a870a7bb7e5d526a7623338e4e9b8399e76df8b634020d11d969594f24a/
`
#### Actual behaviour
But lately I have been getting this - 

`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x23048]

goroutine 847 [running]:
sync/atomic.addUint64(0x13069d2c, 0x1, 0x0, 0x20, 0x122ff700)
	/usr/local/go/src/sync/atomic/64bit_arm.go:31 +0x4c
github.com/ethereum/go-ethereum/swarm/storage.(*hasherStore).storeChunk(0x13069d10, 0xac41c0, 0x1237fe20, 0x122ff700)
	/home/pi/go/src/github.com/ethereum/go-ethereum/swarm/storage/hasherstore.go:240 +0x34
github.com/ethereum/go-ethereum/swarm/storage.(*hasherStore).Put(0x13069d10, 0xac41c0, 0x1237fe20, 0x11c68600, 0xa, 0x1008, 0x124cdfcc, 0x7a5d4, 0x0, 0x4, ...)
	/home/pi/go/src/github.com/ethereum/go-ethereum/swarm/storage/hasherstore.go:79 +0x78
github.com/ethereum/go-ethereum/swarm/storage.(*PyramidChunker).processChunk(0x119958c0, 0xac41c0, 0x1237fe20, 0x1, 0x0, 0x1237ffa0)
	/home/pi/go/src/github.com/ethereum/go-ethereum/swarm/storage/pyramid.go:293 +0xd0
github.com/ethereum/go-ethereum/swarm/storage.(*PyramidChunker).processor(0x119958c0, 0xac41c0, 0x1237fe20, 0x1, 0x0)
	/home/pi/go/src/github.com/ethereum/go-ethereum/swarm/storage/pyramid.go:283 +0x68
created by github.com/ethereum/go-ethereum/swarm/storage.(*PyramidChunker).prepareChunks
	/home/pi/go/src/github.com/ethereum/go-ethereum/swarm/storage/pyramid.go:401 +0xf8
`

**If it's the memory issue, then there's no way we can remove/delete the file/data saved in the logs/in the temp memory. It's a persistent data structure. 
By doing `geth remove` will surely delete the chaindata and the light/fast/full data but not the swarm data.**

Any help regarding this will be highly appreciated.

**Comment by acud** [comment]
@SmitKabrawala can you please elaborate on:
1. file size/content size in bytes (the content size that you're trying to upload)
2. does the cli tool immediately panic or is there a delay between the command and the process exit? (i.e. deadlock involved?)
3. can you please paste the entire terminal output (from issuing the command till end of error output) and post it in a gist?
4. did you build from source? if so - please provide the commit hash you're building
5. can you please paste the exact command you're using to start the actual swarm node?

Thanks!

**Comment by sakabrawala** [comment]
SOLVED - 
@justelad I found a way to solve this - 
@janos 
- The Geth and swarm need to be of the latest and **Stable** version especially.
- If one of them is of unstable version then - it will give a panic issue stating a nil pointer dereference. Since you cannot delete or drop the data in Swarm network (it's a persistent data structure) so you need to pay attention to the architecture of the micro-controller. 
- Raspberry Pi 3 - uses ARMV7 architecture.  So downloading a Stable version of GETH and GO will work. 
- I tried just 4kb file.  This is how I initiated the swarm network using swarm console  `swarm --bzzaccount address` & adding peers in the network by `geth --exec='admin.addPeer(enode of the 2nd node in the network) attach ipc:/home/.ethereum/bzzd.ipc` 
- `geth --syncmode "light"` initates a private blockchain syncing the blocks in the network. The command for uploading a file in the swarm network - `swarm --bzzapi http://localhost:8500 up /home/file.txt`

**Comment by nonsense** [comment]
This is solved on `master`. Will be released as part of Swarm v0.3.5.
