### ISSUE TITLE
[Bug] Problem with ACT and protecting content with Elliptic curve keys

### ISSUE THREAD

**Issue by xrn** [ethersphere/swarm#952]
I skipped proposed steps description because bug is simple.

I tested file Encryption using, password - https://swarm-guide.readthedocs.io/en/latest/usage.html#password-protection - and everything looks ok, it works but when I would like to use keys I got an error.

Keys file:
`$ cat keys 
02e6f8d5e28faaa899744972bb847b6eb805a160494690c9ee7197ae9f619181db`

100% I have not white spaces, I checked many times. I checked with two different public keys with the single line break between them - same result.

Command:
`swarm --bzzaccount ec8cefcdfe5bc288e42fcd946ff2d4e52f1b8cb6 access new act --grant-keys ./keys 6041adf5169262d117a281d0dfcbbfc5e9b2ae321555a6896c8fad44c4420707837801190f441b32bcdf3fb806e5175536100f2125d6f754dc6c67204e39aee8`

I of course testes full path for keys file, for pass exercise this notation is working

Error
`Fatal: error generating ACT manifest: need a grantee Public Key`

Geth:
- version: 1.8.16-stable
- git commit: 477eb0933b9529f7deeccc233cc815fe34a8ea56
- Ubuntu 18.04.1 LTS

Swarm:
- version: 0.3.4-stable
- git commit: 477eb0933b9529f7deeccc233cc815fe34a8ea56
- go version: go1.10.1

**Comment by nonsense** [comment]
@xrn this has been fixed on `master`, and will be part of next release.
