### ISSUE TITLE
ChunkStore.Get can not retrieve chunk - context deadline exceeded

### ISSUE THREAD

**Issue by nonsense** [ethersphere/swarm#954]
```
swarm_30399 WARN [10-01|11:10:47.282|swarm/network/stream/delivery.go:164] ChunkStore.Get can not retrieve chunk    err="context deadline exceeded"
```

We have thousands of these warnings on the public testnet. 200 per second on specific nodes.

Swarm version: v0.3.4

**Comment by acud** [comment]
@nonsense can you update if this is still an issue?

**Comment by nonsense** [comment]
@justelad yes still an issue, although it doesn't happen as often as before.

![screen shot 2018-10-04 at 16 42 35](https://user-images.githubusercontent.com/50459/46481822-7f826600-c7f4-11e8-9a7e-d2708638bbf3.png)

**Comment by nonsense** [comment]
The `hopcount` reaching 20 is what is actually stopping this from an infinite loop.

**Comment by nonsense** [comment]
I am pretty sure we still have this problem.

How can we be sure that this is fixed with a single deployment of the new BZZ protocol version? Deploying a single version of https://github.com/ethereum/go-ethereum/pull/18184 won't have any peers (as there aren't any other peers in the network that support that version), and obviously there won't be any chunk retrieval requests.

We should have waited for at least a few days, after deploying the upcoming release to decide if this is fixed or not.

**Comment by zelig** [comment]
let's reopen then fine
