### ISSUE TITLE
BUG: CORS issue upload failing

### ISSUE THREAD

**Issue by x5engine** [ethersphere/swarm#956]
Hi there,
I am having CORS issues? did you change something guys?? send a post data to https://swarm-gateways.net/bzz:/ with sample data or even a small file and it fails! it used to work!

All my request are failing to send a file which used to work
then throwing Failed to load "Response to preflight request doesn't pass "

#### System information

OS & Version: Windows 10
Server : Ubuntu 16
#### Expected behaviour
File gets uploaded and get a hash

#### Actual behaviour
CORS not allowed and failing

#### Steps to reproduce the behaviour
just host it locally or another domain that the gateway and try it

#### Backtrace

````
https://swarm-gateways.net/bzz:/: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://localhost:3000' is therefore not allowed access
````

Thank you

**Comment by dleonard00** [comment]
Our team at mainframe identified the same issue. Will try and spend some cycles on this soon.

**Comment by acud** [comment]
@dleonard00 [this](https://github.com/ethereum/swarm-cluster/commit/4783bcd207c8b315454c4df0d0ce27550bcae108) might be the reason.
Also, @dleonard00 - can you say if this is also happening with your nodes (when you post to your own gateway) or is this just in conjunction with `swarm-gateways.net`?

**Comment by nonsense** [comment]
@meteorplus `swarm-gateways.net` has CORS set to * again.

I am leaving this issue open, because we haven't sorted out the underlying issue. Command-line flags as `--corsdomain *` doesn't work (when it used to work for Swarm v0.3.3), whereas `--corsdomain=*` works.

**Comment by nonsense** [comment]
@dleonard00 do you mean you identified that CORS is disabled on `swarm-gateways.net` or that CORS flag behaviour changed between 0.3.3 and 0.3.4 ? If it is the former, don't waste time on it, if it is the latter, let's have a chat :)

**Comment by x5engine** [comment]
Thank you @nonsense  for you help 👍

**Comment by acud** [comment]
closing this since this is not a bug in our software but caused due to the shell expanding the asterisk sign
