### ISSUE TITLE
create cloudformation templates to spin up contributed nodes

### ISSUE THREAD

**Issue by acud** [ethersphere/swarm#975]
The purpose of this ticket is to allow users/organisations that would like to contribute Swarm nodes to be able to spin them up through a public AWS CloudFormation template.

Notes:

- ENS resolution is up to the implementer (if necessary at all). However using Infura might be a good possibility.

- Defaults should be:
```
network id=3
storage=40-50gb
log level=INFO
```

- nodes should run with --debug flag
- no monitoring stack
- no custom bootnodes
- no geth container

- User should be able to change the node parameters through the template (or at least the relevant ones)

- The setup should be for a swarm node, not for a swarm gateway, as we would like this to facilitate more nodes to join the network and contribute to the aggregate of collective storage.

- Node addressing and storage persistence should be taken into account also - in the case of upgrades to the swarm code and so on.

Any questions should be posted through this issue.
Thank you <3

**Comment by nagas** [comment]
* Do you have any preference on how Swarm node should be running on AWS? (e.g., as a container on Amazon ECS or self-managed EC2 instance).
* Do you provide any pre-baked AMI with Swarm setup or Docker container?
* Adjusting parameters should be only possible upon initial setup or also at a later point while Swarm is running? (the latter would require custom scripting to restart Swarm container/daemon).
* How do you see long-running maintenance of this setup? E.g., should Swarm version auto-update itself or only via changing parameters in the template and updating CloudFormation stack?
* How bzzaccount and keystore/password should be provided without a geth node?

**Comment by acud** [comment]
initial version done by @nagas.

[video guide](https://drive.google.com/file/d/1ZPKTGF1XWxUaI1imvgKZipLK7xCsq35Q/view), [repo](https://github.com/nagas/ethereum-swarm-cloudformation), [docs](https://github.com/nagas/ethereum-swarm-cloudformation/tree/master/docs).

once stability is improved we can communicate this to the community
