### ISSUE TITLE
Feed CLI: Lack of information about wrong signature

### ISSUE THREAD

**Issue by xrn** [ethersphere/swarm#979]
Hi there,

Geth: 1.8.17-stable
Swarm: 0.3.5-stable

This fix will improve the user experience.

I have on the server private key for the account 
`0x87d964FaB26fF7001b9037eac09447e4987D5639`

I am creating feed for unkow user
`swarm feed create --topic 0xCA978112CA1BBDCAFAC231B39A23DC4DA786EFF8147C4E72B9807785AFEE48BB --user 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
`
And I receive manifest
`0851b7d2c3c198326f67c0b0f7eeb8b6e4b10314a7d4fcbc59977351a16c5be6`

Then I would like to update it 
`swarm --bzzaccount 87d964fab26ff7001b9037eac09447e4987d5639 feed update --manifest 0851b7d2c3c198326f67c0b0f7eeb8b6e4b10314a7d4fcbc59977351a16c5be6 0x4e616d653a20436f6e73656e737973
INFO [11-03|13:36:29.555] Maximum peer count                       ETH=25 LES=0 total=25
Unlocking swarm account 0x87d964FaB26fF7001b9037eac09447e4987D5639 [1/3]
Passphrase: `

Of course, the feed does not update but I do not receive any error. In the command line, everything looks good.

**Comment by xrn** [comment]
Same problem with https://swarm-guide.readthedocs.io/en/latest/usage.html#javascript-example

From one side this is not working for me, but more important thing is that request is returning 200 instead for example 403

**Comment by jpeletier** [comment]
https://github.com/ethereum/go-ethereum/pull/18047 fixes this.

**Comment by jpeletier** [comment]
> Same problem with https://swarm-guide.readthedocs.io/en/latest/usage.html#javascript-example
> 
> From one side this is not working for me, but more important thing is that request is returning 200 instead for example 403

@xrn can you open a separate issue together with a complete JS sample to reproduce this? - Thanks

**Comment by xrn** [comment]
@jpeletier tested after release 0.3.7 - everything is working, response:

`Fatal: Signer address does not match the update request`
