### ISSUE TITLE
Access control: Requesting hash with HTTP basic authentication does not return content

### ISSUE THREAD

**Issue by petyaracz** [ethersphere/swarm#984]
#### System information

Swarm version: 0.3.6-unstable
Geth version: 1.8.18-unstable
Go Version: go1.10.3
OS: darwin

#### Expected behaviour

I run a local swarm node. I upload content. 
I password-protect this content. 
I request it using curl with authentication. 
It returns the content.

#### Actual behaviour

I get a 401 error w/ a `cant decrypt - forbidden` msg.

#### Steps to reproduce the behaviour

```
echo "mypassword" > mypassword.txt
echo "testfile" > mytest.txt
swarm up mytest.txt
```
> c281f27042493bdf23da06ea387d01d783cfc884e04961324af3769203aae394
```
swarm access new pass --password mypassword.txt c281f27042493bdf23da06ea387d01d783cfc884e04961324af3769203aae394
```
> 86c7b5953117bcf46d0870db646df1d7bd2581413c9a041e0c2ac19136995eb9
```
swarm  --password mypassword.txt down bzz:/86c7b5953117bcf46d0870db646df1d7bd2581413c9a041e0c2ac19136995eb9 out.txt
cat out.txt
```
> testfile
```
curl http://:mypassword@localhost:8500/bzz:/86c7b5953117bcf46d0870db646df1d7bd2581413c9a041e0c2ac19136995eb9/
```
> Code: 401
> Message: cant decrypt - forbidden

**Comment by petyaracz** [comment]
`curl http://x:mypassword@localhost:8500/bzz:/<reference of access controlled manifest>/` works indeed.

but `swarm --password mypassword.txt down <ref>` also works.

**Comment by acud** [comment]
ah true. just looked in the code and indeed this is supported for password. it would probably work also for ACT if doing so from the publisher/grantee node
