### ISSUE TITLE
PSS neighbourhood addressing simulation

### ISSUE THREAD

**Issue by adamschmideg** [ethersphere/swarm#987]
Follow-up on #965 and relies on https://github.com/ethereum/go-ethereum/pull/17991

**Comment by adamschmideg** [comment]
@justelad is interested in joining

**Comment by acud** [comment]
@nolash given the complexity and your bandwidth - is this something i could help with?

**Comment by acud** [comment]
@nolash would be happy to if this is ready for review 👍

**Comment by nolash** [comment]
In progress https://github.com/ethersphere/go-ethereum/pull/1016
