### ISSUE TITLE
Progress bars when uploading to Swarm

### ISSUE THREAD

**Issue by adamschmideg** [ethersphere/swarm#988]
A frontend to display these progress bars for a file
1. stored to localstore
2. sent for syncing
3. acknowledged as synced (fixes #460)

**Comment by nolash** [comment]
@adamschmideg is this really priority for stability?

**Comment by adamschmideg** [comment]
I'm not sure, but @zelig seems positive about it. I hope he can give us more insights.

**Comment by zelig** [comment]
delivered in https://github.com/ethersphere/swarm/pull/1649
