### ISSUE TITLE
fix pss forwarding

### ISSUE THREAD

**Issue by zelig** [ethersphere/swarm#995]
Previously, redundancy forwards would be made if the previous peer was among nearest neighbors or within the "dark radius" (proximity order within the bounds of the part of the address not disclosed). However, it would not check if the next peer actually was within these bounds.

**Comment by nolash** [comment]
pending merge of https://github.com/ethersphere/go-ethereum/pull/965

**Comment by nolash** [comment]
PR in progress: https://github.com/ethersphere/go-ethereum/pull/1008

**Comment by acud** [comment]
@zelig @nolash @gluk256 please give a description of what was exactly the bug, and what the PRs involved are doing. 

@gluk256's PR referenced this issue but it is not clear what was the original problem was in the first place, for those not involved.

**Comment by nolash** [comment]
@justelad copied the original problem description from https://github.com/ethersphere/go-ethereum/pull/1008 to the issue.

The PR should describe themselves so I won't put that here.

**Comment by zelig** [comment]
merged as. https://github.com/ethereum/go-ethereum/pull/18353
